"""Metrics any shipped view references. GENERATED -- do not edit.

Regenerate with tools/gen_metric_scope.py after changing tools/build_view.py.

69 kinds, 1636 metrics defined; 253 referenced by views; 1383 not.
45 kinds are referenced by no view at all and can be skipped
entirely, which is the only thing that saves a round trip -- the vSAN perf API
returns every metric of an entity type in one query.
"""

COVERED = {
    "VsanClusterCapacity": (
        "dedupRatio",
        "free",
        "savedByDedup",
        "total",
        "used",
    ),
    "VsanClusterDomclient": (
        "congestion",
        "iopsRead",
        "iopsWrite",
        "latencyAvgRead",
        "latencyAvgWrite",
        "oio",
        "readCongestion",
        "throughputRead",
        "throughputWrite",
        "unmapCongestion",
        "writeCongestion",
    ),
    "VsanClusterDomcompmgr": (
        "congestion",
        "iopsRead",
        "iopsRecWrite",
        "iopsResyncRead",
        "iopsWrite",
        "latAvgResyncRead",
        "latencyAvgRead",
        "latencyAvgRecWrite",
        "latencyAvgWrite",
        "oio",
        "throughputRecWrite",
        "tputResyncRead",
    ),
    "VsanClusterDomowner": (
        "avgResyncParallelism",
        "congestion",
        "iopsRead",
        "iopsRecWrite",
        "iopsResyncRead",
        "iopsWrite",
        "latencyAvgRead",
        "latencyAvgWrite",
        "numCompleteFullResyncOps",
        "numCompleteResyncOps",
        "numInflightPriorityResyncJobs",
        "numInflightSharedResyncJobs",
        "numPendingDecomResyncJobs",
        "numPendingFullResyncJobs",
        "numPendingResyncJobs",
        "numRunningFullResyncJobs",
        "numRunningResyncJobs",
        "numSuspendedResyncJobs",
        "oio",
        "readCongestion",
        "tputRead",
        "tputWrite",
        "writeCongestion",
    ),
    "VsanClusterRdtLatency": (
        "avgLatency",
        "kaReset",
        "maxLatency",
        "minLatency",
        "numReadyDelay",
        "rxSbSpaceMin",
        "txQLatAvg",
        "txSbSpaceMin",
    ),
    "VsanClusterZdomTopStats": (
        "iopsRead",
        "iopsWrite",
        "latencyAvgRead",
        "latencyAvgWrite",
        "oio",
        "throughputRead",
        "throughputWrite",
    ),
    "VsanCmmdsNet": (
        "groupRx",
        "groupRxThroughput",
        "groupTxMcast",
        "groupTxMcastThroughput",
        "groupTxUcast",
        "groupTxUcastThroughput",
        "rdtRx",
        "rdtRxThroughput",
        "rdtTx",
        "rdtTxThroughput",
    ),
    "VsanEsaDiskLayer": (
        "avgLatReadCapacity",
        "avgLatWriteCapacity",
        "avgLatWritePerf",
        "iopsReadCapacity",
        "iopsWriteCapacity",
    ),
    "VsanEsaDiskScsifw": (
        "latencyDevDAvg",
        "latencyDevGAvg",
        "latencyDevKAvg",
        "latencyDevRead",
        "latencyDevWrite",
    ),
    "VsanHostCpu": (
        "coreUtilPct",
        "pcpuUsedPct",
        "pcpuUtilPct",
    ),
    "VsanHostDomclient": (
        "congestion",
        "iopsRead",
        "iopsWrite",
        "latencyAvgRead",
        "latencyAvgWrite",
        "oio",
    ),
    "VsanHostDomcompmgr": (
        "iopsRead",
        "iopsWrite",
        "latencyAvgRead",
        "latencyAvgWrite",
        "latencyMaxRead",
        "latencyMaxWrite",
        "latencyStddevWrite",
        "namespaceDispatchedCostWrite",
        "oio",
        "throughputRead",
        "throughputWrite",
        "vmdiskDispatchedCostWrite",
        "vmdiskQueueDepthWrite",
    ),
    "VsanHostDomowner": (
        "highOIODurationPercentWrite",
        "iops",
        "iopsSegCleanerUnmap",
        "iopsUnmap",
        "latencyAvgRead",
        "latencyAvgSegCleanerUnmap",
        "latencyAvgUnmap",
        "latencyAvgWrite",
        "latencyMaxRead",
        "latencyMaxSegCleanerUnmap",
        "latencyMaxUnmap",
        "latencyMaxWrite",
        "latencyStddevSegCleanerUnmap",
        "latencyStddevWrite",
        "numNetSchedControllerIopsLimit",
        "numNetSchedGuestLTLatUs",
        "numNetSchedLowBand",
        "numNetSchedLowBandSec",
        "numNetSchedLowBandThreshUs",
        "numNetSchedLowToMidBand",
        "numNetSchedMidBand",
        "numNetSchedMidBandSec",
        "numNetSchedMidToLowBand",
        "numNetSchedRollingAvgLatUs",
        "numNetSchedSeenNonResyncTpBps",
        "numNetSchedSeenTotalTpBps",
        "oio",
        "owner2PCCommitLatencyAvgUs",
        "readLeafOwnerLatencyLocal",
        "readLeafOwnerLatencyRemote",
        "segCleanerUnmapLeafOwnerMaxLatencyAvgUs",
        "serverSwitchCount",
        "throughputSegCleanerUnmap",
        "unmapCount",
        "writeLeafOwnerLatencyLocal",
        "writeLeafOwnerLatencyRemote",
    ),
    "VsanHostNet": (
        "portRxDrops",
        "portTxDrops",
        "rxPackets",
        "rxPacketsLossRate",
        "rxThroughput",
        "txPackets",
        "txPacketsLossRate",
        "txThroughput",
    ),
    "VsanHostZdomTopStats": (
        "iopsRead",
        "iopsWrite",
        "latencyAvgRead",
        "latencyAvgWrite",
        "oio",
        "oioWrite",
        "readLatencyMaxUs",
        "throughputRead",
        "throughputWrite",
        "unmapLatencyMaxUs",
        "writeLatencyMaxUs",
    ),
    "VsanMemory": (
        "clomdConsumedSize",
        "clomdReservedSize",
        "cmmdsdConsumedSize",
        "cmmdsdReservedSize",
        "epdConsumedSize",
        "kernelConsumedSize",
        "kernelReservedSize",
        "osfsdConsumedSize",
        "uwConsumedSize",
        "uwReservedSize",
        "vsandevicemonitordConsumedSize",
        "vsanmgmtdConsumedSize",
    ),
    "VsanPnic": (
        "ioChainDrops",
        "ioChainRxdrops",
        "ioChainTxdrops",
        "pauseCount",
        "pfcCountRaw",
        "portRxDrops",
        "portTxDrops",
        "portTxpkts",
        "rxCrcErr",
        "rxCrcErrRaw",
        "rxErr",
        "rxFifoErr",
        "rxMissErr",
        "rxMissErrRaw",
        "rxOvErr",
        "txCarErr",
        "txErr",
    ),
    "VsanRdtLatency": (
        "avgLatency",
        "kaReset",
        "maxLatency",
        "minLatency",
        "numReadyDelay",
        "rxSbSpaceMax",
        "rxSbSpaceMin",
        "txQLatAvg",
        "txQLatMax",
        "txSbSpaceMin",
    ),
    "VsanTcpIp": (
        "tcpErrs",
        "tcpHalfopenDropRate",
        "tcpRcvdupackRate",
        "tcpRcvduppackRate",
        "tcpRcvoopackRate",
        "tcpRxErrRate",
        "tcpSackRcvBlocksRate",
        "tcpSackRexmitsRate",
        "tcpSackSendBlocksRate",
        "tcpSndZeroWin",
        "tcpTimeoutDropRate",
        "tcpTxRexmitRate",
    ),
    "VsanVirtualMachine": (
        "iopsRead",
        "iopsWrite",
        "latencyRead",
        "latencyWrite",
        "throughputRead",
        "throughputWrite",
    ),
    "VsanVnic": (
        "portRxDrops",
        "portRxpkts",
        "portTxDrops",
        "portTxpkts",
        "rxPackets",
        "rxPacketsLossRate",
        "rxThroughput",
        "txPackets",
        "txPacketsLossRate",
        "txThroughput",
    ),
    "VsanVnicRdtLatency": (
        "avgLatency",
        "kaReset",
        "maxLatency",
        "minLatency",
        "numReadyDelay",
        "rxSbSpaceMin",
        "txQLatAvg",
        "txQLatMax",
        "txSbSpaceMin",
    ),
    "VsanVscsi": (
        "iopsRead",
        "iopsWrite",
        "latencyRead",
        "latencyWrite",
    ),
    "VsanZdomVtx": (
        "checkpointWorkerWakeupMs",
        "latAvgTotalOpIO",
        "latAvgTxnBank",
        "maxDiscUsedPct",
        "rateBankFlushTotalCacheRef",
        "rateSegCleaningCtxDataTotalCacheRef",
        "rateTotalCacheRef",
        "rateTxnLookupCacheRef",
        "rateTxnPrefetchTotalCacheRef",
        "rateTxnReadWrite",
    ),
}

# Kinds no view references. Skipping these skips their query.
UNCOVERED_KINDS = (
    "VsanCacheDisk",
    "VsanCapacityDisk",
    "VsanClomDisk",
    "VsanClomHost",
    "VsanClusterEsaDedupDomclientIo",
    "VsanClusterEsaDedupDomcompmgrIo",
    "VsanClusterEsaDedupDomownerIo",
    "VsanClusterEsaDedupStoreChunksvc",
    "VsanClusterEsaDedupStoreHashsvc",
    "VsanClusterPmem",
    "VsanClusterRemotedomclient",
    "VsanClusterResync",
    "VsanCmmdsWorkload",
    "VsanComputeClusterRemotedomclient",
    "VsanComputeHostRemotedomclient",
    "VsanCpu",
    "VsanDdhDisk",
    "VsanDirectCluster",
    "VsanDirectHost",
    "VsanDiskGroup",
    "VsanDistribution",
    "VsanDomWorld",
    "VsanDpHistoricalStats",
    "VsanFileService",
    "VsanHeapMemory",
    "VsanHostEsaDedupDomclientIo",
    "VsanHostEsaDedupDomcompmgrIo",
    "VsanHostEsaDedupDomownerIo",
    "VsanHostEsaDedupStoreChunksvc",
    "VsanHostEsaDedupStoreHashsvc",
    "VsanHostPmem",
    "VsanHostRemotedomclient",
    "VsanHostVsansparse",
    "VsanIoinsight",
    "VsanIscsiHost",
    "VsanIscsiLun",
    "VsanIscsiTarget",
    "VsanLsomWorldCpu",
    "VsanRdtNet",
    "VsanRemoteVirtualDisk",
    "VsanRemoteVirtualMachine",
    "VsanRemoteVscsi",
    "VsanSlabMemory",
    "VsanSystemMemory",
    "VsanVirtualDisk",
)
