"""GENERATED -- do not edit by hand.

Regenerate:
    python3 tools/build_metric_labels.py /tmp/hcib_labels.json

Units are harvested from HCIBench's Grafana dashboards, which
cover the same underlying vSAN stats. Labels are expanded here
because HCIBench's titles are panel-level and shared across
several metrics.
"""

from typing import Dict

LABELS: Dict[str, str] = {
    'IOPSWithinBursts': 'IOPS within bursts',
    'IOPSWithinBurstsExclFirstObj': 'IOPS within bursts excl first obj',
    'IOPSWithinBurstsMultiObj': 'IOPS within bursts multi obj',
    'NIOPS': 'Normalized IOPS',
    'NIOPSDelayed': 'Delayed Normalized IOPS',
    'NIOPSRead': 'Niops (read)',
    'NIOPSReadDelayed': 'Niops read delayed',
    'NIOPSWrite': 'Niops (write)',
    'NIOPSWriteDelayed': 'Niops write delayed',
    'allOpCacheMaxGetLatUSec': 'All op cache max get latency u sec',
    'arpDropRate': 'ARP drop (rate)',
    'avgBurstArrivalTime': 'Burst arrival time (average)',
    'avgBurstArrivalTimeMultiObj': 'Burst arrival time multi obj (average)',
    'avgBurstCompletionTime': 'Burst completion time (average)',
    'avgBurstCompletionTimeMultiObj': 'Burst completion time multi obj (average)',
    'avgBurstPeakOIO': 'Burst peak outstanding IO (average)',
    'avgBurstPeakOIOMultiObj': 'Burst peak outstanding IO multi obj (average)',
    'avgBurstPeakOutstandingKb': 'Burst peak outstanding kb (average)',
    'avgBurstPeakOutstandingKbMultiObj': 'Burst peak outstanding kb multi obj (average)',
    'avgBurstTotalTime': 'Burst total time (average)',
    'avgBurstTotalTimeMultiObj': 'Burst total time multi obj (average)',
    'avgDeltaCreationDomActiveLatency': 'Delta creation DOM active latency (average)',
    'avgDeltaCreationDomCreationLatency': 'Delta creation DOM creation latency (average)',
    'avgLatReadCapacity': 'vSAN Layer Average Read Latency of vSAN ESA Disk',
    'avgLatReadPerf': 'Latency read perf (average)',
    'avgLatUnmapCapacity': 'Latency unmap capacity (average)',
    'avgLatUnmapPerf': 'Latency unmap perf (average)',
    'avgLatWriteCapacity': 'vSAN Layer Average Write Latency of vSAN ESA Disk',
    'avgLatWritePerf': 'Latency write perf (average)',
    'avgLatency': 'RDT Network VNIC Average Latency',
    'avgPctTimeToPeak': 'Percent time to peak (average)',
    'avgPctTimeToPeakMultiObj': 'Percent time to peak multi obj (average)',
    'avgResyncParallelism': 'Resync parallelism (average)',
    'avgRunPct': 'Run percent (average)',
    'avgUsedPct': 'Used percent (average)',
    'bandwidthWithinBursts': 'Bandwidth within bursts',
    'bandwidthWithinBurstsExclFirstObj': 'Bandwidth within bursts excl first obj',
    'bandwidthWithinBurstsMultiObj': 'Bandwidth within bursts multi obj',
    'burstsPerSecond': 'Bursts per second',
    'burstsPerSecondMultiObj': 'Bursts per second multi obj',
    'cacheAllocFails': 'Cache alloc fails',
    'cacheEntries': 'Cache entries',
    'cacheEvictAttempts': 'Cache evict attempts',
    'cacheHitRate': 'Cache Hit Rate',
    'cacheInserts': 'Cache inserts',
    'cacheLockContentions': 'Cache lock contentions',
    'cacheMissPerLookupTxn': 'Cache miss per lookup transaction',
    'cacheMissPerPrefetchTxn': 'Cache miss per prefetch transaction',
    'cacheMissPerSegCleaningCtxDataTxn': 'Cache miss per seg cleaning context data transaction',
    'cacheRemoves': 'Cache removes',
    'cacheUpdateLatency': 'Cache update latency',
    'checkpointWorkerWakeupMs': 'Checkpoint worker wakeup ms',
    'checksumMismatchCount': 'RDT Net Checksum Mismatch Count',
    'clientCacheHitRate': 'Local Client Cache Hit Rate',
    'clientCacheHits': 'Local Client Cache Hit IOPS',
    'clomdConsumedSize': 'Clomd consumed size',
    'clomdMemAllocMax': 'Clomd mem alloc (max)',
    'clomdMemAllocMin': 'Clomd mem alloc (min)',
    'clomdReservedSize': 'Clomd reserved size',
    'cmmdsTimeMachineConsumedSize': 'CMMDS time machine consumed size',
    'cmmdsTimeMachineMemAllocMax': 'CMMDS time machine mem alloc (max)',
    'cmmdsTimeMachineMemAllocMin': 'CMMDS time machine mem alloc (min)',
    'cmmdsTimeMachineReservedSize': 'CMMDS time machine reserved size',
    'cmmdsdConsumedSize': 'Cmmdsd consumed size',
    'cmmdsdMemAllocMax': 'Cmmdsd mem alloc (max)',
    'cmmdsdMemAllocMin': 'Cmmdsd mem alloc (min)',
    'cmmdsdReservedSize': 'Cmmdsd reserved size',
    'componentCongestion': 'Component congestion',
    'congestion': 'Congestions',
    'coreUtilPct': 'Percentage of CPU core uitilization',
    'dedupRatio': 'Space Efficiency Ratio',
    'deltaLeafGTEs': 'Delta leaf gt es',
    'deltaSourceChanges': 'Delta source changes',
    'ecCachedWriteCount': 'Ec cached write count',
    'ecCachedWriteHits': 'Ec cached write hits',
    'ecFswCount': 'Ec fsw count',
    'ecStridedWriteCount': 'Ec strided write count',
    'ecStridedWriteHits': 'Ec strided write hits',
    'ecWriteCount': 'Ec write count',
    'epdConsumedSize': 'Epd consumed size',
    'epdMemAllocMax': 'Epd mem alloc (max)',
    'epdMemAllocMin': 'Epd mem alloc (min)',
    'epdReservedSize': 'Epd reserved size',
    'free': 'Free Capacity',
    'groupRx': 'Group Inbound',
    'groupRxThroughput': 'Group Inbound Throughput',
    'groupTxMcast': 'Group Outbound Multicast',
    'groupTxMcastThroughput': 'Group Outbound Multicast Throughput',
    'groupTxUcast': 'Group Outbound Unicast',
    'groupTxUcastThroughput': 'Group Outbound Unicast Throughput',
    'highOIOAvgDurationMs': 'High outstanding IO avg duration ms',
    'highOIOAvgDurationMsRead': 'High outstanding IO avg duration ms (read)',
    'highOIOAvgDurationMsWrite': 'High outstanding IO avg duration ms (write)',
    'highOIOAvgIOCount': 'High outstanding IO avg IO count',
    'highOIOAvgIOCountRead': 'High outstanding IO avg IO count (read)',
    'highOIOAvgIOCountWrite': 'High outstanding IO avg IO count (write)',
    'highOIOAvgOIO': 'High outstanding IO avg outstanding IO',
    'highOIOAvgOIORead': 'High outstanding IO avg outstanding IO (read)',
    'highOIOAvgOIOWrite': 'High outstanding IO avg outstanding IO (write)',
    'highOIOBytes': 'High outstanding IO bytes',
    'highOIOBytesRead': 'High outstanding IO bytes (read)',
    'highOIOBytesWrite': 'High outstanding IO bytes (write)',
    'highOIOCount': 'High outstanding IO count',
    'highOIOCountPercent': 'High outstanding IO count percent',
    'highOIOCountPercentRead': 'High outstanding IO count percent (read)',
    'highOIOCountPercentWrite': 'High outstanding IO count percent (write)',
    'highOIOCountRead': 'High outstanding IO count (read)',
    'highOIOCountWrite': 'High outstanding IO count (write)',
    'highOIODurationMs': 'High outstanding IO duration ms',
    'highOIODurationMsRead': 'High outstanding IO duration ms (read)',
    'highOIODurationMsWrite': 'High outstanding IO duration ms (write)',
    'highOIODurationPercent': 'High outstanding IO duration percent',
    'highOIODurationPercentRead': 'High outstanding IO duration percent (read)',
    'highOIODurationPercentWrite': 'High outstanding IO duration percent (write)',
    'highOIONumTimes': 'High outstanding IO num times',
    'highOIONumTimesRead': 'High outstanding IO num times (read)',
    'highOIONumTimesWrite': 'High outstanding IO num times (write)',
    'highOIOThroughput': 'High outstanding IO throughput',
    'highOIOThroughputRead': 'High outstanding IO throughput (read)',
    'highOIOThroughputWrite': 'High outstanding IO throughput (write)',
    'ioChainDrops': 'IO chain drops',
    'ioChainDropsActual': 'IO chain drops (actual)',
    'ioChainRxdrops': 'IO chain RX drops',
    'ioChainRxdropsActual': 'IO chain RX drops (actual)',
    'ioChainTxdrops': 'IO chain TX drops',
    'ioChainTxdropsActual': 'IO chain TX drops (actual)',
    'ioCount': 'IO count',
    'ioCountDevRead': 'IO count dev (read)',
    'ioCountDevUnmap': 'IO count dev unmap',
    'ioCountDevWrite': 'IO count dev (write)',
    'iops': 'IOPS',
    'iopsCacheMissRate': 'Cache Miss Per IOPS',
    'iopsDevRead': 'Physical-layer Read IOPS',
    'iopsDevUnmap': 'IOPS dev unmap',
    'iopsDevWrite': 'Physical-layer Write IOPS',
    'iopsGwe': 'GWE IOPS',
    'iopsLimit': 'Normalized IOPS Limit',
    'iopsRead': 'Read IOPS',
    'iopsReadCapacity': 'vSAN Layer Read IOPS of vSAN ESA Disk',
    'iopsReadPerf': 'IOPS read perf',
    'iopsRecUnmap': 'Recovery Unmap IOPS',
    'iopsRecWrite': 'Recovery Write IOPS',
    'iopsResyncRead': 'Resync Read IOPS',
    'iopsRmw': 'RMW IOPS',
    'iopsSegCleanerUnmap': 'IOPS seg cleaner unmap',
    'iopsUnmap': 'Unmap IOPS',
    'iopsUnmapCapacity': 'IOPS unmap capacity',
    'iopsUnmapPerf': 'IOPS unmap perf',
    'iopsWrite': 'Write IOPS',
    'iopsWriteCapacity': 'vSAN Layer Write IOPS of vSAN ESA Disk',
    'iopsWriteConflicts': 'Write Conficts IOPS',
    'iopsWritePerf': 'IOPS write perf',
    'ip6Errs': 'IPv6 Errors',
    'ip6Total': 'IP6 (total)',
    'ipErrs': 'IPv4 Errors',
    'ipTotal': 'IP (total)',
    'kaReset': 'Keepalive reset',
    'kernelConsumedSize': 'Kernel consumed size',
    'kernelReservedSize': 'Kernel Reserved Memory Size',
    'latAvgCacheGet': 'Latency avg cache get',
    'latAvgResyncRead': 'Resync Read Latency',
    'latAvgTotalOpIO': 'Latency avg total op IO',
    'latAvgTxnBank': 'Latency avg transaction bank',
    'latAvgTxnBankTotalIO': 'Latency avg transaction bank total IO',
    'latAvgTxnUnmap': 'Latency avg transaction unmap',
    'latAvgTxnUnmapTotalIO': 'Latency avg transaction unmap total IO',
    'latencyAvg': 'Latency (average)',
    'latencyAvgRead': 'Read Latency',
    'latencyAvgRecUnmap': 'Recovery Unmap Latency',
    'latencyAvgRecWrite': 'Recovery Write Latency',
    'latencyAvgResyncRead': 'Resync Read Latency',
    'latencyAvgSegCleanerUnmap': 'Latency avg seg cleaner unmap',
    'latencyAvgServiceVMRead': 'Latency avg service VM (read)',
    'latencyAvgServiceVMWrite': 'Latency avg service VM (write)',
    'latencyAvgUnmap': 'Unmap Latency',
    'latencyAvgWrite': 'Write Latency',
    'latencyCacheLookup': 'Cache Lookup Latency',
    'latencyDevDAvg': 'Device Average Latency',
    'latencyDevGAvg': 'Guest Average Latency',
    'latencyDevKAvg': 'Latency dev k (average)',
    'latencyDevRead': 'Physical-layer Read Latency',
    'latencyDevUnmap': 'Latency dev unmap',
    'latencyDevWrite': 'Physical-layer Write Latency',
    'latencyGwe': 'GWE Latency',
    'latencyMaxRead': 'Latency (max, read)',
    'latencyMaxSegCleanerUnmap': 'Latency max seg cleaner unmap',
    'latencyMaxUnmap': 'Latency max unmap',
    'latencyMaxWrite': 'Latency (max, write)',
    'latencyRead': 'vSAN Layer Read Latency',
    'latencyStddev': 'Latency Std Dev',
    'latencyStddevRead': 'Latency standard deviation (read)',
    'latencyStddevRecoveryWrite': 'Latency standard deviation recovery (write)',
    'latencyStddevResyncRead': 'Latency standard deviation resync (read)',
    'latencyStddevSegCleanerUnmap': 'Latency standard deviation seg cleaner unmap',
    'latencyStddevUnmap': 'Unmap Latency Std Dev',
    'latencyStddevWrite': 'Latency standard deviation (write)',
    'latencyWrite': 'vSAN Layer Write Latency',
    'leafGTEs': 'Leaf gt es',
    'lessSkewedMultiBurstsPerSecond': 'Less skewed multi bursts per second',
    'lruLockContentions': 'Lru lock contentions',
    'maxDiscUsedPct': 'Disc used percent (max)',
    'maxLatency': 'RDT Network Cluster Max Latency',
    'maxReadTimeCapacity': 'Read time capacity (max)',
    'maxReadTimePerf': 'Read time perf (max)',
    'maxRunPct': 'Run percent (max)',
    'maxUnmapTimeCapacity': 'Unmap time capacity (max)',
    'maxUnmapTimePerf': 'Unmap time perf (max)',
    'maxUsedPct': 'Used percent (max)',
    'maxWriteTimeCapacity': 'Write time capacity (max)',
    'maxWriteTimePerf': 'Write time perf (max)',
    'metadataDispatchedCostRead': 'Metadata dispatched cost (read)',
    'metadataDispatchedCostWrite': 'Metadata dispatched cost (write)',
    'metadataQueueDepthRead': 'Metadata queue depth (read)',
    'metadataQueueDepthWrite': 'Metadata queue depth (write)',
    'minLatency': 'RDT Network Cluster Min Latency',
    'minReadTimeCapacity': 'Read time capacity (min)',
    'minReadTimePerf': 'Read time perf (min)',
    'minUnmapTimeCapacity': 'Unmap time capacity (min)',
    'minUnmapTimePerf': 'Unmap time perf (min)',
    'minWriteTimeCapacity': 'Write time capacity (min)',
    'minWriteTimePerf': 'Write time perf (min)',
    'missesPerIO': 'Misses per IO',
    'namespaceDispatchedCostRead': 'Namespace dispatched cost (read)',
    'namespaceDispatchedCostWrite': 'Namespace dispatched cost (write)',
    'namespaceQueueDepthRead': 'Namespace queue depth (read)',
    'namespaceQueueDepthWrite': 'Namespace queue depth (write)',
    'netSchedAvgCompRecoveryWriteDelayMs': 'Net sched avg comp recovery write delay ms',
    'netSchedAvgCompResyncReadDelayMs': 'Net sched avg comp resync read delay ms',
    'netSchedAvgOwnerRecoveryWriteDelayMs': 'Net sched avg owner recovery write delay ms',
    'netSchedAvgOwnerResyncReadDelayMs': 'Net sched avg owner resync read delay ms',
    'netSchedBWDiscoveredPerDiscoverySession': 'Net sched bw discovered per discovery session',
    'netSchedBWDiscoveryActions': 'Net sched bw discovery actions',
    'netSchedBWDiscoveryAvgIntervalsUs': 'Net sched bw discovery avg intervals us',
    'netSchedBWDiscoverySessions': 'Net sched bw discovery sessions',
    'netSchedBWDiscoveryStopsDueToGainsFromGuestPct': 'Net sched bw discovery stops due to gains from guest percent',
    'netSchedBWDiscoveryStopsDueToHighLatencyPct': 'Net sched bw discovery stops due to high latency percent',
    'netSchedBWDiscoveryStopsDueToLowUtilizationPct': 'Net sched bw discovery stops due to low utilization percent',
    'netSchedBWDiscoveryUtilizationPct': 'Net sched bw discovery utilization percent',
    'netSchedBWReallocatedPerReallocationSession': 'Net sched bw reallocated per reallocation session',
    'netSchedBWReallocationActions': 'Net sched bw reallocation actions',
    'netSchedBWReallocationAvgIntervalsUs': 'Net sched bw reallocation avg intervals us',
    'netSchedBWReallocationSessions': 'Net sched bw reallocation sessions',
    'netSchedBWReallocationStopsDueToHighSharePct': 'Net sched bw reallocation stops due to high share percent',
    'netSchedBWReallocationStopsDueToLowUtilizationPct': 'Net sched bw reallocation stops due to low utilization percent',
    'netSchedBWReallocationUtilizationRatio': 'Net sched bw reallocation utilization ratio',
    'netSchedBWReallocationUtilizationRatioAbove': 'Net sched bw reallocation utilization ratio above',
    'netSchedBWReallocationUtilizationRatioBelow': 'Net sched bw reallocation utilization ratio below',
    'netSchedBandwidthDiscoveryBps': 'Net sched bandwidth discovery bps',
    'netSchedGuestIopsDecreasePerDiscoverySession': 'Net sched guest IOPS decrease per discovery session',
    'netSchedGuestIopsIncreasePerReallocationSession': 'Net sched guest IOPS increase per reallocation session',
    'netSchedLatencyIncreaseFromResyncPerDiscoverySessionPct': 'Net sched latency increase from resync per discovery session percent',
    'netSchedResyncGainsFromGuestCount': 'Net sched resync gains from guest count',
    'netSchedResyncIopsDecreasePerReallocationSession': 'Net sched resync IOPS decrease per reallocation session',
    'netSchedResyncIopsIncreasePerDiscoverySession': 'Net sched resync IOPS increase per discovery session',
    'netSchedUnderUtilCount': 'Net sched under utilization count',
    'netSchedUnderUtilGuestBps': 'Net sched under utilization guest bps',
    'netSchedUnderUtilTtlBps': 'Net sched under utilization ttl bps',
    'numBlockedDeltaToBaseResyncJobs': 'Num blocked delta to base resync jobs',
    'numBlockedFullResyncJobs': 'Num blocked full resync jobs',
    'numBlockedPriorityResyncJobs': 'Num blocked priority resync jobs',
    'numBlockedResyncJobs': 'Num blocked resync jobs',
    'numBlockedSharedResyncJobs': 'Num blocked shared resync jobs',
    'numBlockedSiblingToDeltaResyncJobs': 'Num blocked sibling to delta resync jobs',
    'numBurstStatsSkipped': 'Num burst stats skipped',
    'numCompleteDeltaToBaseResyncOps': 'Num complete delta to base resync ops',
    'numCompleteFullResyncOps': 'Num complete full resync ops',
    'numCompleteResyncOps': 'Num complete resync ops',
    'numCompleteResyncRwrBatches': 'Num complete resync rwr batches',
    'numCompleteRwrOps': 'Num complete rwr ops',
    'numCompleteSiblingToDeltaResyncOps': 'Num complete sibling to delta resync ops',
    'numInflightDedupResyncJobs': 'Num inflight dedup resync jobs',
    'numInflightPriorityResyncJobs': 'Num inflight priority resync jobs',
    'numInflightSharedResyncJobs': 'Num inflight shared resync jobs',
    'numNetSchedCompIops': 'Num net sched comp IOPS',
    'numNetSchedCompIopsLimit': 'Num net sched comp IOPS limit',
    'numNetSchedCompRecoveryWriteIops': 'Num net sched comp recovery write IOPS',
    'numNetSchedCompRecoveryWriteIopsLimit': 'Num net sched comp recovery write IOPS limit',
    'numNetSchedCompRecoveryWriteTpThrottled': 'Num net sched comp recovery write tp throttled',
    'numNetSchedCompResyncReadIops': 'Num net sched comp resync read IOPS',
    'numNetSchedCompResyncReadIopsLimit': 'Num net sched comp resync read IOPS limit',
    'numNetSchedCompResyncReadTpThrottled': 'Num net sched comp resync read tp throttled',
    'numNetSchedCompTpThrottled': 'Num net sched comp tp throttled',
    'numNetSchedControllerActivations': 'Num net sched controller activations',
    'numNetSchedControllerIopsLimit': 'Num net sched controller IOPS limit',
    'numNetSchedGuestLTLatUs': 'Num net sched guest lt latency us',
    'numNetSchedHighBand': 'Num net sched high band',
    'numNetSchedHighBandHighShare': 'Num net sched high band high share',
    'numNetSchedHighBandLowLimit': 'Num net sched high band low limit',
    'numNetSchedHighBandSec': 'Num net sched high band sec',
    'numNetSchedHighToLowBand': 'Num net sched high to low band',
    'numNetSchedHighToMidBand': 'Num net sched high to mid band',
    'numNetSchedLowBand': 'Num net sched low band',
    'numNetSchedLowBandHighLimit': 'Num net sched low band high limit',
    'numNetSchedLowBandSec': 'Num net sched low band sec',
    'numNetSchedLowBandThreshUs': 'Num net sched low band thresh us',
    'numNetSchedLowToHighBand': 'Num net sched low to high band',
    'numNetSchedLowToMidBand': 'Num net sched low to mid band',
    'numNetSchedMidBand': 'Num net sched mid band',
    'numNetSchedMidBandHighLimit': 'Num net sched mid band high limit',
    'numNetSchedMidBandLowShare': 'Num net sched mid band low share',
    'numNetSchedMidBandSec': 'Num net sched mid band sec',
    'numNetSchedMidToHighBand': 'Num net sched mid to high band',
    'numNetSchedMidToLowBand': 'Num net sched mid to low band',
    'numNetSchedOwnerIops': 'Num net sched owner IOPS',
    'numNetSchedOwnerIopsLimit': 'Num net sched owner IOPS limit',
    'numNetSchedOwnerRecoveryWriteIops': 'Num net sched owner recovery write IOPS',
    'numNetSchedOwnerRecoveryWriteIopsLimit': 'Num net sched owner recovery write IOPS limit',
    'numNetSchedOwnerRecoveryWriteTpThrottled': 'Num net sched owner recovery write tp throttled',
    'numNetSchedOwnerResyncReadIops': 'Num net sched owner resync read IOPS',
    'numNetSchedOwnerResyncReadIopsLimit': 'Num net sched owner resync read IOPS limit',
    'numNetSchedOwnerResyncReadTpThrottled': 'Num net sched owner resync read tp throttled',
    'numNetSchedOwnerTpThrottled': 'Num net sched owner tp throttled',
    'numNetSchedRecoveryWriteTpThrottled': 'Num net sched recovery write tp throttled',
    'numNetSchedResyncReadTpThrottled': 'Num net sched resync read tp throttled',
    'numNetSchedResyncTotalSharePercent': 'Num net sched resync total share percent',
    'numNetSchedRollingAvgLatUs': 'Num net sched rolling avg latency us',
    'numNetSchedSeenNonResyncTpBps': 'Num net sched seen non resync tp bps',
    'numNetSchedSeenResyncTpBps': 'Num net sched seen resync tp bps',
    'numNetSchedSeenTotalTpBps': 'Num net sched seen total tp bps',
    'numOio': 'Num outstanding IO',
    'numPendingDecomResyncJobs': 'Num pending decom resync jobs',
    'numPendingDedupResyncJobs': 'Num pending dedup resync jobs',
    'numPendingDeltaToBaseResyncJobs': 'Num pending delta to base resync jobs',
    'numPendingFullResyncJobs': 'Num pending full resync jobs',
    'numPendingResyncJobs': 'Num pending resync jobs',
    'numPendingSiblingToDeltaResyncJobs': 'Num pending sibling to delta resync jobs',
    'numReadyDelay': 'Num ready delay',
    'numRunningDeltaToBaseResyncJobs': 'Num running delta to base resync jobs',
    'numRunningFullResyncJobs': 'Num running full resync jobs',
    'numRunningResyncJobs': 'Num running resync jobs',
    'numRunningSiblingToDeltaResyncJobs': 'Num running sibling to delta resync jobs',
    'numSuspendedDedupResyncJobs': 'Num suspended dedup resync jobs',
    'numSuspendedDeltaToBaseResyncJobs': 'Num suspended delta to base resync jobs',
    'numSuspendedFullResyncJobs': 'Num suspended full resync jobs',
    'numSuspendedPriorityResyncJobs': 'Num suspended priority resync jobs',
    'numSuspendedResyncChangemaps': 'Num suspended resync changemaps',
    'numSuspendedResyncJobs': 'Num suspended resync jobs',
    'numSuspendedSharedResyncJobs': 'Num suspended shared resync jobs',
    'numSuspendedSiblingToDeltaResyncJobs': 'Num suspended sibling to delta resync jobs',
    'oio': 'Outstanding IO',
    'oioRead': 'Outstanding IO (read)',
    'oioRecoveryWrite': 'Outstanding IO recovery (write)',
    'oioResyncRead': 'Outstanding IO resync (read)',
    'oioWrite': 'Outstanding IO (write)',
    'osfsdConsumedSize': 'Osfsd consumed size',
    'osfsdMemAllocMax': 'Osfsd mem alloc (max)',
    'osfsdMemAllocMin': 'Osfsd mem alloc (min)',
    'osfsdReservedSize': 'Osfsd reserved size',
    'outstandingCmdCount': 'Outstanding cmd count',
    'overcommitRatio': 'Over Commit Ratio',
    'owner2PCCommitLatencyAvgUs': 'Owner2 pc commit latency avg us',
    'ownerECCacheHitMissRatio': 'Owner ec cache hit miss ratio',
    'ownerECCacheNumCachedObjects': 'Owner ec cache num cached objects',
    'ownerECCacheNumFailedAllocs': 'Owner ec cache num failed allocs',
    'ownerECCacheNumSuccessAllocs': 'Owner ec cache num success allocs',
    'pauseCount': 'pNic 802.3x Pause Rate',
    'pauseCountActual': 'Pause count (actual)',
    'pauseCountRaw': 'Pause count raw',
    'pcpuUsedPct': 'Percentage of Used Physical CPU Time',
    'pcpuUtilPct': 'Percentage of Physical CPU Utilization',
    'pctMemUsed': 'Used Memory Percentage',
    'pfcCount': 'PFC count',
    'pfcCountActual': 'PFC count (actual)',
    'pfcCountRaw': 'PFC count raw',
    'portRxDrops': 'Inbound Packet Drop Rate of vSwitch Port',
    'portRxDropsActual': 'Port RX drops (actual)',
    'portRxpkts': 'Port RX packets',
    'portTxDrops': 'Outbound Packet Drop Rate of vSwitch Port',
    'portTxDropsActual': 'Port TX drops (actual)',
    'portTxpkts': 'Port TX packets',
    'prefetchCacheMaxGetLatUs': 'Prefetch cache max get latency us',
    'rateBankFlushTotalCacheRef': 'Bank flush total cache ref (rate)',
    'rateClientOpsBadParam': 'Client ops bad param (rate)',
    'rateClientOpsChecksumMismatch': 'Client ops checksum mismatch (rate)',
    'rateClientOpsIoError': 'Client ops IO error (rate)',
    'rateClientOpsLimitExceed': 'Client ops limit exceed (rate)',
    'rateClientOpsNoConnect': 'Client ops no connect (rate)',
    'rateClientOpsNoMem': 'Client ops no mem (rate)',
    'rateClientOpsNoSpace': 'Client ops no space (rate)',
    'rateClientOpsNotSupported': 'Client ops not supported (rate)',
    'rateClientOpsRetry': 'Client ops retry (rate)',
    'rateCompmgrOpsBadParam': 'Compmgr ops bad param (rate)',
    'rateCompmgrOpsChecksumMismatch': 'Compmgr ops checksum mismatch (rate)',
    'rateCompmgrOpsIoError': 'Compmgr ops IO error (rate)',
    'rateCompmgrOpsLimitExceed': 'Compmgr ops limit exceed (rate)',
    'rateCompmgrOpsNoConnect': 'Compmgr ops no connect (rate)',
    'rateCompmgrOpsNoMem': 'Compmgr ops no mem (rate)',
    'rateCompmgrOpsNoSpace': 'Compmgr ops no space (rate)',
    'rateCompmgrOpsNotSupported': 'Compmgr ops not supported (rate)',
    'rateCompmgrOpsRetry': 'Compmgr ops retry (rate)',
    'rateOtherClientOpsFailure': 'Other client ops failure (rate)',
    'rateOtherCompmgrOpsFailure': 'Other compmgr ops failure (rate)',
    'rateOtherOwnerOpsFailure': 'Other owner ops failure (rate)',
    'rateOwnerOpsBadParam': 'Owner ops bad param (rate)',
    'rateOwnerOpsChecksumMismatch': 'Owner ops checksum mismatch (rate)',
    'rateOwnerOpsIoError': 'Owner ops IO error (rate)',
    'rateOwnerOpsLimitExceed': 'Owner ops limit exceed (rate)',
    'rateOwnerOpsNoConnect': 'Owner ops no connect (rate)',
    'rateOwnerOpsNoMem': 'Owner ops no mem (rate)',
    'rateOwnerOpsNoSpace': 'Owner ops no space (rate)',
    'rateOwnerOpsNotSupported': 'Owner ops not supported (rate)',
    'rateOwnerOpsRetry': 'Owner ops retry (rate)',
    'rateSegCleaningCtxDataTotalCacheRef': 'Seg cleaning context data total cache ref (rate)',
    'rateTotDirtyCachePage': 'Tot dirty cache page (rate)',
    'rateTotalBitmapCacheMiss': 'Bitmap cache miss (rate, total)',
    'rateTotalCacheMiss': 'Cache miss (rate, total)',
    'rateTotalCacheRef': 'Cache ref (rate, total)',
    'rateTotalLogicalTreeCacheMiss': 'Logical tree cache miss (rate, total)',
    'rateTotalMiddleTreeCacheMiss': 'Middle tree cache miss (rate, total)',
    'rateTotalSnapTreeCacheMiss': 'Snap tree cache miss (rate, total)',
    'rateTotalSutCacheMiss': 'Sut cache miss (rate, total)',
    'rateTxnBankLogicalTreeCacheMiss': 'Transaction bank logical tree cache miss (rate)',
    'rateTxnBankLogicalTreeCacheRef': 'Transaction bank logical tree cache ref (rate)',
    'rateTxnBankMiddleTreeCacheMiss': 'Transaction bank middle tree cache miss (rate)',
    'rateTxnBankMiddleTreeCacheRef': 'Transaction bank middle tree cache ref (rate)',
    'rateTxnBankSutCacheMiss': 'Transaction bank sut cache miss (rate)',
    'rateTxnBankSutCacheRef': 'Transaction bank sut cache ref (rate)',
    'rateTxnBankTotalCacheMiss': 'Transaction bank total cache miss (rate)',
    'rateTxnBankTotalCacheRef': 'Transaction bank total cache ref (rate)',
    'rateTxnLookupCacheMiss': 'Transaction lookup cache miss (rate)',
    'rateTxnLookupCacheRef': 'Transaction lookup cache ref (rate)',
    'rateTxnLookupLogicalTreeCacheMiss': 'Transaction lookup logical tree cache miss (rate)',
    'rateTxnLookupLogicalTreeCacheRef': 'Transaction lookup logical tree cache ref (rate)',
    'rateTxnLookupMiddleTreeCacheMiss': 'Transaction lookup middle tree cache miss (rate)',
    'rateTxnLookupMiddleTreeCacheRef': 'Transaction lookup middle tree cache ref (rate)',
    'rateTxnPrefetchLogicalTreeCacheMiss': 'Transaction prefetch logical tree cache miss (rate)',
    'rateTxnPrefetchLogicalTreeCacheRef': 'Transaction prefetch logical tree cache ref (rate)',
    'rateTxnPrefetchMiddleTreeCacheMiss': 'Transaction prefetch middle tree cache miss (rate)',
    'rateTxnPrefetchMiddleTreeCacheRef': 'Transaction prefetch middle tree cache ref (rate)',
    'rateTxnPrefetchSutCacheMiss': 'Transaction prefetch sut cache miss (rate)',
    'rateTxnPrefetchSutCacheRef': 'Transaction prefetch sut cache ref (rate)',
    'rateTxnPrefetchTotalCacheMiss': 'Transaction prefetch total cache miss (rate)',
    'rateTxnPrefetchTotalCacheRef': 'Transaction prefetch total cache ref (rate)',
    'rateTxnReadWrite': 'Transaction (read, write, rate)',
    'rateTxnSegCleaningCtxDataLogicalTreeCacheMiss': 'Transaction seg cleaning context data logical tree cache miss (rate)',
    'rateTxnSegCleaningCtxDataLogicalTreeCacheRef': 'Transaction seg cleaning context data logical tree cache ref (rate)',
    'rateTxnSegCleaningCtxDataMiddleTreeCacheMiss': 'Transaction seg cleaning context data middle tree cache miss (rate)',
    'rateTxnSegCleaningCtxDataMiddleTreeCacheRef': 'Transaction seg cleaning context data middle tree cache ref (rate)',
    'rateTxnSegCleaningCtxDataSutCacheMiss': 'Transaction seg cleaning context data sut cache miss (rate)',
    'rateTxnSegCleaningCtxDataSutCacheRef': 'Transaction seg cleaning context data sut cache ref (rate)',
    'rateTxnSegCleaningCtxDataTotalCacheMiss': 'Transaction seg cleaning context data total cache miss (rate)',
    'rateTxnSegCleaningCtxDataTotalCacheRef': 'Transaction seg cleaning context data total cache ref (rate)',
    'rateTxnUnmapLogicalTreeCacheMiss': 'Transaction unmap logical tree cache miss (rate)',
    'rateTxnUnmapMiddleTreeCacheMiss': 'Transaction unmap middle tree cache miss (rate)',
    'rateTxnUnmapSutCacheMiss': 'Transaction unmap sut cache miss (rate)',
    'rateTxnUnmapTotalCacheMiss': 'Transaction unmap total cache miss (rate)',
    'rdtRx': 'Read Inbound',
    'rdtRxThroughput': 'Read Inbound Throughput',
    'rdtTx': 'Read Outbound',
    'rdtTxThroughput': 'Read Outbound Throughput',
    'readCongestion': 'Read Congestions',
    'readCount': 'Read count',
    'readCountCapacity': 'Read count capacity',
    'readCountPerf': 'Read count perf',
    'readECLeafOwnerMaxLatencyAvgUs': 'Read ec leaf owner max latency avg us',
    'readECLeafOwnerMaxLatencyUs': 'Read ec leaf owner max latency us',
    'readLatencyMaxUs': 'Read latency max us',
    'readLeafOwnerIops': 'Read leaf owner IOPS',
    'readLeafOwnerLatency': 'Read leaf owner latency',
    'readLeafOwnerLatencyLocal': 'Read leaf owner latency local',
    'readLeafOwnerLatencyRemote': 'Read leaf owner latency remote',
    'readLeafOwnerMaxLatencyAvgUs': 'Read leaf owner max latency avg us',
    'readLeafOwnerRetriesPerOp': 'Read leaf owner retries per op',
    'readLeafOwnerThroughput': 'Read leaf owner throughput',
    'readOwnerRetriesPerOp': 'Read owner retries per op',
    'readsToLayer': 'Reads to layer',
    'readyPct': 'Percentage of Ready CPU Time',
    'recUnmapCongestion': 'Recovery unmap congestion',
    'recUnmapCount': 'Recovery unmap count',
    'recWriteCongestion': 'Recovery write congestion',
    'recWriteCount': 'Recovery write count',
    'recoveryUnmapCongestion': 'Recovery unmap congestion',
    'recoveryUnmapLeafOwnerLatency': 'Recovery unmap leaf owner latency',
    'recoveryWriteCongestion': 'Resync Read Congestions',
    'recoveryWriteLeafOwnerLatency': 'Recovery write leaf owner latency',
    'recoveryWriteLeafOwnerLatencyLocal': 'Recovery write leaf owner latency local',
    'recoveryWriteLeafOwnerLatencyRemote': 'Recovery write leaf owner latency remote',
    'regulatorIopsRead': 'Regulator IOPS (read)',
    'regulatorIopsWrite': 'Regulator IOPS (write)',
    'resyncDispatchedCostRead': 'Resync dispatched cost (read)',
    'resyncDispatchedCostWrite': 'Resync dispatched cost (write)',
    'resyncQueueDepthRead': 'Resync queue depth (read)',
    'resyncQueueDepthWrite': 'Resync queue depth (write)',
    'resyncReadCongestion': 'Resync read congestion',
    'resyncReadCount': 'Resync read count',
    'resyncReadLeafOwnerLatency': 'Resync read leaf owner latency',
    'resyncReadLeafOwnerLatencyLocal': 'Resync read leaf owner latency local',
    'resyncReadLeafOwnerLatencyRemote': 'Resync read leaf owner latency remote',
    'resyncsEndedAsDeltaToBase': 'Resyncs ended as delta to base',
    'resyncsStartedAsDeltaToBase': 'Resyncs started as delta to base',
    'runPct': 'Percentage of Running CPU Time',
    'rxCrcErr': 'pNIC RX CRC Error',
    'rxCrcErrActual': 'RX CRC errors (actual)',
    'rxCrcErrRaw': 'RX CRC errors raw',
    'rxDrp': 'RX dropped',
    'rxDrpActual': 'RX dropped (actual)',
    'rxErr': 'pNIC RX Generic Error',
    'rxErrActual': 'RX errors (actual)',
    'rxErrRaw': 'RX errors raw',
    'rxFifoErr': 'pNIC RX FIFO Error',
    'rxFifoErrActual': 'RX FIFO errors (actual)',
    'rxFifoErrRaw': 'RX FIFO errors raw',
    'rxFrmErr': 'RX frame alignment errors',
    'rxFrmErrActual': 'RX frame alignment errors (actual)',
    'rxLgtErr': 'RX length errors',
    'rxLgtErrActual': 'RX length errors (actual)',
    'rxMissErr': 'pNIC RX missed error (ring buffer full)',
    'rxMissErrActual': 'pNIC RX missed error (ring buffer full) (actual)',
    'rxMissErrRaw': 'pNIC RX missed error (ring buffer full) (raw)',
    'rxOvErr': 'pNIC RX Buffer Overflow Error',
    'rxOvErrActual': 'RX overrun errors (actual)',
    'rxOvErrRaw': 'RX overrun errors raw',
    'rxPackets': 'Inbound Packets Per Second',
    'rxPacketsLossRate': 'Inbound Packet Discard Rate',
    'rxPacketsLossRateActual': 'RX packets loss (rate, actual)',
    'rxPktRaw': 'RX packet raw',
    'rxSbSpaceAvg': 'RDT Network Socket Average Inbound Bytes',
    'rxSbSpaceMax': 'RDT Network Socket Max Inbound Bytes',
    'rxSbSpaceMin': 'RDT Network Socket Min Inbound Bytes',
    'rxThroughput': 'Throughput Inbound',
    'savedByDedup': 'Saved Capacity',
    'segCleanerUnmapCongestion': 'Seg cleaner unmap congestion',
    'segCleanerUnmapLeafOwnerLatency': 'Seg cleaner unmap leaf owner latency',
    'segCleanerUnmapLeafOwnerMaxLatencyAvgUs': 'Seg cleaner unmap leaf owner max latency avg us',
    'serverSwitchAvglatency': 'Server switch average latency',
    'serverSwitchCount': 'Server switch count',
    'serverSwitchLatencyMaxUs': 'Server switch latency max us',
    'serverSwitchlatencyStddev': 'Server switchlatency standard deviation',
    'sharedCongestion': 'Shared congestion',
    'tcpBadrst': 'TCP badrst',
    'tcpBadsyn': 'TCP badsyn',
    'tcpConndrops': 'TCP conndrops',
    'tcpConnects': 'TCP connects',
    'tcpDrops': 'TCP drops',
    'tcpEcnCe': 'TCP ECN ce',
    'tcpErrs': 'TCP Errors',
    'tcpErrsActual': 'TCP errors (actual)',
    'tcpHalfopenDropRate': 'Half Open Drop Rate',
    'tcpHalfopenDropRateActual': 'TCP halfopen drop (rate, actual)',
    'tcpKeepdrops': 'TCP keepdrops',
    'tcpKeeptimeo': 'TCP keeptimeo',
    'tcpPersisttimeo': 'TCP persisttimeo',
    'tcpRcvackpack': 'TCP received ackpack',
    'tcpRcvbadoff': 'TCP received badoff',
    'tcpRcvbadsum': 'TCP received badsum',
    'tcpRcvdupack': 'TCP received duplicate ACKs',
    'tcpRcvdupackRate': 'Received Duplicate Acknowledge Rate',
    'tcpRcvdupackRateActual': 'TCP received duplicate ACKs (rate, actual)',
    'tcpRcvduppack': 'TCP received duplicate packets',
    'tcpRcvduppackRate': 'Received Duplicate Packets Rate',
    'tcpRcvduppackRateActual': 'TCP received duplicate packets (rate, actual)',
    'tcpRcvmemdrop': 'TCP received memdrop',
    'tcpRcvoopack': 'TCP received out-of-order packets',
    'tcpRcvoopackRate': 'Received Out-of-order Packets Rate',
    'tcpRcvoopackRateActual': 'TCP received out-of-order packets (rate, actual)',
    'tcpRcvshort': 'TCP received short',
    'tcpRexmttimeo': 'TCP rexmttimeo',
    'tcpRxErrRate': 'TCP RX errors (rate)',
    'tcpRxPackets': 'TCP Inbound Packets',
    'tcpRxThroughput': 'TCP Inbound Throughout',
    'tcpSackRcvBlocks': 'TCP SACK received blocks',
    'tcpSackRcvBlocksRate': 'Sack Received Blocks Rate',
    'tcpSackRcvBlocksRateActual': 'TCP SACK received blocks (rate, actual)',
    'tcpSackRexmits': 'TCP SACK retransmits',
    'tcpSackRexmitsRate': 'Sack Rexmits Rate',
    'tcpSackRexmitsRateActual': 'TCP SACK retransmits (rate, actual)',
    'tcpSackSendBlocks': 'TCP SACK send blocks',
    'tcpSackSendBlocksRate': 'Sack Send Blocks Rate',
    'tcpSackSendBlocksRateActual': 'TCP SACK send blocks (rate, actual)',
    'tcpSndZeroWin': 'TCP Send Zero Window',
    'tcpSndZeroWinActual': 'TCP sent zero window (actual)',
    'tcpSndacks': 'TCP sent ACKS',
    'tcpTimeoutDropRate': 'Timeout Drop Rate',
    'tcpTimeoutDropRateActual': 'TCP timeout drop (rate, actual)',
    'tcpTimeoutdrop': 'TCP timeoutdrop',
    'tcpTxPackets': 'TCP Outbound Packets',
    'tcpTxRexmitRate': 'TCP TX retransmit (rate)',
    'tcpTxThroughput': 'TCP Outbound Throughout',
    'throughput': 'Throughput',
    'throughputDevRead': 'Physical-layer Read Throughput',
    'throughputDevUnmap': 'Throughput dev unmap',
    'throughputDevWrite': 'Physical-layer Write Throughput',
    'throughputRead': 'Read throughput',
    'throughputRecUnmap': 'Recovery Unmap Throughput',
    'throughputRecWrite': 'Recovery Write Throughput',
    'throughputSegCleanerUnmap': 'Throughput seg cleaner unmap',
    'throughputUnmap': 'Unmap Throughput',
    'throughputWrite': 'Write throughput',
    'total': 'Total Capacity',
    'totalDeltaCreationDomActiveLatency': 'Delta creation DOM active latency (total)',
    'totalDeltaCreationDomCreationLatency': 'Delta creation DOM creation latency (total)',
    'totalDeltasCreatedCount': 'Deltas created count (total)',
    'totalDpOverhead': 'DP overhead (total)',
    'totalMbMemUsed': 'Total Memory Used',
    'totalSnapshotCapacity': 'Used By Snapshots',
    'tputCacheMissRate': 'Cache Miss Per Throughput',
    'tputRead': 'Read Throughput',
    'tputReadCapacity': 'vSAN Layer Read Throughput of vSAN ESA Disk',
    'tputReadDiskCapacity': 'Throughput read disk capacity',
    'tputReadDiskPerf': 'Throughput read disk perf',
    'tputReadPerf': 'Throughput read perf',
    'tputRecUnmap': 'Throughput recovery unmap',
    'tputRecWrite': 'Recovery Write Throughput',
    'tputResyncRead': 'Resync Read Throughput',
    'tputServiceVMRead': 'Throughput service VM (read)',
    'tputServiceVMWrite': 'Throughput service VM (write)',
    'tputUnmap': 'Throughput unmap',
    'tputUnmapCapacity': 'Throughput unmap capacity',
    'tputUnmapPerf': 'Throughput unmap perf',
    'tputWrite': 'Write Throughput',
    'tputWriteCapacity': 'vSAN Layer Write Throughput of vSAN ESA Disk',
    'tputWritePerf': 'Throughput write perf',
    'twoPCBatchCommitBlockedByGuestIOPS': 'Two pc batch commit blocked by guest IOPS',
    'twoPCBatchCommitBlockedByOtherIOPS': 'Two pc batch commit blocked by other IOPS',
    'twoPCBatchCommitBlockedByResyncIOPS': 'Two pc batch commit blocked by resync IOPS',
    'twoPCBatchCommitBlockedBySyncIOPS': 'Two pc batch commit blocked by sync IOPS',
    'twoPCBatchCommitGuestIOPS': 'Two pc batch commit guest IOPS',
    'twoPCBatchCommitOtherIOPS': 'Two pc batch commit other IOPS',
    'twoPCBatchCommitResyncIOPS': 'Two pc batch commit resync IOPS',
    'twoPCBatchCommitSyncIOPS': 'Two pc batch commit sync IOPS',
    'twoPCCommitCount': 'Two pc commit count',
    'twoPCCommitSize': 'Two pc commit size',
    'twoPCPrepareLimitRetryGuestAvgTimeMs': 'Two pc prepare limit retry guest avg time ms',
    'twoPCPrepareLimitRetryGuestIOPS': 'Two pc prepare limit retry guest IOPS',
    'twoPCPrepareLimitRetryOtherAvgTimeMs': 'Two pc prepare limit retry other avg time ms',
    'twoPCPrepareLimitRetryOtherIOPS': 'Two pc prepare limit retry other IOPS',
    'twoPCPrepareLimitRetryResyncAvgTimeMs': 'Two pc prepare limit retry resync avg time ms',
    'twoPCPrepareLimitRetryResyncIOPS': 'Two pc prepare limit retry resync IOPS',
    'twoPCPrepareRetryCount': 'Two pc prepare retry count',
    'twoPCReservedLSNExhaustedCount': 'Two pc reserved lsn exhausted count',
    'twoPCReservedLSNUnusedCount': 'Two pc reserved lsn unused count',
    'twoPCReservedLSNUsedCount': 'Two pc reserved lsn used count',
    'txAbortErr': 'TX aborted errors',
    'txAbortErrActual': 'TX aborted errors (actual)',
    'txCarErr': 'pNIC TX Carrier Error',
    'txCarErrActual': 'TX carrier errors (actual)',
    'txCarErrRaw': 'TX carrier errors raw',
    'txCtxQAvg': 'RDT Network Average Outbound Context Bytes',
    'txCtxQMax': 'RDT Network Max Outbound Context Bytes',
    'txCtxQMin': 'RDT Network Min Outbound Context Bytes',
    'txDrp': 'TX dropped',
    'txDrpActual': 'TX dropped (actual)',
    'txErr': 'pNIC TX Generic Error',
    'txErrActual': 'TX errors (actual)',
    'txErrRaw': 'TX errors raw',
    'txFifoErr': 'TX FIFO errors',
    'txFifoErrActual': 'TX FIFO errors (actual)',
    'txHeartErr': 'TX heartbeat errors',
    'txHeartErrActual': 'TX heartbeat errors (actual)',
    'txPackets': 'Outbound Packets Per Second',
    'txPacketsLossRate': 'Outbound Packet Discard Rate',
    'txPacketsLossRateActual': 'TX packets loss (rate, actual)',
    'txPktRaw': 'TX packet raw',
    'txQLatAvg': 'RDT Network Average Outbound Queueing Latency',
    'txQLatMax': 'RDT Network Max Outbound Queueing Latency',
    'txQLatMin': 'RDT Network Min Outbound Queueing Latency',
    'txSbSpaceAvg': 'RDT Network Socket Average Outbound Bytes',
    'txSbSpaceMax': 'RDT Network Socket Max Outbound Bytes',
    'txSbSpaceMin': 'RDT Network Socket Min Outbound Bytes',
    'txThroughput': 'Throughput Outbound',
    'txWinErr': 'TX window errors',
    'txWinErrActual': 'TX window errors (actual)',
    'txnBankMaxLatUs': 'Transaction bank max latency us',
    'txnCacheFlushMaxLatUs': 'Transaction cache flush max latency us',
    'txnDLogMaxLatUs': 'Transaction d log max latency us',
    'txnDelExtMiddleTreeMaxLatUs': 'Transaction del ext middle tree max latency us',
    'txnLookupMaxLatUs': 'Transaction lookup max latency us',
    'txnPrefetchMaxLatUs': 'Transaction prefetch max latency us',
    'txnSegCtxDataMaxLatUs': 'Transaction seg context data max latency us',
    'txnSegCtxLLPMaxLatUs': 'Transaction seg context llp max latency us',
    'txnUnmapMaxLatUs': 'Transaction unmap max latency us',
    'txnVatWriteSegMaxLatUs': 'Transaction vat write seg max latency us',
    'unmapCongestion': 'Unmap congestion',
    'unmapCount': 'Unmap count',
    'unmapCountCapacity': 'Unmap count capacity',
    'unmapCountPerf': 'Unmap count perf',
    'unmapECLeafOwnerMaxLatencyAvgUs': 'Unmap ec leaf owner max latency avg us',
    'unmapECLeafOwnerMaxLatencyUs': 'Unmap ec leaf owner max latency us',
    'unmapLatencyMaxUs': 'Unmap latency max us',
    'unmapLeafOwnerLatency': 'Unmap leaf owner latency',
    'unmapLeafOwnerMaxLatencyAvgUs': 'Unmap leaf owner max latency avg us',
    'used': 'Used Capacity',
    'usedPct': 'Percentage of Used CPU Time',
    'uwConsumedSize': 'Uw consumed size',
    'uwMemAllocMax': 'Uw mem alloc (max)',
    'uwMemAllocMin': 'Uw mem alloc (min)',
    'uwReservedSize': 'User world Reserved Memory Size',
    'vitdConsumedSize': 'Vitd consumed size',
    'vitdMemAllocMax': 'Vitd mem alloc (max)',
    'vitdMemAllocMin': 'Vitd mem alloc (min)',
    'vitdReservedSize': 'Vitd reserved size',
    'vmdiskDispatchedCostRead': 'VM disk dispatched cost (read)',
    'vmdiskDispatchedCostWrite': 'VM disk dispatched cost (write)',
    'vmdiskQueueDepthRead': 'VM disk queue depth (read)',
    'vmdiskQueueDepthWrite': 'VM disk queue depth (write)',
    'vsandevicemonitordConsumedSize': 'Vsandevicemonitord consumed size',
    'vsandevicemonitordMemAllocMax': 'Vsandevicemonitord mem alloc (max)',
    'vsandevicemonitordMemAllocMin': 'Vsandevicemonitord mem alloc (min)',
    'vsandevicemonitordReservedSize': 'Vsandevicemonitord reserved size',
    'vsanmgmtdConsumedSize': 'Vsanmgmtd consumed size',
    'vsanmgmtdMemAllocMax': 'Vsanmgmtd mem alloc (max)',
    'vsanmgmtdMemAllocMin': 'Vsanmgmtd mem alloc (min)',
    'vsanmgmtdReservedSize': 'Vsanmgmtd reserved size',
    'vsanmgmtdWatchdogConsumedSize': 'Vsanmgmtd watchdog consumed size',
    'vsanmgmtdWatchdogMemAllocMax': 'Vsanmgmtd watchdog mem alloc (max)',
    'vsanmgmtdWatchdogMemAllocMin': 'Vsanmgmtd watchdog mem alloc (min)',
    'vsanmgmtdWatchdogReservedSize': 'Vsanmgmtd watchdog reserved size',
    'vsanobserverConsumedSize': 'Vsanobserver consumed size',
    'vsanobserverMemAllocMax': 'Vsanobserver mem alloc (max)',
    'vsanobserverMemAllocMin': 'Vsanobserver mem alloc (min)',
    'vsanobserverReservedSize': 'Vsanobserver reserved size',
    'vsantracedConsumedSize': 'Vsantraced consumed size',
    'vsantracedMemAllocMax': 'Vsantraced mem alloc (max)',
    'vsantracedMemAllocMin': 'Vsantraced mem alloc (min)',
    'vsantracedReservedSize': 'Vsantraced reserved size',
    'writeCongestion': 'Write Congestions',
    'writeCount': 'Write count',
    'writeCountCapacity': 'Write count capacity',
    'writeCountPerf': 'Write count perf',
    'writeECLeafOwnerMaxLatencyAvgUs': 'Write ec leaf owner max latency avg us',
    'writeECLeafOwnerMaxLatencyUs': 'Write ec leaf owner max latency us',
    'writeLatencyMaxUs': 'Write latency max us',
    'writeLeafOwnerIops': 'Write leaf owner IOPS',
    'writeLeafOwnerLatency': 'Write leaf owner latency',
    'writeLeafOwnerLatencyLocal': 'Write leaf owner latency local',
    'writeLeafOwnerLatencyRemote': 'Write leaf owner latency remote',
    'writeLeafOwnerMaxLatencyAvgUs': 'Write leaf owner max latency avg us',
    'writeLeafOwnerRetriesPerOp': 'Write leaf owner retries per op',
    'writeLeafOwnerThroughput': 'Write leaf owner throughput',
    'writeOwnerRetriesPerOp': 'Write owner retries per op',
}

# metric -> dotted path under aria.ops.definition.units.Units
UNITS: Dict[str, str] = {
    'IOPSWithinBursts': 'MISC.IO_OPERATIONS_PER_SECOND',
    'IOPSWithinBurstsExclFirstObj': 'MISC.IO_OPERATIONS_PER_SECOND',
    'IOPSWithinBurstsMultiObj': 'MISC.IO_OPERATIONS_PER_SECOND',
    'NIOPS': 'MISC.IO_OPERATIONS_PER_SECOND',
    'NIOPSDelayed': 'MISC.IO_OPERATIONS_PER_SECOND',
    'NIOPSRead': 'MISC.IO_OPERATIONS_PER_SECOND',
    'NIOPSReadDelayed': 'MISC.IO_OPERATIONS_PER_SECOND',
    'NIOPSWrite': 'MISC.IO_OPERATIONS_PER_SECOND',
    'NIOPSWriteDelayed': 'MISC.IO_OPERATIONS_PER_SECOND',
    'allOpCacheMaxGetLatUSec': 'TIME.MICROSECONDS',
    'avgBurstArrivalTime': 'TIME.MICROSECONDS',
    'avgBurstCompletionTime': 'TIME.MICROSECONDS',
    'avgBurstTotalTime': 'TIME.MICROSECONDS',
    'avgDeltaCreationDomActiveLatency': 'TIME.SECONDS',
    'avgDeltaCreationDomCreationLatency': 'TIME.SECONDS',
    'avgLatency': 'TIME.MICROSECONDS',
    'avgRunPct': 'RATIO.PERCENT',
    'avgUsedPct': 'RATIO.PERCENT',
    'cacheUpdateLatency': 'TIME.MICROSECONDS',
    'checkpointWorkerWakeupMs': 'TIME.MICROSECONDS',
    'clientCacheHits': 'MISC.IO_OPERATIONS_PER_SECOND',
    'clomdConsumedSize': 'DATA_SIZE.BYTE',
    'clomdReservedSize': 'DATA_SIZE.BYTE',
    'cmmdsTimeMachineConsumedSize': 'DATA_SIZE.BYTE',
    'cmmdsTimeMachineReservedSize': 'DATA_SIZE.BYTE',
    'cmmdsdConsumedSize': 'DATA_SIZE.BYTE',
    'cmmdsdReservedSize': 'DATA_SIZE.BYTE',
    'coreUtilPct': 'RATIO.PERCENT',
    'epdConsumedSize': 'DATA_SIZE.BYTE',
    'epdReservedSize': 'DATA_SIZE.BYTE',
    'groupRxThroughput': 'DATA_RATE.BIBYTE_PER_SECOND',
    'groupTxMcastThroughput': 'DATA_RATE.BIBYTE_PER_SECOND',
    'groupTxUcastThroughput': 'DATA_RATE.BIBYTE_PER_SECOND',
    'highOIOAvgDurationMs': 'TIME.MILLISECONDS',
    'highOIOAvgDurationMsRead': 'TIME.MILLISECONDS',
    'highOIOAvgDurationMsWrite': 'TIME.MILLISECONDS',
    'highOIOBytes': 'DATA_SIZE.BYTE',
    'highOIOBytesRead': 'DATA_SIZE.BYTE',
    'highOIOBytesWrite': 'DATA_SIZE.BYTE',
    'highOIOCountPercent': 'RATIO.PERCENT',
    'highOIODurationMs': 'TIME.MILLISECONDS',
    'highOIODurationMsRead': 'TIME.MILLISECONDS',
    'highOIODurationMsWrite': 'TIME.MILLISECONDS',
    'highOIODurationPercent': 'RATIO.PERCENT',
    'highOIOThroughput': 'DATA_RATE.BIBYTE_PER_SECOND',
    'highOIOThroughputRead': 'DATA_RATE.BIBYTE_PER_SECOND',
    'highOIOThroughputWrite': 'DATA_RATE.BIBYTE_PER_SECOND',
    'iops': 'MISC.IO_OPERATIONS_PER_SECOND',
    'iopsCacheMissRate': 'MISC.IO_OPERATIONS_PER_SECOND',
    'iopsDevRead': 'MISC.IO_OPERATIONS_PER_SECOND',
    'iopsDevUnmap': 'MISC.IO_OPERATIONS_PER_SECOND',
    'iopsDevWrite': 'MISC.IO_OPERATIONS_PER_SECOND',
    'iopsGwe': 'MISC.IO_OPERATIONS_PER_SECOND',
    'iopsLimit': 'MISC.IO_OPERATIONS_PER_SECOND',
    'iopsRead': 'MISC.IO_OPERATIONS_PER_SECOND',
    'iopsReadCapacity': 'MISC.IO_OPERATIONS_PER_SECOND',
    'iopsReadPerf': 'MISC.IO_OPERATIONS_PER_SECOND',
    'iopsRecUnmap': 'MISC.IO_OPERATIONS_PER_SECOND',
    'iopsRecWrite': 'MISC.IO_OPERATIONS_PER_SECOND',
    'iopsResyncRead': 'MISC.IO_OPERATIONS_PER_SECOND',
    'iopsRmw': 'MISC.IO_OPERATIONS_PER_SECOND',
    'iopsSegCleanerUnmap': 'MISC.IO_OPERATIONS_PER_SECOND',
    'iopsUnmap': 'MISC.IO_OPERATIONS_PER_SECOND',
    'iopsUnmapCapacity': 'MISC.IO_OPERATIONS_PER_SECOND',
    'iopsUnmapPerf': 'MISC.IO_OPERATIONS_PER_SECOND',
    'iopsWrite': 'MISC.IO_OPERATIONS_PER_SECOND',
    'iopsWriteCapacity': 'MISC.IO_OPERATIONS_PER_SECOND',
    'iopsWriteConflicts': 'MISC.IO_OPERATIONS_PER_SECOND',
    'iopsWritePerf': 'MISC.IO_OPERATIONS_PER_SECOND',
    'kernelReservedSize': 'DATA_SIZE.BYTE',
    'latAvgCacheGet': 'TIME.MICROSECONDS',
    'latAvgResyncRead': 'TIME.MICROSECONDS',
    'latAvgTotalOpIO': 'TIME.MICROSECONDS',
    'latAvgTxnBank': 'TIME.MICROSECONDS',
    'latAvgTxnBankTotalIO': 'TIME.MICROSECONDS',
    'latAvgTxnUnmap': 'TIME.MICROSECONDS',
    'latAvgTxnUnmapTotalIO': 'TIME.MICROSECONDS',
    'latencyAvg': 'TIME.MICROSECONDS',
    'latencyAvgRead': 'TIME.MICROSECONDS',
    'latencyAvgRecUnmap': 'TIME.MICROSECONDS',
    'latencyAvgRecWrite': 'TIME.MICROSECONDS',
    'latencyAvgResyncRead': 'TIME.MICROSECONDS',
    'latencyAvgSegCleanerUnmap': 'TIME.MICROSECONDS',
    'latencyAvgServiceVMRead': 'TIME.MICROSECONDS',
    'latencyAvgServiceVMWrite': 'TIME.MICROSECONDS',
    'latencyAvgUnmap': 'TIME.MICROSECONDS',
    'latencyAvgWrite': 'TIME.MICROSECONDS',
    'latencyCacheLookup': 'TIME.MICROSECONDS',
    'latencyDevDAvg': 'TIME.MICROSECONDS',
    'latencyDevGAvg': 'TIME.MICROSECONDS',
    'latencyDevKAvg': 'TIME.MICROSECONDS',
    'latencyDevRead': 'TIME.MICROSECONDS',
    'latencyDevUnmap': 'TIME.MICROSECONDS',
    'latencyDevWrite': 'TIME.MICROSECONDS',
    'latencyGwe': 'TIME.MICROSECONDS',
    'latencyMaxRead': 'TIME.MICROSECONDS',
    'latencyMaxSegCleanerUnmap': 'TIME.MICROSECONDS',
    'latencyMaxUnmap': 'TIME.MICROSECONDS',
    'latencyMaxWrite': 'TIME.MICROSECONDS',
    'latencyRead': 'TIME.MICROSECONDS',
    'latencyStddev': 'TIME.MICROSECONDS',
    'latencyStddevRead': 'TIME.MICROSECONDS',
    'latencyStddevRecoveryWrite': 'TIME.MICROSECONDS',
    'latencyStddevResyncRead': 'TIME.MICROSECONDS',
    'latencyStddevSegCleanerUnmap': 'TIME.MICROSECONDS',
    'latencyStddevUnmap': 'TIME.MICROSECONDS',
    'latencyStddevWrite': 'TIME.MICROSECONDS',
    'latencyWrite': 'TIME.MICROSECONDS',
    'maxDiscUsedPct': 'RATIO.PERCENT',
    'maxLatency': 'TIME.MICROSECONDS',
    'maxRunPct': 'RATIO.PERCENT',
    'maxUsedPct': 'RATIO.PERCENT',
    'metadataDispatchedCostRead': 'DATA_RATE.BIBYTE_PER_SECOND',
    'metadataDispatchedCostWrite': 'DATA_RATE.BIBYTE_PER_SECOND',
    'minLatency': 'TIME.MICROSECONDS',
    'namespaceDispatchedCostRead': 'DATA_RATE.BIBYTE_PER_SECOND',
    'namespaceDispatchedCostWrite': 'DATA_RATE.BIBYTE_PER_SECOND',
    'netSchedAvgCompRecoveryWriteDelayMs': 'TIME.MILLISECONDS',
    'netSchedAvgCompResyncReadDelayMs': 'TIME.MILLISECONDS',
    'netSchedAvgOwnerRecoveryWriteDelayMs': 'TIME.MILLISECONDS',
    'netSchedAvgOwnerResyncReadDelayMs': 'TIME.MILLISECONDS',
    'netSchedBWDiscoveredPerDiscoverySession': 'DATA_RATE.BIBYTE_PER_SECOND',
    'netSchedBWDiscoveryAvgIntervalsUs': 'TIME.MICROSECONDS',
    'netSchedBWDiscoveryStopsDueToGainsFromGuestPct': 'RATIO.PERCENT',
    'netSchedBWDiscoveryStopsDueToHighLatencyPct': 'RATIO.PERCENT',
    'netSchedBWDiscoveryStopsDueToLowUtilizationPct': 'RATIO.PERCENT',
    'netSchedBWDiscoveryUtilizationPct': 'RATIO.PERCENT',
    'netSchedBWReallocatedPerReallocationSession': 'DATA_RATE.BIBYTE_PER_SECOND',
    'netSchedBWReallocationAvgIntervalsUs': 'TIME.MICROSECONDS',
    'netSchedBWReallocationStopsDueToHighSharePct': 'RATIO.PERCENT',
    'netSchedBWReallocationStopsDueToLowUtilizationPct': 'RATIO.PERCENT',
    'netSchedBWReallocationUtilizationRatio': 'RATIO.PERCENT',
    'netSchedGuestIopsDecreasePerDiscoverySession': 'MISC.IO_OPERATIONS_PER_SECOND',
    'netSchedGuestIopsIncreasePerReallocationSession': 'MISC.IO_OPERATIONS_PER_SECOND',
    'netSchedLatencyIncreaseFromResyncPerDiscoverySessionPct': 'RATIO.PERCENT',
    'netSchedResyncIopsDecreasePerReallocationSession': 'MISC.IO_OPERATIONS_PER_SECOND',
    'netSchedResyncIopsIncreasePerDiscoverySession': 'MISC.IO_OPERATIONS_PER_SECOND',
    'numNetSchedCompIops': 'MISC.IO_OPERATIONS_PER_SECOND',
    'numNetSchedCompIopsLimit': 'MISC.IO_OPERATIONS_PER_SECOND',
    'numNetSchedCompRecoveryWriteIops': 'MISC.IO_OPERATIONS_PER_SECOND',
    'numNetSchedCompRecoveryWriteIopsLimit': 'MISC.IO_OPERATIONS_PER_SECOND',
    'numNetSchedCompRecoveryWriteTpThrottled': 'DATA_RATE.BIBYTE_PER_SECOND',
    'numNetSchedCompResyncReadIops': 'MISC.IO_OPERATIONS_PER_SECOND',
    'numNetSchedCompResyncReadIopsLimit': 'MISC.IO_OPERATIONS_PER_SECOND',
    'numNetSchedCompResyncReadTpThrottled': 'DATA_RATE.BIBYTE_PER_SECOND',
    'numNetSchedCompTpThrottled': 'DATA_RATE.BIBYTE_PER_SECOND',
    'numNetSchedControllerIopsLimit': 'MISC.IO_OPERATIONS_PER_SECOND',
    'numNetSchedHighBandSec': 'TIME.SECONDS',
    'numNetSchedLowBandSec': 'TIME.SECONDS',
    'numNetSchedMidBandSec': 'TIME.SECONDS',
    'numNetSchedOwnerIops': 'MISC.IO_OPERATIONS_PER_SECOND',
    'numNetSchedOwnerIopsLimit': 'MISC.IO_OPERATIONS_PER_SECOND',
    'numNetSchedOwnerRecoveryWriteIops': 'MISC.IO_OPERATIONS_PER_SECOND',
    'numNetSchedOwnerRecoveryWriteIopsLimit': 'MISC.IO_OPERATIONS_PER_SECOND',
    'numNetSchedOwnerRecoveryWriteTpThrottled': 'DATA_RATE.BIBYTE_PER_SECOND',
    'numNetSchedOwnerResyncReadIops': 'MISC.IO_OPERATIONS_PER_SECOND',
    'numNetSchedOwnerResyncReadIopsLimit': 'MISC.IO_OPERATIONS_PER_SECOND',
    'numNetSchedOwnerResyncReadTpThrottled': 'DATA_RATE.BIBYTE_PER_SECOND',
    'numNetSchedOwnerTpThrottled': 'DATA_RATE.BIBYTE_PER_SECOND',
    'numNetSchedResyncTotalSharePercent': 'RATIO.PERCENT',
    'numNetSchedRollingAvgLatUs': 'TIME.MICROSECONDS',
    'numNetSchedSeenNonResyncTpBps': 'DATA_RATE.BIBYTE_PER_SECOND',
    'numNetSchedSeenResyncTpBps': 'DATA_RATE.BIBYTE_PER_SECOND',
    'numNetSchedSeenTotalTpBps': 'DATA_RATE.BIBYTE_PER_SECOND',
    'osfsdConsumedSize': 'DATA_SIZE.BYTE',
    'osfsdReservedSize': 'DATA_SIZE.BYTE',
    'overcommitRatio': 'RATIO.PERCENT',
    'owner2PCCommitLatencyAvgUs': 'TIME.MICROSECONDS',
    'ownerECCacheHitMissRatio': 'RATIO.PERCENT',
    'pcpuUsedPct': 'RATIO.PERCENT',
    'pcpuUtilPct': 'RATIO.PERCENT',
    'pctMemUsed': 'RATIO.PERCENT',
    'prefetchCacheMaxGetLatUs': 'TIME.MICROSECONDS',
    'rdtRxThroughput': 'DATA_RATE.BIBYTE_PER_SECOND',
    'rdtTxThroughput': 'DATA_RATE.BIBYTE_PER_SECOND',
    'readECLeafOwnerMaxLatencyAvgUs': 'TIME.MICROSECONDS',
    'readECLeafOwnerMaxLatencyUs': 'TIME.MICROSECONDS',
    'readLatencyMaxUs': 'TIME.MICROSECONDS',
    'readLeafOwnerIops': 'MISC.IO_OPERATIONS_PER_SECOND',
    'readLeafOwnerLatency': 'TIME.MICROSECONDS',
    'readLeafOwnerLatencyLocal': 'TIME.MICROSECONDS',
    'readLeafOwnerLatencyRemote': 'TIME.MICROSECONDS',
    'readLeafOwnerMaxLatencyAvgUs': 'TIME.MICROSECONDS',
    'readLeafOwnerThroughput': 'DATA_RATE.BIBYTE_PER_SECOND',
    'readyPct': 'RATIO.PERCENT',
    'recoveryUnmapLeafOwnerLatency': 'TIME.MICROSECONDS',
    'recoveryWriteLeafOwnerLatency': 'TIME.MICROSECONDS',
    'recoveryWriteLeafOwnerLatencyLocal': 'TIME.MICROSECONDS',
    'recoveryWriteLeafOwnerLatencyRemote': 'TIME.MICROSECONDS',
    'regulatorIopsRead': 'MISC.IO_OPERATIONS_PER_SECOND',
    'regulatorIopsWrite': 'MISC.IO_OPERATIONS_PER_SECOND',
    'resyncDispatchedCostRead': 'DATA_RATE.BIBYTE_PER_SECOND',
    'resyncDispatchedCostWrite': 'DATA_RATE.BIBYTE_PER_SECOND',
    'resyncReadLeafOwnerLatency': 'TIME.MICROSECONDS',
    'resyncReadLeafOwnerLatencyLocal': 'TIME.MICROSECONDS',
    'resyncReadLeafOwnerLatencyRemote': 'TIME.MICROSECONDS',
    'runPct': 'RATIO.PERCENT',
    'rxSbSpaceAvg': 'DATA_SIZE.BYTE',
    'rxSbSpaceMax': 'DATA_SIZE.BYTE',
    'rxSbSpaceMin': 'DATA_SIZE.BYTE',
    'rxThroughput': 'DATA_RATE.BIBYTE_PER_SECOND',
    'segCleanerUnmapLeafOwnerLatency': 'TIME.MICROSECONDS',
    'segCleanerUnmapLeafOwnerMaxLatencyAvgUs': 'TIME.MICROSECONDS',
    'serverSwitchAvglatency': 'TIME.MICROSECONDS',
    'serverSwitchLatencyMaxUs': 'TIME.MICROSECONDS',
    'serverSwitchlatencyStddev': 'TIME.MICROSECONDS',
    'tcpRxThroughput': 'DATA_RATE.BIBYTE_PER_SECOND',
    'tcpTxThroughput': 'DATA_RATE.BIBYTE_PER_SECOND',
    'throughput': 'DATA_RATE.BIBYTE_PER_SECOND',
    'throughputDevRead': 'DATA_RATE.BIBYTE_PER_SECOND',
    'throughputDevUnmap': 'DATA_RATE.BIBYTE_PER_SECOND',
    'throughputDevWrite': 'DATA_RATE.BIBYTE_PER_SECOND',
    'throughputRead': 'DATA_RATE.BIBYTE_PER_SECOND',
    'throughputRecUnmap': 'DATA_RATE.BIBYTE_PER_SECOND',
    'throughputRecWrite': 'DATA_RATE.BIBYTE_PER_SECOND',
    'throughputSegCleanerUnmap': 'DATA_RATE.BIBYTE_PER_SECOND',
    'throughputUnmap': 'DATA_RATE.BIBYTE_PER_SECOND',
    'throughputWrite': 'DATA_RATE.BIBYTE_PER_SECOND',
    'totalDeltaCreationDomActiveLatency': 'TIME.MICROSECONDS',
    'totalDeltaCreationDomCreationLatency': 'TIME.MICROSECONDS',
    'totalMbMemUsed': 'DATA_SIZE.MEGABYTE',
    'tputRead': 'DATA_RATE.BIBYTE_PER_SECOND',
    'tputRecUnmap': 'DATA_RATE.BIBYTE_PER_SECOND',
    'tputRecWrite': 'DATA_RATE.BIBYTE_PER_SECOND',
    'tputResyncRead': 'DATA_RATE.BIBYTE_PER_SECOND',
    'tputServiceVMRead': 'DATA_RATE.BIBYTE_PER_SECOND',
    'tputServiceVMWrite': 'DATA_RATE.BIBYTE_PER_SECOND',
    'tputUnmap': 'DATA_RATE.BIBYTE_PER_SECOND',
    'tputWrite': 'DATA_RATE.BIBYTE_PER_SECOND',
    'twoPCBatchCommitBlockedByGuestIOPS': 'MISC.IO_OPERATIONS_PER_SECOND',
    'twoPCBatchCommitBlockedByOtherIOPS': 'MISC.IO_OPERATIONS_PER_SECOND',
    'twoPCBatchCommitBlockedByResyncIOPS': 'MISC.IO_OPERATIONS_PER_SECOND',
    'twoPCBatchCommitBlockedBySyncIOPS': 'MISC.IO_OPERATIONS_PER_SECOND',
    'twoPCBatchCommitGuestIOPS': 'MISC.IO_OPERATIONS_PER_SECOND',
    'twoPCBatchCommitOtherIOPS': 'MISC.IO_OPERATIONS_PER_SECOND',
    'twoPCBatchCommitResyncIOPS': 'MISC.IO_OPERATIONS_PER_SECOND',
    'twoPCBatchCommitSyncIOPS': 'MISC.IO_OPERATIONS_PER_SECOND',
    'twoPCPrepareLimitRetryGuestAvgTimeMs': 'TIME.MILLISECONDS',
    'twoPCPrepareLimitRetryGuestIOPS': 'MISC.IO_OPERATIONS_PER_SECOND',
    'twoPCPrepareLimitRetryOtherAvgTimeMs': 'TIME.MILLISECONDS',
    'twoPCPrepareLimitRetryOtherIOPS': 'MISC.IO_OPERATIONS_PER_SECOND',
    'twoPCPrepareLimitRetryResyncAvgTimeMs': 'TIME.MILLISECONDS',
    'twoPCPrepareLimitRetryResyncIOPS': 'MISC.IO_OPERATIONS_PER_SECOND',
    'txCtxQAvg': 'DATA_SIZE.BYTE',
    'txCtxQMax': 'DATA_SIZE.BYTE',
    'txCtxQMin': 'DATA_SIZE.BYTE',
    'txQLatAvg': 'TIME.MICROSECONDS',
    'txQLatMax': 'TIME.MICROSECONDS',
    'txQLatMin': 'TIME.MICROSECONDS',
    'txSbSpaceAvg': 'DATA_SIZE.BYTE',
    'txSbSpaceMax': 'DATA_SIZE.BYTE',
    'txSbSpaceMin': 'DATA_SIZE.BYTE',
    'txThroughput': 'DATA_RATE.BIBYTE_PER_SECOND',
    'txnBankMaxLatUs': 'TIME.MICROSECONDS',
    'txnCacheFlushMaxLatUs': 'TIME.MICROSECONDS',
    'txnDLogMaxLatUs': 'TIME.MICROSECONDS',
    'txnDelExtMiddleTreeMaxLatUs': 'TIME.MICROSECONDS',
    'txnPrefetchMaxLatUs': 'TIME.MICROSECONDS',
    'txnSegCtxDataMaxLatUs': 'TIME.MICROSECONDS',
    'txnSegCtxLLPMaxLatUs': 'TIME.MICROSECONDS',
    'txnUnmapMaxLatUs': 'TIME.MICROSECONDS',
    'txnVatWriteSegMaxLatUs': 'TIME.MICROSECONDS',
    'unmapECLeafOwnerMaxLatencyAvgUs': 'TIME.MICROSECONDS',
    'unmapECLeafOwnerMaxLatencyUs': 'TIME.MICROSECONDS',
    'unmapLatencyMaxUs': 'TIME.MICROSECONDS',
    'unmapLeafOwnerLatency': 'TIME.MICROSECONDS',
    'unmapLeafOwnerMaxLatencyAvgUs': 'TIME.MICROSECONDS',
    'usedPct': 'RATIO.PERCENT',
    'uwConsumedSize': 'DATA_SIZE.BYTE',
    'uwReservedSize': 'DATA_SIZE.BYTE',
    'vitdConsumedSize': 'DATA_SIZE.BYTE',
    'vitdReservedSize': 'DATA_SIZE.BYTE',
    'vmdiskDispatchedCostRead': 'DATA_RATE.BIBYTE_PER_SECOND',
    'vmdiskDispatchedCostWrite': 'DATA_RATE.BIBYTE_PER_SECOND',
    'vsandevicemonitordConsumedSize': 'DATA_SIZE.BYTE',
    'vsandevicemonitordReservedSize': 'DATA_SIZE.BYTE',
    'vsanmgmtdConsumedSize': 'DATA_SIZE.BYTE',
    'vsanmgmtdReservedSize': 'DATA_SIZE.BYTE',
    'vsanmgmtdWatchdogConsumedSize': 'DATA_SIZE.BYTE',
    'vsanmgmtdWatchdogReservedSize': 'DATA_SIZE.BYTE',
    'vsanobserverConsumedSize': 'DATA_SIZE.BYTE',
    'vsanobserverReservedSize': 'DATA_SIZE.BYTE',
    'vsantracedConsumedSize': 'DATA_SIZE.BYTE',
    'vsantracedReservedSize': 'DATA_SIZE.BYTE',
    'writeECLeafOwnerMaxLatencyAvgUs': 'TIME.MICROSECONDS',
    'writeECLeafOwnerMaxLatencyUs': 'TIME.MICROSECONDS',
    'writeLatencyMaxUs': 'TIME.MICROSECONDS',
    'writeLeafOwnerIops': 'MISC.IO_OPERATIONS_PER_SECOND',
    'writeLeafOwnerLatency': 'TIME.MICROSECONDS',
    'writeLeafOwnerLatencyLocal': 'TIME.MICROSECONDS',
    'writeLeafOwnerLatencyRemote': 'TIME.MICROSECONDS',
    'writeLeafOwnerMaxLatencyAvgUs': 'TIME.MICROSECONDS',
    'writeLeafOwnerThroughput': 'DATA_RATE.BIBYTE_PER_SECOND',
}
