"""GENERATED -- do not edit by hand.

Regenerate with:
    python3 tools/model_from_exposition.py \
        docs/sample-exposition-esxi01.txt --python app/model.py

Derived from a real /vsanmetrics exposition.  Each family becomes one
resource kind; identity labels split objects, measurement labels become
part of the metric key.
"""

from typing import Dict, List, Tuple

HOST_LABELS = ['host_uuid', 'hostname', 'vsan_cluster_uuid']

# family -> resource kind definition
FAMILIES: Dict[str, dict] = {
    'vmware_esx_heap': {
        'identity': ['heap_id'],
        'metric_key_labels': [],
        'properties': ['heap_name', 'sink_type', 'subsystem'],
        'objects_per_host': 31,
        'metrics': [
            ('usage_ratio', 'vmware_esx_heap_usage_ratio', [], 'Point in time. Usage of heap (mempool) in percent. For some being full is normal, others may impact control or IO operations'),
        ],
    },
    'vmware_esx_pnic': {
        'identity': ['vmnic'],
        'metric_key_labels': ['io_type'],
        'properties': ['sink_type'],
        'objects_per_host': 2,
        'metrics': [
            ('pkt_bytes_total|rx', 'vmware_esx_pnic_pkt_bytes_total', ['rx'], 'Total Bytes processed by ESX physical NIC since boot. (rx)'),
            ('pkt_bytes_total|tx', 'vmware_esx_pnic_pkt_bytes_total', ['tx'], 'Total Bytes processed by ESX physical NIC since boot. (tx)'),
            ('pkt_err_total|rx', 'vmware_esx_pnic_pkt_err_total', ['rx'], 'rx'),
            ('pkt_err_total|tx', 'vmware_esx_pnic_pkt_err_total', ['tx'], 'tx'),
            ('pkt_total|rx', 'vmware_esx_pnic_pkt_total', ['rx'], 'Total Packets processed by ESX physical NIC since boot. (rx)'),
            ('pkt_total|tx', 'vmware_esx_pnic_pkt_total', ['tx'], 'Total Packets processed by ESX physical NIC since boot. (tx)'),
        ],
    },
    'vmware_esx_rdt': {
        'identity': [],
        'metric_key_labels': [],
        'properties': ['name', 'sink_type', 'unicast_agent_ipv4'],
        'objects_per_host': 1,
        'metrics': [
            ('checksum_mismatch_count', 'vmware_esx_rdt_checksum_mismatch_count', [], 'The count of RDT checksum mismatch.'),
            ('latency_us', 'vmware_esx_rdt_latency_us', [], 'The RDT roundtrip network latency in microsecond'),
        ],
    },
    'vmware_esx_slab': {
        'identity': ['slab'],
        'metric_key_labels': [],
        'properties': ['sink_type', 'subsystem'],
        'objects_per_host': 62,
        'metrics': [
            ('alloc_count', 'vmware_esx_slab_alloc_count', [], 'Point in time. Number of objects allocated/used. For some being full is normal, others may impact control or IO operations'),
            ('max_count', 'vmware_esx_slab_max_count', [], 'Point in time. Total number of objects in the slab that could be allocated from. For some being full is normal, others may impact control or IO operations'),
        ],
    },
    'vmware_esx_tcppkt': {
        'identity': ['stack'],
        'metric_key_labels': ['io_type'],
        'properties': ['sink_type'],
        'objects_per_host': 1,
        'metrics': [
            ('bytes_total|rx', 'vmware_esx_tcppkt_bytes_total', ['rx'], 'Total Bytes processed by ESX TCP since boot. (rx)'),
            ('bytes_total|tx', 'vmware_esx_tcppkt_bytes_total', ['tx'], 'Total Bytes processed by ESX TCP since boot. (tx)'),
            ('rcvdupack_total', 'vmware_esx_tcppkt_rcvdupack_total', [''], 'Total received duplicate ACKs by ESX TCP since boot. ()'),
            ('rcvduppack_total', 'vmware_esx_tcppkt_rcvduppack_total', [''], 'Total received duplicate packets by ESX TCP since boot. ()'),
            ('rcvoopack_total', 'vmware_esx_tcppkt_rcvoopack_total', [''], 'Total received out-of-order packets by ESX TCP since boot. ()'),
            ('sack_rcv_blocks_total', 'vmware_esx_tcppkt_sack_rcv_blocks_total', [''], 'Total received SACK asks for blocks by ESX TCP since boot. ()'),
            ('sack_rexmits_total', 'vmware_esx_tcppkt_sack_rexmits_total', [''], 'Total sent SACK asks for blocks by ESX TCP since boot. ()'),
            ('sack_send_blocks_total', 'vmware_esx_tcppkt_sack_send_blocks_total', [''], 'Total requested SACK retransmit of blocks by ESX TCP since boot. ()'),
            ('sndrexmitpack_total', 'vmware_esx_tcppkt_sndrexmitpack_total', [''], 'Total retransmitted packets by ESX TCP since boot. ()'),
            ('total|rx', 'vmware_esx_tcppkt_total', ['rx'], 'Total Packets processed by ESX TCP since boot. (rx)'),
            ('total|tx', 'vmware_esx_tcppkt_total', ['tx'], 'Total Packets processed by ESX TCP since boot. (tx)'),
        ],
    },
    'vmware_esx_world': {
        'identity': ['world_id'],
        'metric_key_labels': [],
        'properties': ['name', 'sink_type', 'role', 'subsystem'],
        'objects_per_host': 167,
        'metrics': [
            ('readytime_seconds_total', 'vmware_esx_world_readytime_seconds_total', [], 'Worlds is what ESX calls threads. Except when noted in the name, refers to a single world. readytime is a sum total of the time the world was activated, but waiting for a pCPU.'),
            ('uptime_seconds_total', 'vmware_esx_world_uptime_seconds_total', [], 'Worlds is what ESX calls threads. Except when noted in the name, refers to a single world. uptime is a sum total of the time the world was not paused'),
            ('usedtime_seconds_total', 'vmware_esx_world_usedtime_seconds_total', [], 'Worlds is what ESX calls threads. Except when noted in the name, refers to a single world. usedtime is a sum total of the time the world was running on a pCPU. So usedtime/uptime i'),
        ],
    },
    'vmware_host_cpu': {
        'identity': ['cpu'],
        'metric_key_labels': ['type'],
        'properties': ['sink_type'],
        'objects_per_host': 65,
        'metrics': [
            ('seconds_total|coreutiltime', 'vmware_host_cpu_seconds_total', ['coreutiltime'], 'usedtime is a sum total of the used time of all pCPUs on host. elapsedtime is a sum total of the elapsed time of all pCPUs on host. utiltime is a sum total of the utilization time '),
            ('seconds_total|elapsedtime', 'vmware_host_cpu_seconds_total', ['elapsedtime'], 'usedtime is a sum total of the used time of all pCPUs on host. elapsedtime is a sum total of the elapsed time of all pCPUs on host. utiltime is a sum total of the utilization time '),
            ('seconds_total|usedtime', 'vmware_host_cpu_seconds_total', ['usedtime'], 'usedtime is a sum total of the used time of all pCPUs on host. elapsedtime is a sum total of the elapsed time of all pCPUs on host. utiltime is a sum total of the utilization time '),
            ('seconds_total|utiltime', 'vmware_host_cpu_seconds_total', ['utiltime'], 'usedtime is a sum total of the used time of all pCPUs on host. elapsedtime is a sum total of the elapsed time of all pCPUs on host. utiltime is a sum total of the utilization time '),
        ],
    },
    'vmware_vsan_cmmds': {
        'identity': [],
        'metric_key_labels': ['sink_type', 'type'],
        'properties': [],
        'objects_per_host': 1,
        'metrics': [
            ('local_updates_count|hot|completed', 'vmware_vsan_cmmds_local_updates_count', ['hot', 'completed'], 'Number of local updates. (hot, completed)'),
            ('local_updates_count|hot|received', 'vmware_vsan_cmmds_local_updates_count', ['hot', 'received'], 'Number of local updates. (hot, received)'),
            ('local_updates_count|hot|transmitted', 'vmware_vsan_cmmds_local_updates_count', ['hot', 'transmitted'], 'Number of local updates. (hot, transmitted)'),
            ('update_latency|hot|cumulative', 'vmware_vsan_cmmds_update_latency', ['hot', 'cumulative'], 'Update latency of local updates committed in USec. (hot, cumulative)'),
            ('update_latency|hot|max', 'vmware_vsan_cmmds_update_latency', ['hot', 'max'], 'Update latency of local updates committed in USec. (hot, max)'),
            ('update_latency|hot|min', 'vmware_vsan_cmmds_update_latency', ['hot', 'min'], 'Update latency of local updates committed in USec. (hot, min)'),
            ('updates_count_at_leader|hot|committed', 'vmware_vsan_cmmds_updates_count_at_leader', ['hot', 'committed'], 'Number of updates happened at leader. (hot, committed)'),
            ('updates_count_at_leader|hot|received', 'vmware_vsan_cmmds_updates_count_at_leader', ['hot', 'received'], 'Number of updates happened at leader. (hot, received)'),
            ('workload_agent_batches_sent|cold', 'vmware_vsan_cmmds_workload_agent_batches_sent', ['cold', ''], 'Number of update batches sent by the agent to master. (cold)'),
            ('workload_check_point_batches_sent|cold', 'vmware_vsan_cmmds_workload_check_point_batches_sent', ['cold', ''], 'Number of checkpoint batches sent by the master to backup. (cold)'),
            ('workload_heartbeat_soft_timeouts|hot', 'vmware_vsan_cmmds_workload_heartbeat_soft_timeouts', ['hot', ''], 'Number of heartbeat soft timeout. (hot)'),
            ('workload_heartbeats_missed|hot', 'vmware_vsan_cmmds_workload_heartbeats_missed', ['hot', ''], 'Number of heartbeat missed. (hot)'),
            ('workload_master_batches_recved|cold', 'vmware_vsan_cmmds_workload_master_batches_recved', ['cold', ''], 'Number of update batches sent by the master to agent. (cold)'),
            ('workload_rx_accept|cold', 'vmware_vsan_cmmds_workload_rx_accept', ['cold', ''], 'Number of total (local and remote) update requests received. (cold)'),
            ('workload_rx_agent_update_request|cold', 'vmware_vsan_cmmds_workload_rx_agent_update_request', ['cold', ''], 'Number of agent update messages received. (cold)'),
            ('workload_rx_heartbeat_request|cold', 'vmware_vsan_cmmds_workload_rx_heartbeat_request', ['cold', ''], 'Number of heartbeat request messages received. (cold)'),
            ('workload_rx_master_update|cold', 'vmware_vsan_cmmds_workload_rx_master_update', ['cold', ''], 'Number of all master update messages received. (cold)'),
            ('workload_rx_misc|cold', 'vmware_vsan_cmmds_workload_rx_misc', ['cold', ''], 'Number of miscellaneous message received. (cold)'),
            ('workload_rx_retransmit_request|cold', 'vmware_vsan_cmmds_workload_rx_retransmit_request', ['cold', ''], 'Number of retransmit request messages received. (cold)'),
            ('workload_rx_snapshot|cold', 'vmware_vsan_cmmds_workload_rx_snapshot', ['cold', ''], 'Number of snapshot message received. (cold)'),
            ('workload_total_upd_in_batch_ckpt|cold', 'vmware_vsan_cmmds_workload_total_upd_in_batch_ckpt', ['cold', ''], 'Number of checkpoints sent in batch by the master to backup. (cold)'),
            ('workload_total_upd_in_master_batches|cold', 'vmware_vsan_cmmds_workload_total_upd_in_master_batches', ['cold', ''], 'Number of updates sent in batch by the master to agent. (cold)'),
            ('workload_total_upd_sent_in_agent_batch|cold', 'vmware_vsan_cmmds_workload_total_upd_sent_in_agent_batch', ['cold', ''], 'Number of updates sent in batch updates by the agent to master. (cold)'),
            ('workload_tx_agent_update_request|cold', 'vmware_vsan_cmmds_workload_tx_agent_update_request', ['cold', ''], 'Number of agent update messages sent. (cold)'),
            ('workload_tx_heartbeat_request|cold', 'vmware_vsan_cmmds_workload_tx_heartbeat_request', ['cold', ''], 'Number of heartbeat request messages sent. (cold)'),
            ('workload_tx_master_checkpoint|cold', 'vmware_vsan_cmmds_workload_tx_master_checkpoint', ['cold', ''], 'Number of master checkpoint messages sent. (cold)'),
            ('workload_tx_master_ckpt_tried|cold', 'vmware_vsan_cmmds_workload_tx_master_ckpt_tried', ['cold', ''], 'Number of master checkpoint messages tried to send. (cold)'),
            ('workload_tx_master_update|cold', 'vmware_vsan_cmmds_workload_tx_master_update', ['cold', ''], 'Number of master update messages sent. (cold)'),
            ('workload_tx_master_update_tried|cold', 'vmware_vsan_cmmds_workload_tx_master_update_tried', ['cold', ''], 'Number of master update messages tried to send. (cold)'),
            ('workload_tx_retransmit_request|cold', 'vmware_vsan_cmmds_workload_tx_retransmit_request', ['cold', ''], 'Number of retransmit request messages sent. (cold)'),
            ('workload_tx_snapshot|cold', 'vmware_vsan_cmmds_workload_tx_snapshot', ['cold', ''], 'Number of snapshot messages sent. (cold)'),
            ('workload_tx_snapshot_bytes|cold', 'vmware_vsan_cmmds_workload_tx_snapshot_bytes', ['cold', ''], 'Bytes of snapshot messages sent. (cold)'),
            ('workload_tx_snapshot_tried|cold', 'vmware_vsan_cmmds_workload_tx_snapshot_tried', ['cold', ''], 'Number of snapshot messages tried to send. (cold)'),
        ],
    },
    'vmware_vsan_disk': {
        'identity': ['disk_uuid'],
        'metric_key_labels': [],
        'properties': ['sink_type'],
        'objects_per_host': 2,
        'metrics': [
            ('checksum_errors_total', 'vmware_vsan_disk_checksum_errors_total', [], 'Total checksum errors of vSAN disk'),
        ],
    },
    'vmware_vsan_dom': {
        'identity': [],
        'metric_key_labels': ['io_type', 'role', 'sink_type'],
        'properties': [],
        'objects_per_host': 1,
        'metrics': [
            ('clientcache_readhit_count|cold', 'vmware_vsan_dom_clientcache_readhit_count', ['', '', 'cold'], 'Total number of cache hit Read IOs seen by vSAN DOM Client memory read cache since boot (number). (cold)'),
            ('clientcache_readio_count|cold', 'vmware_vsan_dom_clientcache_readio_count', ['', '', 'cold'], 'Total number of Read IOs seen by vSAN DOM Client memory read cache since boot (number). (cold)'),
            ('congestion_total|read|client|cold', 'vmware_vsan_dom_congestion_total', ['read', 'client', 'cold'], 'Sum total of observed congestion values by vSAN DOM since boot. (read, client, cold)'),
            ('congestion_total|read|compmgr|cold', 'vmware_vsan_dom_congestion_total', ['read', 'compmgr', 'cold'], 'Sum total of observed congestion values by vSAN DOM since boot. (read, compmgr, cold)'),
            ('congestion_total|read|owner|cold', 'vmware_vsan_dom_congestion_total', ['read', 'owner', 'cold'], 'Sum total of observed congestion values by vSAN DOM since boot. (read, owner, cold)'),
            ('congestion_total|recoveryWrite|compmgr|cold', 'vmware_vsan_dom_congestion_total', ['recoveryWrite', 'compmgr', 'cold'], 'Sum total of observed congestion values by vSAN DOM since boot. (recoveryWrite, compmgr, cold)'),
            ('congestion_total|recoveryWrite|owner|cold', 'vmware_vsan_dom_congestion_total', ['recoveryWrite', 'owner', 'cold'], 'Sum total of observed congestion values by vSAN DOM since boot. (recoveryWrite, owner, cold)'),
            ('congestion_total|resyncRead|compmgr|cold', 'vmware_vsan_dom_congestion_total', ['resyncRead', 'compmgr', 'cold'], 'Sum total of observed congestion values by vSAN DOM since boot. (resyncRead, compmgr, cold)'),
            ('congestion_total|resyncRead|owner|cold', 'vmware_vsan_dom_congestion_total', ['resyncRead', 'owner', 'cold'], 'Sum total of observed congestion values by vSAN DOM since boot. (resyncRead, owner, cold)'),
            ('congestion_total|unmap|client|cold', 'vmware_vsan_dom_congestion_total', ['unmap', 'client', 'cold'], 'Sum total of observed congestion values by vSAN DOM since boot. (unmap, client, cold)'),
            ('congestion_total|unmap|compmgr|cold', 'vmware_vsan_dom_congestion_total', ['unmap', 'compmgr', 'cold'], 'Sum total of observed congestion values by vSAN DOM since boot. (unmap, compmgr, cold)'),
            ('congestion_total|unmap|owner|cold', 'vmware_vsan_dom_congestion_total', ['unmap', 'owner', 'cold'], 'Sum total of observed congestion values by vSAN DOM since boot. (unmap, owner, cold)'),
            ('congestion_total|write|client|cold', 'vmware_vsan_dom_congestion_total', ['write', 'client', 'cold'], 'Sum total of observed congestion values by vSAN DOM since boot. (write, client, cold)'),
            ('congestion_total|write|compmgr|cold', 'vmware_vsan_dom_congestion_total', ['write', 'compmgr', 'cold'], 'Sum total of observed congestion values by vSAN DOM since boot. (write, compmgr, cold)'),
            ('congestion_total|write|owner|cold', 'vmware_vsan_dom_congestion_total', ['write', 'owner', 'cold'], 'Sum total of observed congestion values by vSAN DOM since boot. (write, owner, cold)'),
            ('io_bytes_total|read|client|hot', 'vmware_vsan_dom_io_bytes_total', ['read', 'client', 'hot'], 'Total Bytes processed by vSAN DOM since boot. (read, client, hot)'),
            ('io_bytes_total|read|compmgr|hot', 'vmware_vsan_dom_io_bytes_total', ['read', 'compmgr', 'hot'], 'Total Bytes processed by vSAN DOM since boot. (read, compmgr, hot)'),
            ('io_bytes_total|read|owner|hot', 'vmware_vsan_dom_io_bytes_total', ['read', 'owner', 'hot'], 'Total Bytes processed by vSAN DOM since boot. (read, owner, hot)'),
            ('io_bytes_total|recoveryWrite|compmgr|hot', 'vmware_vsan_dom_io_bytes_total', ['recoveryWrite', 'compmgr', 'hot'], 'Total Bytes processed by vSAN DOM since boot. (recoveryWrite, compmgr, hot)'),
            ('io_bytes_total|recoveryWrite|owner|hot', 'vmware_vsan_dom_io_bytes_total', ['recoveryWrite', 'owner', 'hot'], 'Total Bytes processed by vSAN DOM since boot. (recoveryWrite, owner, hot)'),
            ('io_bytes_total|resyncRead|compmgr|hot', 'vmware_vsan_dom_io_bytes_total', ['resyncRead', 'compmgr', 'hot'], 'Total Bytes processed by vSAN DOM since boot. (resyncRead, compmgr, hot)'),
            ('io_bytes_total|resyncRead|owner|hot', 'vmware_vsan_dom_io_bytes_total', ['resyncRead', 'owner', 'hot'], 'Total Bytes processed by vSAN DOM since boot. (resyncRead, owner, hot)'),
            ('io_bytes_total|unmap|client|hot', 'vmware_vsan_dom_io_bytes_total', ['unmap', 'client', 'hot'], 'Total Bytes processed by vSAN DOM since boot. (unmap, client, hot)'),
            ('io_bytes_total|unmap|compmgr|hot', 'vmware_vsan_dom_io_bytes_total', ['unmap', 'compmgr', 'hot'], 'Total Bytes processed by vSAN DOM since boot. (unmap, compmgr, hot)'),
            ('io_bytes_total|unmap|owner|hot', 'vmware_vsan_dom_io_bytes_total', ['unmap', 'owner', 'hot'], 'Total Bytes processed by vSAN DOM since boot. (unmap, owner, hot)'),
            ('io_bytes_total|write|client|hot', 'vmware_vsan_dom_io_bytes_total', ['write', 'client', 'hot'], 'Total Bytes processed by vSAN DOM since boot. (write, client, hot)'),
            ('io_bytes_total|write|compmgr|hot', 'vmware_vsan_dom_io_bytes_total', ['write', 'compmgr', 'hot'], 'Total Bytes processed by vSAN DOM since boot. (write, compmgr, hot)'),
            ('io_bytes_total|write|owner|hot', 'vmware_vsan_dom_io_bytes_total', ['write', 'owner', 'hot'], 'Total Bytes processed by vSAN DOM since boot. (write, owner, hot)'),
            ('io_duration_seconds_total|read|client|hot', 'vmware_vsan_dom_io_duration_seconds_total', ['read', 'client', 'hot'], 'Sum total of duration of IO processed by vSAN DOM since boot. (read, client, hot)'),
            ('io_duration_seconds_total|read|compmgr|hot', 'vmware_vsan_dom_io_duration_seconds_total', ['read', 'compmgr', 'hot'], 'Sum total of duration of IO processed by vSAN DOM since boot. (read, compmgr, hot)'),
            ('io_duration_seconds_total|read|owner|hot', 'vmware_vsan_dom_io_duration_seconds_total', ['read', 'owner', 'hot'], 'Sum total of duration of IO processed by vSAN DOM since boot. (read, owner, hot)'),
            ('io_duration_seconds_total|read|ownerLeaf|hot', 'vmware_vsan_dom_io_duration_seconds_total', ['read', 'ownerLeaf', 'hot'], 'Sum total of duration of IO processed by vSAN DOM since boot. (read, ownerLeaf, hot)'),
            ('io_duration_seconds_total|recoveryUnmap|ownerLeaf|hot', 'vmware_vsan_dom_io_duration_seconds_total', ['recoveryUnmap', 'ownerLeaf', 'hot'], 'Sum total of duration of IO processed by vSAN DOM since boot. (recoveryUnmap, ownerLeaf, hot)'),
            ('io_duration_seconds_total|recoveryWrite|compmgr|hot', 'vmware_vsan_dom_io_duration_seconds_total', ['recoveryWrite', 'compmgr', 'hot'], 'Sum total of duration of IO processed by vSAN DOM since boot. (recoveryWrite, compmgr, hot)'),
            ('io_duration_seconds_total|recoveryWrite|owner|hot', 'vmware_vsan_dom_io_duration_seconds_total', ['recoveryWrite', 'owner', 'hot'], 'Sum total of duration of IO processed by vSAN DOM since boot. (recoveryWrite, owner, hot)'),
            ('io_duration_seconds_total|recoveryWrite|ownerLeaf|hot', 'vmware_vsan_dom_io_duration_seconds_total', ['recoveryWrite', 'ownerLeaf', 'hot'], 'Sum total of duration of IO processed by vSAN DOM since boot. (recoveryWrite, ownerLeaf, hot)'),
            ('io_duration_seconds_total|resyncRead|compmgr|hot', 'vmware_vsan_dom_io_duration_seconds_total', ['resyncRead', 'compmgr', 'hot'], 'Sum total of duration of IO processed by vSAN DOM since boot. (resyncRead, compmgr, hot)'),
            ('io_duration_seconds_total|resyncRead|owner|hot', 'vmware_vsan_dom_io_duration_seconds_total', ['resyncRead', 'owner', 'hot'], 'Sum total of duration of IO processed by vSAN DOM since boot. (resyncRead, owner, hot)'),
            ('io_duration_seconds_total|unmap|client|hot', 'vmware_vsan_dom_io_duration_seconds_total', ['unmap', 'client', 'hot'], 'Sum total of duration of IO processed by vSAN DOM since boot. (unmap, client, hot)'),
            ('io_duration_seconds_total|unmap|compmgr|hot', 'vmware_vsan_dom_io_duration_seconds_total', ['unmap', 'compmgr', 'hot'], 'Sum total of duration of IO processed by vSAN DOM since boot. (unmap, compmgr, hot)'),
            ('io_duration_seconds_total|unmap|owner|hot', 'vmware_vsan_dom_io_duration_seconds_total', ['unmap', 'owner', 'hot'], 'Sum total of duration of IO processed by vSAN DOM since boot. (unmap, owner, hot)'),
            ('io_duration_seconds_total|unmap|ownerLeaf|hot', 'vmware_vsan_dom_io_duration_seconds_total', ['unmap', 'ownerLeaf', 'hot'], 'Sum total of duration of IO processed by vSAN DOM since boot. (unmap, ownerLeaf, hot)'),
            ('io_duration_seconds_total|write|client|hot', 'vmware_vsan_dom_io_duration_seconds_total', ['write', 'client', 'hot'], 'Sum total of duration of IO processed by vSAN DOM since boot. (write, client, hot)'),
            ('io_duration_seconds_total|write|compmgr|hot', 'vmware_vsan_dom_io_duration_seconds_total', ['write', 'compmgr', 'hot'], 'Sum total of duration of IO processed by vSAN DOM since boot. (write, compmgr, hot)'),
            ('io_duration_seconds_total|write|owner|hot', 'vmware_vsan_dom_io_duration_seconds_total', ['write', 'owner', 'hot'], 'Sum total of duration of IO processed by vSAN DOM since boot. (write, owner, hot)'),
            ('io_duration_seconds_total|write|ownerLeaf|hot', 'vmware_vsan_dom_io_duration_seconds_total', ['write', 'ownerLeaf', 'hot'], 'Sum total of duration of IO processed by vSAN DOM since boot. (write, ownerLeaf, hot)'),
            ('io_durationsquare_seconds_total|read|client|cold', 'vmware_vsan_dom_io_durationsquare_seconds_total', ['read', 'client', 'cold'], 'Sum total of duration^2 of IO processed by vSAN DOM since boot. (read, client, cold)'),
            ('io_durationsquare_seconds_total|read|compmgr|cold', 'vmware_vsan_dom_io_durationsquare_seconds_total', ['read', 'compmgr', 'cold'], 'Sum total of duration^2 of IO processed by vSAN DOM since boot. (read, compmgr, cold)'),
            ('io_durationsquare_seconds_total|read|owner|cold', 'vmware_vsan_dom_io_durationsquare_seconds_total', ['read', 'owner', 'cold'], 'Sum total of duration^2 of IO processed by vSAN DOM since boot. (read, owner, cold)'),
            ('io_durationsquare_seconds_total|recoveryWrite|compmgr|cold', 'vmware_vsan_dom_io_durationsquare_seconds_total', ['recoveryWrite', 'compmgr', 'cold'], 'Sum total of duration^2 of IO processed by vSAN DOM since boot. (recoveryWrite, compmgr, cold)'),
            ('io_durationsquare_seconds_total|recoveryWrite|owner|cold', 'vmware_vsan_dom_io_durationsquare_seconds_total', ['recoveryWrite', 'owner', 'cold'], 'Sum total of duration^2 of IO processed by vSAN DOM since boot. (recoveryWrite, owner, cold)'),
            ('io_durationsquare_seconds_total|resyncRead|compmgr|cold', 'vmware_vsan_dom_io_durationsquare_seconds_total', ['resyncRead', 'compmgr', 'cold'], 'Sum total of duration^2 of IO processed by vSAN DOM since boot. (resyncRead, compmgr, cold)'),
            ('io_durationsquare_seconds_total|resyncRead|owner|cold', 'vmware_vsan_dom_io_durationsquare_seconds_total', ['resyncRead', 'owner', 'cold'], 'Sum total of duration^2 of IO processed by vSAN DOM since boot. (resyncRead, owner, cold)'),
            ('io_durationsquare_seconds_total|unmap|client|cold', 'vmware_vsan_dom_io_durationsquare_seconds_total', ['unmap', 'client', 'cold'], 'Sum total of duration^2 of IO processed by vSAN DOM since boot. (unmap, client, cold)'),
            ('io_durationsquare_seconds_total|unmap|compmgr|cold', 'vmware_vsan_dom_io_durationsquare_seconds_total', ['unmap', 'compmgr', 'cold'], 'Sum total of duration^2 of IO processed by vSAN DOM since boot. (unmap, compmgr, cold)'),
            ('io_durationsquare_seconds_total|unmap|owner|cold', 'vmware_vsan_dom_io_durationsquare_seconds_total', ['unmap', 'owner', 'cold'], 'Sum total of duration^2 of IO processed by vSAN DOM since boot. (unmap, owner, cold)'),
            ('io_durationsquare_seconds_total|write|client|cold', 'vmware_vsan_dom_io_durationsquare_seconds_total', ['write', 'client', 'cold'], 'Sum total of duration^2 of IO processed by vSAN DOM since boot. (write, client, cold)'),
            ('io_durationsquare_seconds_total|write|compmgr|cold', 'vmware_vsan_dom_io_durationsquare_seconds_total', ['write', 'compmgr', 'cold'], 'Sum total of duration^2 of IO processed by vSAN DOM since boot. (write, compmgr, cold)'),
            ('io_durationsquare_seconds_total|write|owner|cold', 'vmware_vsan_dom_io_durationsquare_seconds_total', ['write', 'owner', 'cold'], 'Sum total of duration^2 of IO processed by vSAN DOM since boot. (write, owner, cold)'),
            ('io_total|read|client|hot', 'vmware_vsan_dom_io_total', ['read', 'client', 'hot'], 'Total IOs processed by vSAN DOM since boot. (read, client, hot)'),
            ('io_total|read|compmgr|hot', 'vmware_vsan_dom_io_total', ['read', 'compmgr', 'hot'], 'Total IOs processed by vSAN DOM since boot. (read, compmgr, hot)'),
            ('io_total|read|owner|hot', 'vmware_vsan_dom_io_total', ['read', 'owner', 'hot'], 'Total IOs processed by vSAN DOM since boot. (read, owner, hot)'),
            ('io_total|read|ownerLeaf|hot', 'vmware_vsan_dom_io_total', ['read', 'ownerLeaf', 'hot'], 'Total IOs processed by vSAN DOM since boot. (read, ownerLeaf, hot)'),
            ('io_total|recoveryUnmap|ownerLeaf|hot', 'vmware_vsan_dom_io_total', ['recoveryUnmap', 'ownerLeaf', 'hot'], 'Total IOs processed by vSAN DOM since boot. (recoveryUnmap, ownerLeaf, hot)'),
            ('io_total|recoveryWrite|compmgr|hot', 'vmware_vsan_dom_io_total', ['recoveryWrite', 'compmgr', 'hot'], 'Total IOs processed by vSAN DOM since boot. (recoveryWrite, compmgr, hot)'),
            ('io_total|recoveryWrite|owner|hot', 'vmware_vsan_dom_io_total', ['recoveryWrite', 'owner', 'hot'], 'Total IOs processed by vSAN DOM since boot. (recoveryWrite, owner, hot)'),
            ('io_total|recoveryWrite|ownerLeaf|hot', 'vmware_vsan_dom_io_total', ['recoveryWrite', 'ownerLeaf', 'hot'], 'Total IOs processed by vSAN DOM since boot. (recoveryWrite, ownerLeaf, hot)'),
            ('io_total|resyncRead|compmgr|hot', 'vmware_vsan_dom_io_total', ['resyncRead', 'compmgr', 'hot'], 'Total IOs processed by vSAN DOM since boot. (resyncRead, compmgr, hot)'),
            ('io_total|resyncRead|owner|hot', 'vmware_vsan_dom_io_total', ['resyncRead', 'owner', 'hot'], 'Total IOs processed by vSAN DOM since boot. (resyncRead, owner, hot)'),
            ('io_total|unmap|client|hot', 'vmware_vsan_dom_io_total', ['unmap', 'client', 'hot'], 'Total IOs processed by vSAN DOM since boot. (unmap, client, hot)'),
            ('io_total|unmap|compmgr|hot', 'vmware_vsan_dom_io_total', ['unmap', 'compmgr', 'hot'], 'Total IOs processed by vSAN DOM since boot. (unmap, compmgr, hot)'),
            ('io_total|unmap|owner|hot', 'vmware_vsan_dom_io_total', ['unmap', 'owner', 'hot'], 'Total IOs processed by vSAN DOM since boot. (unmap, owner, hot)'),
            ('io_total|unmap|ownerLeaf|hot', 'vmware_vsan_dom_io_total', ['unmap', 'ownerLeaf', 'hot'], 'Total IOs processed by vSAN DOM since boot. (unmap, ownerLeaf, hot)'),
            ('io_total|write|client|hot', 'vmware_vsan_dom_io_total', ['write', 'client', 'hot'], 'Total IOs processed by vSAN DOM since boot. (write, client, hot)'),
            ('io_total|write|compmgr|hot', 'vmware_vsan_dom_io_total', ['write', 'compmgr', 'hot'], 'Total IOs processed by vSAN DOM since boot. (write, compmgr, hot)'),
            ('io_total|write|owner|hot', 'vmware_vsan_dom_io_total', ['write', 'owner', 'hot'], 'Total IOs processed by vSAN DOM since boot. (write, owner, hot)'),
            ('io_total|write|ownerLeaf|hot', 'vmware_vsan_dom_io_total', ['write', 'ownerLeaf', 'hot'], 'Total IOs processed by vSAN DOM since boot. (write, ownerLeaf, hot)'),
            ('numoio_total|client|cold', 'vmware_vsan_dom_numoio_total', ['', 'client', 'cold'], 'Sum total of observed Outstanding IOs (aka Queue Depth) by vSAN DOM since boot. (client, cold)'),
            ('numoio_total|compmgr|cold', 'vmware_vsan_dom_numoio_total', ['', 'compmgr', 'cold'], 'Sum total of observed Outstanding IOs (aka Queue Depth) by vSAN DOM since boot. (compmgr, cold)'),
            ('numoio_total|owner|cold', 'vmware_vsan_dom_numoio_total', ['', 'owner', 'cold'], 'Sum total of observed Outstanding IOs (aka Queue Depth) by vSAN DOM since boot. (owner, cold)'),
        ],
    },
    'vmware_vsan_esa': {
        'identity': ['disk_uuid', 'splinter_db_name', 'splinter_uuid'],
        'metric_key_labels': ['disk_role', 'sink_type', 'source', 'type'],
        'properties': [],
        'objects_per_host': 9,
        'metrics': [
            ('clom_actual_bytes_moving|capacity|cold|disk', 'vmware_vsan_esa_clom_actual_bytes_moving', ['capacity', 'cold', 'disk', ''], 'Actual bytes moving on this ESXi host. (capacity, cold, disk)'),
            ('clom_actual_bytes_moving|performance|cold|disk', 'vmware_vsan_esa_clom_actual_bytes_moving', ['performance', 'cold', 'disk', ''], 'Actual bytes moving on this ESXi host. (performance, cold, disk)'),
            ('clom_actual_bytes_sched_to_move|capacity|cold|disk', 'vmware_vsan_esa_clom_actual_bytes_sched_to_move', ['capacity', 'cold', 'disk', ''], 'Acutual bytes sched to move on this ESXi host. (capacity, cold, disk)'),
            ('clom_actual_bytes_sched_to_move|performance|cold|disk', 'vmware_vsan_esa_clom_actual_bytes_sched_to_move', ['performance', 'cold', 'disk', ''], 'Acutual bytes sched to move on this ESXi host. (performance, cold, disk)'),
            ('clom_component_utilization|capacity|cold|disk', 'vmware_vsan_esa_clom_component_utilization', ['capacity', 'cold', 'disk', ''], 'Component utilization on this ESXi host. (capacity, cold, disk)'),
            ('clom_component_utilization|performance|cold|disk', 'vmware_vsan_esa_clom_component_utilization', ['performance', 'cold', 'disk', ''], 'Component utilization on this ESXi host. (performance, cold, disk)'),
            ('clom_dedup_ratio|capacity|cold|disk', 'vmware_vsan_esa_clom_dedup_ratio', ['capacity', 'cold', 'disk', ''], 'Dedup ratio on this ESXi host. (capacity, cold, disk)'),
            ('clom_dedup_ratio|performance|cold|disk', 'vmware_vsan_esa_clom_dedup_ratio', ['performance', 'cold', 'disk', ''], 'Dedup ratio on this ESXi host. (performance, cold, disk)'),
            ('clom_disk_logical_capacity_requested|capacity|cold|disk', 'vmware_vsan_esa_clom_disk_logical_capacity_requested', ['capacity', 'cold', 'disk', ''], 'Diskgroup logical capacity requested on this ESXi host. (capacity, cold, disk)'),
            ('clom_disk_logical_capacity_requested|performance|cold|disk', 'vmware_vsan_esa_clom_disk_logical_capacity_requested', ['performance', 'cold', 'disk', ''], 'Diskgroup logical capacity requested on this ESXi host. (performance, cold, disk)'),
            ('clom_disk_transient_capacity_used|capacity|cold|disk', 'vmware_vsan_esa_clom_disk_transient_capacity_used', ['capacity', 'cold', 'disk', ''], 'Disk transient capacity used on this ESXi host. (capacity, cold, disk)'),
            ('clom_disk_transient_capacity_used|performance|cold|disk', 'vmware_vsan_esa_clom_disk_transient_capacity_used', ['performance', 'cold', 'disk', ''], 'Disk transient capacity used on this ESXi host. (performance, cold, disk)'),
            ('clom_fitness|capacity|cold|disk', 'vmware_vsan_esa_clom_fitness', ['capacity', 'cold', 'disk', ''], 'Fitness on this ESXi host. (capacity, cold, disk)'),
            ('clom_fitness|performance|cold|disk', 'vmware_vsan_esa_clom_fitness', ['performance', 'cold', 'disk', ''], 'Fitness on this ESXi host. (performance, cold, disk)'),
            ('clom_fitness_disk_component_count_ratio|capacity|cold|disk', 'vmware_vsan_esa_clom_fitness_disk_component_count_ratio', ['capacity', 'cold', 'disk', ''], 'Disk component count ratio on this ESXi host. (capacity, cold, disk)'),
            ('clom_fitness_disk_component_count_ratio|performance|cold|disk', 'vmware_vsan_esa_clom_fitness_disk_component_count_ratio', ['performance', 'cold', 'disk', ''], 'Disk component count ratio on this ESXi host. (performance, cold, disk)'),
            ('clom_fitness_disk_data_component_count_ratio|capacity|cold|disk', 'vmware_vsan_esa_clom_fitness_disk_data_component_count_ratio', ['capacity', 'cold', 'disk', ''], 'Disk data component count ratio on this ESXi host. (capacity, cold, disk)'),
            ('clom_fitness_disk_data_component_count_ratio|performance|cold|disk', 'vmware_vsan_esa_clom_fitness_disk_data_component_count_ratio', ['performance', 'cold', 'disk', ''], 'Disk data component count ratio on this ESXi host. (performance, cold, disk)'),
            ('clom_fitness_diskgroup_data_component_count_ratio|capacity|cold|disk', 'vmware_vsan_esa_clom_fitness_diskgroup_data_component_count_ratio', ['capacity', 'cold', 'disk', ''], 'Diskgroup data component count ratio on this ESXi host. (capacity, cold, disk)'),
            ('clom_fitness_diskgroup_data_component_count_ratio|performance|cold|disk', 'vmware_vsan_esa_clom_fitness_diskgroup_data_component_count_ratio', ['performance', 'cold', 'disk', ''], 'Diskgroup data component count ratio on this ESXi host. (performance, cold, disk)'),
            ('clom_fitness_max_actual_reserved_space_utilization|capacity|hot|disk', 'vmware_vsan_esa_clom_fitness_max_actual_reserved_space_utilization', ['capacity', 'hot', 'disk', ''], 'Max actual reserved space utilization on this ESXi host. (capacity, hot, disk)'),
            ('clom_fitness_max_actual_reserved_space_utilization|performance|hot|disk', 'vmware_vsan_esa_clom_fitness_max_actual_reserved_space_utilization', ['performance', 'hot', 'disk', ''], 'Max actual reserved space utilization on this ESXi host. (performance, hot, disk)'),
            ('clom_fitness_node_component_count_ratio|cold|host', 'vmware_vsan_esa_clom_fitness_node_component_count_ratio', ['', 'cold', 'host', ''], 'Node component count ratio on this ESXi host. (cold, host)'),
            ('clom_fitness_node_data_component_count_ratio|cold|host', 'vmware_vsan_esa_clom_fitness_node_data_component_count_ratio', ['', 'cold', 'host', ''], 'Node data component count ratio on this ESXi host. (cold, host)'),
            ('clom_fitness_read_cache_reservation_utilization|capacity|cold|disk', 'vmware_vsan_esa_clom_fitness_read_cache_reservation_utilization', ['capacity', 'cold', 'disk', ''], 'Read cache reservation utilization on this ESXi host. (capacity, cold, disk)'),
            ('clom_fitness_read_cache_reservation_utilization|performance|cold|disk', 'vmware_vsan_esa_clom_fitness_read_cache_reservation_utilization', ['performance', 'cold', 'disk', ''], 'Read cache reservation utilization on this ESXi host. (performance, cold, disk)'),
            ('clom_fitness_resource_stddev_change|capacity|cold|disk', 'vmware_vsan_esa_clom_fitness_resource_stddev_change', ['capacity', 'cold', 'disk', ''], 'Resource standard deviation change on this ESXi host. (capacity, cold, disk)'),
            ('clom_fitness_resource_stddev_change|performance|cold|disk', 'vmware_vsan_esa_clom_fitness_resource_stddev_change', ['performance', 'cold', 'disk', ''], 'Resource standard deviation change on this ESXi host. (performance, cold, disk)'),
            ('clom_fitness_unreserved_address_space_utilization|capacity|hot|disk', 'vmware_vsan_esa_clom_fitness_unreserved_address_space_utilization', ['capacity', 'hot', 'disk', ''], 'Unreserved address space utilization on this ESXi host. (capacity, hot, disk)'),
            ('clom_fitness_unreserved_address_space_utilization|performance|hot|disk', 'vmware_vsan_esa_clom_fitness_unreserved_address_space_utilization', ['performance', 'hot', 'disk', ''], 'Unreserved address space utilization on this ESXi host. (performance, hot, disk)'),
            ('clom_fitness_version_weight|capacity|cold|disk', 'vmware_vsan_esa_clom_fitness_version_weight', ['capacity', 'cold', 'disk', ''], 'Version weight on this ESXi host. (capacity, cold, disk)'),
            ('clom_fitness_version_weight|performance|cold|disk', 'vmware_vsan_esa_clom_fitness_version_weight', ['performance', 'cold', 'disk', ''], 'Version weight on this ESXi host. (performance, cold, disk)'),
            ('clom_logical_fullness|capacity|cold|disk', 'vmware_vsan_esa_clom_logical_fullness', ['capacity', 'cold', 'disk', ''], 'Logical fullness on this ESXi host. (capacity, cold, disk)'),
            ('clom_logical_fullness|performance|cold|disk', 'vmware_vsan_esa_clom_logical_fullness', ['performance', 'cold', 'disk', ''], 'Logical fullness on this ESXi host. (performance, cold, disk)'),
            ('clom_num_components|capacity|cold|disk', 'vmware_vsan_esa_clom_num_components', ['capacity', 'cold', 'disk', ''], 'Number of components on this ESXi host. (capacity, cold, disk)'),
            ('clom_num_components|performance|cold|disk', 'vmware_vsan_esa_clom_num_components', ['performance', 'cold', 'disk', ''], 'Number of components on this ESXi host. (performance, cold, disk)'),
            ('clom_pending_deletes|capacity|cold|disk', 'vmware_vsan_esa_clom_pending_deletes', ['capacity', 'cold', 'disk', ''], 'Pending deletes on this ESXi host. (capacity, cold, disk)'),
            ('clom_pending_deletes|performance|cold|disk', 'vmware_vsan_esa_clom_pending_deletes', ['performance', 'cold', 'disk', ''], 'Pending deletes on this ESXi host. (performance, cold, disk)'),
            ('clom_pending_writes|capacity|cold|disk', 'vmware_vsan_esa_clom_pending_writes', ['capacity', 'cold', 'disk', ''], 'Pending writes on this ESXi host. (capacity, cold, disk)'),
            ('clom_pending_writes|performance|cold|disk', 'vmware_vsan_esa_clom_pending_writes', ['performance', 'cold', 'disk', ''], 'Pending writes on this ESXi host. (performance, cold, disk)'),
            ('clom_physical_disk_capacity_reserved|capacity|cold|disk', 'vmware_vsan_esa_clom_physical_disk_capacity_reserved', ['capacity', 'cold', 'disk', ''], 'Physical disk capacity reserved on this ESXi host. (capacity, cold, disk)'),
            ('clom_physical_disk_capacity_reserved|performance|cold|disk', 'vmware_vsan_esa_clom_physical_disk_capacity_reserved', ['performance', 'cold', 'disk', ''], 'Physical disk capacity reserved on this ESXi host. (performance, cold, disk)'),
            ('clom_physical_free_space|capacity|hot|disk', 'vmware_vsan_esa_clom_physical_free_space', ['capacity', 'hot', 'disk', ''], 'Physical free space on this ESXi host. (capacity, hot, disk)'),
            ('clom_physical_free_space|performance|hot|disk', 'vmware_vsan_esa_clom_physical_free_space', ['performance', 'hot', 'disk', ''], 'Physical free space on this ESXi host. (performance, hot, disk)'),
            ('clom_physical_fullness|capacity|cold|disk', 'vmware_vsan_esa_clom_physical_fullness', ['capacity', 'cold', 'disk', ''], 'Physical fullness on this ESXi host. (capacity, cold, disk)'),
            ('clom_physical_fullness|performance|cold|disk', 'vmware_vsan_esa_clom_physical_fullness', ['performance', 'cold', 'disk', ''], 'Physical fullness on this ESXi host. (performance, cold, disk)'),
            ('clom_queued_bytes|cold|host|change', 'vmware_vsan_esa_clom_queued_bytes', ['', 'cold', 'host', 'change'], 'Queued bytes on this ESXi host. (cold, host, change)'),
            ('clom_queued_bytes|cold|host|concat', 'vmware_vsan_esa_clom_queued_bytes', ['', 'cold', 'host', 'concat'], 'Queued bytes on this ESXi host. (cold, host, concat)'),
            ('clom_queued_bytes|cold|host|consolidate', 'vmware_vsan_esa_clom_queued_bytes', ['', 'cold', 'host', 'consolidate'], 'Queued bytes on this ESXi host. (cold, host, consolidate)'),
            ('clom_queued_bytes|cold|host|decom', 'vmware_vsan_esa_clom_queued_bytes', ['', 'cold', 'host', 'decom'], 'Queued bytes on this ESXi host. (cold, host, decom)'),
            ('clom_queued_bytes|cold|host|fixcompliance', 'vmware_vsan_esa_clom_queued_bytes', ['', 'cold', 'host', 'fixcompliance'], 'Queued bytes on this ESXi host. (cold, host, fixcompliance)'),
            ('clom_queued_bytes|cold|host|move', 'vmware_vsan_esa_clom_queued_bytes', ['', 'cold', 'host', 'move'], 'Queued bytes on this ESXi host. (cold, host, move)'),
            ('clom_queued_bytes|cold|host|rebalance', 'vmware_vsan_esa_clom_queued_bytes', ['', 'cold', 'host', 'rebalance'], 'Queued bytes on this ESXi host. (cold, host, rebalance)'),
            ('clom_queued_bytes|cold|host|repair', 'vmware_vsan_esa_clom_queued_bytes', ['', 'cold', 'host', 'repair'], 'Queued bytes on this ESXi host. (cold, host, repair)'),
            ('clom_queued_bytes|cold|host|total', 'vmware_vsan_esa_clom_queued_bytes', ['', 'cold', 'host', 'total'], 'Queued bytes on this ESXi host. (cold, host, total)'),
            ('clom_queued_objects|cold|host|change', 'vmware_vsan_esa_clom_queued_objects', ['', 'cold', 'host', 'change'], 'Queued objects on this ESXi host. (cold, host, change)'),
            ('clom_queued_objects|cold|host|concat', 'vmware_vsan_esa_clom_queued_objects', ['', 'cold', 'host', 'concat'], 'Queued objects on this ESXi host. (cold, host, concat)'),
            ('clom_queued_objects|cold|host|consolidate', 'vmware_vsan_esa_clom_queued_objects', ['', 'cold', 'host', 'consolidate'], 'Queued objects on this ESXi host. (cold, host, consolidate)'),
            ('clom_queued_objects|cold|host|decom', 'vmware_vsan_esa_clom_queued_objects', ['', 'cold', 'host', 'decom'], 'Queued objects on this ESXi host. (cold, host, decom)'),
            ('clom_queued_objects|cold|host|fixcompliance', 'vmware_vsan_esa_clom_queued_objects', ['', 'cold', 'host', 'fixcompliance'], 'Queued objects on this ESXi host. (cold, host, fixcompliance)'),
            ('clom_queued_objects|cold|host|move', 'vmware_vsan_esa_clom_queued_objects', ['', 'cold', 'host', 'move'], 'Queued objects on this ESXi host. (cold, host, move)'),
            ('clom_queued_objects|cold|host|rebalance', 'vmware_vsan_esa_clom_queued_objects', ['', 'cold', 'host', 'rebalance'], 'Queued objects on this ESXi host. (cold, host, rebalance)'),
            ('clom_queued_objects|cold|host|repair', 'vmware_vsan_esa_clom_queued_objects', ['', 'cold', 'host', 'repair'], 'Queued objects on this ESXi host. (cold, host, repair)'),
            ('clom_queued_objects|cold|host|total', 'vmware_vsan_esa_clom_queued_objects', ['', 'cold', 'host', 'total'], 'Queued objects on this ESXi host. (cold, host, total)'),
            ('clom_rebalancing_fullness|capacity|hot|disk', 'vmware_vsan_esa_clom_rebalancing_fullness', ['capacity', 'hot', 'disk', ''], 'Rebalancing fullness on this ESXi host. (capacity, hot, disk)'),
            ('clom_rebalancing_fullness|performance|hot|disk', 'vmware_vsan_esa_clom_rebalancing_fullness', ['performance', 'hot', 'disk', ''], 'Rebalancing fullness on this ESXi host. (performance, hot, disk)'),
            ('clom_rebalancing_status|capacity|cold|disk', 'vmware_vsan_esa_clom_rebalancing_status', ['capacity', 'cold', 'disk', ''], 'Rebalancing status on this ESXi host. (capacity, cold, disk)'),
            ('clom_rebalancing_status|performance|cold|disk', 'vmware_vsan_esa_clom_rebalancing_status', ['performance', 'cold', 'disk', ''], 'Rebalancing status on this ESXi host. (performance, cold, disk)'),
            ('clom_total_queued_work_items|hot|host', 'vmware_vsan_esa_clom_total_queued_work_items', ['', 'hot', 'host', ''], 'Total queued work items on this ESXi host. (hot, host)'),
            ('clom_work_item_success_count|cold|host|change', 'vmware_vsan_esa_clom_work_item_success_count', ['', 'cold', 'host', 'change'], 'Success count on this ESXi host. (cold, host, change)'),
            ('clom_work_item_success_count|cold|host|change_pending', 'vmware_vsan_esa_clom_work_item_success_count', ['', 'cold', 'host', 'change_pending'], 'Success count on this ESXi host. (cold, host, change_pending)'),
            ('clom_work_item_success_count|cold|host|cleanup', 'vmware_vsan_esa_clom_work_item_success_count', ['', 'cold', 'host', 'cleanup'], 'Success count on this ESXi host. (cold, host, cleanup)'),
            ('clom_work_item_success_count|cold|host|compliance', 'vmware_vsan_esa_clom_work_item_success_count', ['', 'cold', 'host', 'compliance'], 'Success count on this ESXi host. (cold, host, compliance)'),
            ('clom_work_item_success_count|cold|host|concat', 'vmware_vsan_esa_clom_work_item_success_count', ['', 'cold', 'host', 'concat'], 'Success count on this ESXi host. (cold, host, concat)'),
            ('clom_work_item_success_count|cold|host|decom', 'vmware_vsan_esa_clom_work_item_success_count', ['', 'cold', 'host', 'decom'], 'Success count on this ESXi host. (cold, host, decom)'),
            ('clom_work_item_success_count|cold|host|delta_decom', 'vmware_vsan_esa_clom_work_item_success_count', ['', 'cold', 'host', 'delta_decom'], 'Success count on this ESXi host. (cold, host, delta_decom)'),
            ('clom_work_item_success_count|cold|host|force_repair', 'vmware_vsan_esa_clom_work_item_success_count', ['', 'cold', 'host', 'force_repair'], 'Success count on this ESXi host. (cold, host, force_repair)'),
            ('clom_work_item_success_count|cold|host|proactive_rebalance', 'vmware_vsan_esa_clom_work_item_success_count', ['', 'cold', 'host', 'proactive_rebalance'], 'Success count on this ESXi host. (cold, host, proactive_rebalance)'),
            ('clom_work_item_success_count|cold|host|reactive_rebalance', 'vmware_vsan_esa_clom_work_item_success_count', ['', 'cold', 'host', 'reactive_rebalance'], 'Success count on this ESXi host. (cold, host, reactive_rebalance)'),
            ('clom_work_item_success_count|cold|host|repair', 'vmware_vsan_esa_clom_work_item_success_count', ['', 'cold', 'host', 'repair'], 'Success count on this ESXi host. (cold, host, repair)'),
            ('clom_work_item_success_count|cold|host|thickplacement', 'vmware_vsan_esa_clom_work_item_success_count', ['', 'cold', 'host', 'thickplacement'], 'Success count on this ESXi host. (cold, host, thickplacement)'),
            ('clom_work_item_success_count|cold|host|thinplacement', 'vmware_vsan_esa_clom_work_item_success_count', ['', 'cold', 'host', 'thinplacement'], 'Success count on this ESXi host. (cold, host, thinplacement)'),
            ('clom_work_item_success_count|cold|host|total', 'vmware_vsan_esa_clom_work_item_success_count', ['', 'cold', 'host', 'total'], 'Success count on this ESXi host. (cold, host, total)'),
            ('clom_work_item_success_count|cold|host|unplanned_delta', 'vmware_vsan_esa_clom_work_item_success_count', ['', 'cold', 'host', 'unplanned_delta'], 'Success count on this ESXi host. (cold, host, unplanned_delta)'),
            ('disk_congestion_be_data|hot|capacity', 'vmware_vsan_esa_disk_congestion_be_data', ['', 'hot', '', 'capacity'], 'vSAN2 ESA disk Lsom2 congestion block engine data. (hot, capacity)'),
            ('disk_congestion_be_data|hot|perf', 'vmware_vsan_esa_disk_congestion_be_data', ['', 'hot', '', 'perf'], 'vSAN2 ESA disk Lsom2 congestion block engine data. (hot, perf)'),
            ('disk_congestion_be_data_allocator|hot|capacity', 'vmware_vsan_esa_disk_congestion_be_data_allocator', ['', 'hot', '', 'capacity'], 'vSAN2 ESA disk Lsom2 congestion block engine data allocator. (hot, capacity)'),
            ('disk_congestion_be_data_allocator|hot|perf', 'vmware_vsan_esa_disk_congestion_be_data_allocator', ['', 'hot', '', 'perf'], 'vSAN2 ESA disk Lsom2 congestion block engine data allocator. (hot, perf)'),
            ('disk_congestion_be_policy_allocator|hot|capacity', 'vmware_vsan_esa_disk_congestion_be_policy_allocator', ['', 'hot', '', 'capacity'], 'vSAN2 ESA disk Lsom2 congestion block engine policy allocator. (hot, capacity)'),
            ('disk_congestion_be_policy_allocator|hot|perf', 'vmware_vsan_esa_disk_congestion_be_policy_allocator', ['', 'hot', '', 'perf'], 'vSAN2 ESA disk Lsom2 congestion block engine policy allocator. (hot, perf)'),
            ('disk_congestion_global|hot|capacity', 'vmware_vsan_esa_disk_congestion_global', ['', 'hot', '', 'capacity'], 'vSAN2 ESA disk Lsom2 global congress. (hot, capacity)'),
            ('disk_congestion_global|hot|perf', 'vmware_vsan_esa_disk_congestion_global', ['', 'hot', '', 'perf'], 'vSAN2 ESA disk Lsom2 global congress. (hot, perf)'),
            ('disk_congestion_spl_allocator|hot|capacity', 'vmware_vsan_esa_disk_congestion_spl_allocator', ['', 'hot', '', 'capacity'], 'vSAN2 ESA disk Lsom2 congestion for splinter logical table allocator. (hot, capacity)'),
            ('disk_congestion_spl_allocator|hot|perf', 'vmware_vsan_esa_disk_congestion_spl_allocator', ['', 'hot', '', 'perf'], 'vSAN2 ESA disk Lsom2 congestion for splinter logical table allocator. (hot, perf)'),
            ('disk_congestion_spl_attr|hot|capacity', 'vmware_vsan_esa_disk_congestion_spl_attr', ['', 'hot', '', 'capacity'], 'vSAN2 ESA disk Lsom2 congestion for splinter logical table attributes. (hot, capacity)'),
            ('disk_congestion_spl_attr|hot|perf', 'vmware_vsan_esa_disk_congestion_spl_attr', ['', 'hot', '', 'perf'], 'vSAN2 ESA disk Lsom2 congestion for splinter logical table attributes. (hot, perf)'),
            ('disk_congestion_spl_logical|hot|capacity', 'vmware_vsan_esa_disk_congestion_spl_logical', ['', 'hot', '', 'capacity'], 'vSAN2 ESA disk Lsom2 congestion for splinter logical table logical. (hot, capacity)'),
            ('disk_congestion_spl_logical|hot|perf', 'vmware_vsan_esa_disk_congestion_spl_logical', ['', 'hot', '', 'perf'], 'vSAN2 ESA disk Lsom2 congestion for splinter logical table logical. (hot, perf)'),
            ('disk_congestion_spl_prepare|hot|capacity', 'vmware_vsan_esa_disk_congestion_spl_prepare', ['', 'hot', '', 'capacity'], 'vSAN2 ESA disk Lsom2 congestion for splinter logical table prepare. (hot, capacity)'),
            ('disk_congestion_spl_prepare|hot|perf', 'vmware_vsan_esa_disk_congestion_spl_prepare', ['', 'hot', '', 'perf'], 'vSAN2 ESA disk Lsom2 congestion for splinter logical table prepare. (hot, perf)'),
            ('disk_congestion_wal|hot|capacity', 'vmware_vsan_esa_disk_congestion_wal', ['', 'hot', '', 'capacity'], 'vSAN2 ESA disk Lsom2 congestion write after log. (hot, capacity)'),
            ('disk_congestion_wal|hot|perf', 'vmware_vsan_esa_disk_congestion_wal', ['', 'hot', '', 'perf'], 'vSAN2 ESA disk Lsom2 congestion write after log. (hot, perf)'),
            ('disk_congestion_wal_allocator|hot|capacity', 'vmware_vsan_esa_disk_congestion_wal_allocator', ['', 'hot', '', 'capacity'], 'vSAN2 ESA disk Lsom2 congestion write after log allocator. (hot, capacity)'),
            ('disk_congestion_wal_allocator|hot|perf', 'vmware_vsan_esa_disk_congestion_wal_allocator', ['', 'hot', '', 'perf'], 'vSAN2 ESA disk Lsom2 congestion write after log allocator. (hot, perf)'),
            ('disk_dev_read_time_total|hot|capacity', 'vmware_vsan_esa_disk_dev_read_time_total', ['', 'hot', '', 'capacity'], 'vSAN ESA disk device total read time. (hot, capacity)'),
            ('disk_dev_read_time_total|hot|perf', 'vmware_vsan_esa_disk_dev_read_time_total', ['', 'hot', '', 'perf'], 'vSAN ESA disk device total read time. (hot, perf)'),
            ('disk_dev_write_time_total|hot|capacity', 'vmware_vsan_esa_disk_dev_write_time_total', ['', 'hot', '', 'capacity'], 'vSAN ESA disk device total write time. (hot, capacity)'),
            ('disk_dev_write_time_total|hot|perf', 'vmware_vsan_esa_disk_dev_write_time_total', ['', 'hot', '', 'perf'], 'vSAN ESA disk device total write time. (hot, perf)'),
            ('disk_io_bytes|hot|capacity', 'vmware_vsan_esa_disk_io_bytes', ['', 'hot', '', 'capacity'], 'Total IO bytes of vSAN2 ESA disk Lsom2. (hot, capacity)'),
            ('disk_io_bytes|hot|perf', 'vmware_vsan_esa_disk_io_bytes', ['', 'hot', '', 'perf'], 'Total IO bytes of vSAN2 ESA disk Lsom2. (hot, perf)'),
            ('disk_io_count|hot|capacity', 'vmware_vsan_esa_disk_io_count', ['', 'hot', '', 'capacity'], 'Total IO count of vSAN2 ESA disk Lsom2. (hot, capacity)'),
            ('disk_io_count|hot|perf', 'vmware_vsan_esa_disk_io_count', ['', 'hot', '', 'perf'], 'Total IO count of vSAN2 ESA disk Lsom2. (hot, perf)'),
            ('disk_num_allocated_blocks|hot', 'vmware_vsan_esa_disk_num_allocated_blocks', ['', 'hot', '', ''], 'Number of allocated blocks for vSAN2 ESA disk Lsom2. (hot)'),
            ('disk_num_total_blocks|hot', 'vmware_vsan_esa_disk_num_total_blocks', ['', 'hot', '', ''], 'Total allocated blocks for vSAN2 ESA disk Lsom2. (hot)'),
            ('disk_pending_free_blocks|cold', 'vmware_vsan_esa_disk_pending_free_blocks', ['', 'cold', '', ''], 'Number of pending free blocks for vSAN2 ESA disk Lsom2. (cold)'),
            ('disk_read_io_bytes|cold|capacity', 'vmware_vsan_esa_disk_read_io_bytes', ['', 'cold', '', 'capacity'], 'Read IO bytes of vSAN2 ESA disk Lsom2. (cold, capacity)'),
            ('disk_read_io_bytes|cold|perf', 'vmware_vsan_esa_disk_read_io_bytes', ['', 'cold', '', 'perf'], 'Read IO bytes of vSAN2 ESA disk Lsom2. (cold, perf)'),
            ('disk_read_io_count|cold|capacity', 'vmware_vsan_esa_disk_read_io_count', ['', 'cold', '', 'capacity'], 'Read IO count of vSAN2 ESA disk Lsom2. (cold, capacity)'),
            ('disk_read_io_count|cold|perf', 'vmware_vsan_esa_disk_read_io_count', ['', 'cold', '', 'perf'], 'Read IO count of vSAN2 ESA disk Lsom2. (cold, perf)'),
            ('disk_read_time_max|hot|capacity', 'vmware_vsan_esa_disk_read_time_max', ['', 'hot', '', 'capacity'], 'Max read time of vSAN2 ESA disk Lsom2. (hot, capacity)'),
            ('disk_read_time_max|hot|perf', 'vmware_vsan_esa_disk_read_time_max', ['', 'hot', '', 'perf'], 'Max read time of vSAN2 ESA disk Lsom2. (hot, perf)'),
            ('disk_read_time_min|cold|capacity', 'vmware_vsan_esa_disk_read_time_min', ['', 'cold', '', 'capacity'], 'Min read time of vSAN2 ESA disk Lsom2. (cold, capacity)'),
            ('disk_read_time_min|cold|perf', 'vmware_vsan_esa_disk_read_time_min', ['', 'cold', '', 'perf'], 'Min read time of vSAN2 ESA disk Lsom2. (cold, perf)'),
            ('disk_read_time_sum|hot|capacity', 'vmware_vsan_esa_disk_read_time_sum', ['', 'hot', '', 'capacity'], 'Total read time of vSAN2 ESA disk Lsom2. (hot, capacity)'),
            ('disk_read_time_sum|hot|perf', 'vmware_vsan_esa_disk_read_time_sum', ['', 'hot', '', 'perf'], 'Total read time of vSAN2 ESA disk Lsom2. (hot, perf)'),
            ('disk_write_io_bytes|cold|capacity', 'vmware_vsan_esa_disk_write_io_bytes', ['', 'cold', '', 'capacity'], 'Write IO bytes of vSAN2 ESA disk Lsom2. (cold, capacity)'),
            ('disk_write_io_bytes|cold|perf', 'vmware_vsan_esa_disk_write_io_bytes', ['', 'cold', '', 'perf'], 'Write IO bytes of vSAN2 ESA disk Lsom2. (cold, perf)'),
            ('disk_write_io_count|cold|capacity', 'vmware_vsan_esa_disk_write_io_count', ['', 'cold', '', 'capacity'], 'Write IO count of vSAN2 ESA disk Lsom2. (cold, capacity)'),
            ('disk_write_io_count|cold|perf', 'vmware_vsan_esa_disk_write_io_count', ['', 'cold', '', 'perf'], 'Write IO count of vSAN2 ESA disk Lsom2. (cold, perf)'),
            ('disk_write_time_max|hot|capacity', 'vmware_vsan_esa_disk_write_time_max', ['', 'hot', '', 'capacity'], 'Max write time of vSAN2 ESA disk Lsom2. (hot, capacity)'),
            ('disk_write_time_max|hot|perf', 'vmware_vsan_esa_disk_write_time_max', ['', 'hot', '', 'perf'], 'Max write time of vSAN2 ESA disk Lsom2. (hot, perf)'),
            ('disk_write_time_min|cold|capacity', 'vmware_vsan_esa_disk_write_time_min', ['', 'cold', '', 'capacity'], 'Min write time of vSAN2 ESA disk Lsom2. (cold, capacity)'),
            ('disk_write_time_min|cold|perf', 'vmware_vsan_esa_disk_write_time_min', ['', 'cold', '', 'perf'], 'Min write time of vSAN2 ESA disk Lsom2. (cold, perf)'),
            ('disk_write_time_sum|hot|capacity', 'vmware_vsan_esa_disk_write_time_sum', ['', 'hot', '', 'capacity'], 'Total write time of vSAN2 ESA disk Lsom2. (hot, capacity)'),
            ('disk_write_time_sum|hot|perf', 'vmware_vsan_esa_disk_write_time_sum', ['', 'hot', '', 'perf'], 'Total write time of vSAN2 ESA disk Lsom2. (hot, perf)'),
            ('num_max_components|cold', 'vmware_vsan_esa_num_max_components', ['', 'cold', '', ''], 'vSAN ESA number of max components. (cold)'),
            ('splinter_cache_hits_branch|hot', 'vmware_vsan_esa_splinter_cache_hits_branch', ['', 'hot', '', ''], 'vSAN ESA LSOM2 splinter cache hits branch. (hot)'),
            ('splinter_cache_hits_branch_range|hot', 'vmware_vsan_esa_splinter_cache_hits_branch_range', ['', 'hot', '', ''], 'vSAN ESA LSOM2 splinter cache hits branch range. (hot)'),
            ('splinter_cache_hits_filter|hot', 'vmware_vsan_esa_splinter_cache_hits_filter', ['', 'hot', '', ''], 'vSAN ESA LSOM2 splinter cache hits filter. (hot)'),
            ('splinter_cache_hits_misc|hot', 'vmware_vsan_esa_splinter_cache_hits_misc', ['', 'hot', '', ''], 'vSAN ESA LSOM2 splinter cache hits misc. (hot)'),
            ('splinter_cache_misses_branch|hot', 'vmware_vsan_esa_splinter_cache_misses_branch', ['', 'hot', '', ''], 'vSAN ESA LSOM2 splinter cache misses branch. (hot)'),
            ('splinter_cache_misses_branch_range|hot', 'vmware_vsan_esa_splinter_cache_misses_branch_range', ['', 'hot', '', ''], 'vSAN ESA LSOM2 splinter cache misses branch range. (hot)'),
            ('splinter_cache_misses_filter|hot', 'vmware_vsan_esa_splinter_cache_misses_filter', ['', 'hot', '', ''], 'vSAN ESA LSOM2 splinter cache misses filter. (hot)'),
            ('splinter_cache_misses_misc|hot', 'vmware_vsan_esa_splinter_cache_misses_misc', ['', 'hot', '', ''], 'vSAN ESA LSOM2 splinter cache misses misc. (hot)'),
            ('splinter_checkpoint_write_latency_max|hot', 'vmware_vsan_esa_splinter_checkpoint_write_latency_max', ['', 'hot', '', ''], 'vSAN ESA splinter checkpoint max write latency. (hot)'),
            ('splinter_current_outstanding_tasks|cold', 'vmware_vsan_esa_splinter_current_outstanding_tasks', ['', 'cold', '', ''], 'vmware vSAN splinter current outstanding tasks. (cold)'),
            ('splinter_max_outstanding_tasks|hot', 'vmware_vsan_esa_splinter_max_outstanding_tasks', ['', 'hot', '', ''], 'vmware vSAN splinter max outstanding tasks. (hot)'),
            ('splinter_memtable_pending_tasks|cold', 'vmware_vsan_esa_splinter_memtable_pending_tasks', ['', 'cold', '', ''], 'vmware vSAN splinter memtable pending tasks. (cold)'),
            ('splinter_total_tasks|hot', 'vmware_vsan_esa_splinter_total_tasks', ['', 'hot', '', ''], 'vSAN ESA LSOM2 splinter total tasks numbers. (hot)'),
            ('splinter_total_tasks_latency_max_ns|hot', 'vmware_vsan_esa_splinter_total_tasks_latency_max_ns', ['', 'hot', '', ''], 'vSAN ESA LSOM2 splinter total task queue runtime latency max in nano seconds. (hot)'),
            ('splinter_total_tasks_latency_ns|hot', 'vmware_vsan_esa_splinter_total_tasks_latency_ns', ['', 'hot', '', ''], 'vSAN ESA LSOM2 splinter total tasks latency in nano seconds. (hot)'),
            ('splinter_total_tasks_runtime_max_ns|hot', 'vmware_vsan_esa_splinter_total_tasks_runtime_max_ns', ['', 'hot', '', ''], 'vSAN ESA LSOM2 splinter total task queue runtime max in nano seconds. (hot)'),
            ('zdom_all_op_cache_miss|cold', 'vmware_vsan_esa_zdom_all_op_cache_miss', ['', 'cold', '', ''], 'Total cache missed. (cold)'),
            ('zdom_all_op_logical_tree_cache_miss|cold', 'vmware_vsan_esa_zdom_all_op_logical_tree_cache_miss', ['', 'cold', '', ''], 'Total logical tree cache missed. (cold)'),
            ('zdom_all_op_middle_tree_cache_miss|cold', 'vmware_vsan_esa_zdom_all_op_middle_tree_cache_miss', ['', 'cold', '', ''], 'Total middle tree cache missed. (cold)'),
            ('zdom_all_op_snap_tree_cache_miss|cold', 'vmware_vsan_esa_zdom_all_op_snap_tree_cache_miss', ['', 'cold', '', ''], 'Total snap tree cache missed. (cold)'),
            ('zdom_bank_flush_count|cold', 'vmware_vsan_esa_zdom_bank_flush_count', ['', 'cold', '', ''], 'Total count of zDOM bank flush. (cold)'),
            ('zdom_bank_flush_latency_us|cold', 'vmware_vsan_esa_zdom_bank_flush_latency_us', ['', 'cold', '', ''], 'Bank flush latency sum. (cold)'),
            ('zdom_data_checksum_mismatch|cold', 'vmware_vsan_esa_zdom_data_checksum_mismatch', ['', 'cold', '', ''], 'Number of data checksum mismatch being observed. (cold)'),
            ('zdom_seg_clean_read_bytes|cold', 'vmware_vsan_esa_zdom_seg_clean_read_bytes', ['', 'cold', '', ''], 'Segment cleaning read in bytes. (cold)'),
            ('zdom_seg_clean_unmap_bytes|cold', 'vmware_vsan_esa_zdom_seg_clean_unmap_bytes', ['', 'cold', '', ''], 'Segment cleaning unmap in bytes. (cold)'),
            ('zdom_seg_clean_write_bytes|cold', 'vmware_vsan_esa_zdom_seg_clean_write_bytes', ['', 'cold', '', ''], 'Segment cleaning write in bytes. (cold)'),
        ],
    },
    'vmware_vsan_heap': {
        'identity': ['heap_id'],
        'metric_key_labels': [],
        'properties': ['heap_name', 'sink_type', 'subsystem'],
        'objects_per_host': 31,
        'metrics': [
            ('usage_current_allocation', 'vmware_vsan_heap_usage_current_allocation', [], ''),
            ('usage_current_available', 'vmware_vsan_heap_usage_current_available', [], ''),
            ('usage_current_size', 'vmware_vsan_heap_usage_current_size', [], ''),
            ('usage_failed_count', 'vmware_vsan_heap_usage_failed_count', [], ''),
            ('usage_max_size', 'vmware_vsan_heap_usage_max_size', [], ''),
        ],
    },
    'vmware_vsan_memory': {
        'identity': [],
        'metric_key_labels': ['memory_type'],
        'properties': ['sink_type'],
        'objects_per_host': 1,
        'metrics': [
            ('usage_bytes|clomdConsumedSize', 'vmware_vsan_memory_usage_bytes', ['clomdConsumedSize'], 'The usage of vSAN memory. (clomdConsumedSize)'),
            ('usage_bytes|clomdMemAllocMax', 'vmware_vsan_memory_usage_bytes', ['clomdMemAllocMax'], 'The usage of vSAN memory. (clomdMemAllocMax)'),
            ('usage_bytes|clomdMemAllocMin', 'vmware_vsan_memory_usage_bytes', ['clomdMemAllocMin'], 'The usage of vSAN memory. (clomdMemAllocMin)'),
            ('usage_bytes|clomdReservedSize', 'vmware_vsan_memory_usage_bytes', ['clomdReservedSize'], 'The usage of vSAN memory. (clomdReservedSize)'),
            ('usage_bytes|cmmdsTimeMachineConsumedSize', 'vmware_vsan_memory_usage_bytes', ['cmmdsTimeMachineConsumedSize'], 'The usage of vSAN memory. (cmmdsTimeMachineConsumedSize)'),
            ('usage_bytes|cmmdsTimeMachineMemAllocMax', 'vmware_vsan_memory_usage_bytes', ['cmmdsTimeMachineMemAllocMax'], 'The usage of vSAN memory. (cmmdsTimeMachineMemAllocMax)'),
            ('usage_bytes|cmmdsTimeMachineMemAllocMin', 'vmware_vsan_memory_usage_bytes', ['cmmdsTimeMachineMemAllocMin'], 'The usage of vSAN memory. (cmmdsTimeMachineMemAllocMin)'),
            ('usage_bytes|cmmdsTimeMachineReservedSize', 'vmware_vsan_memory_usage_bytes', ['cmmdsTimeMachineReservedSize'], 'The usage of vSAN memory. (cmmdsTimeMachineReservedSize)'),
            ('usage_bytes|cmmdsdConsumedSize', 'vmware_vsan_memory_usage_bytes', ['cmmdsdConsumedSize'], 'The usage of vSAN memory. (cmmdsdConsumedSize)'),
            ('usage_bytes|cmmdsdMemAllocMax', 'vmware_vsan_memory_usage_bytes', ['cmmdsdMemAllocMax'], 'The usage of vSAN memory. (cmmdsdMemAllocMax)'),
            ('usage_bytes|cmmdsdMemAllocMin', 'vmware_vsan_memory_usage_bytes', ['cmmdsdMemAllocMin'], 'The usage of vSAN memory. (cmmdsdMemAllocMin)'),
            ('usage_bytes|cmmdsdReservedSize', 'vmware_vsan_memory_usage_bytes', ['cmmdsdReservedSize'], 'The usage of vSAN memory. (cmmdsdReservedSize)'),
            ('usage_bytes|epdConsumedSize', 'vmware_vsan_memory_usage_bytes', ['epdConsumedSize'], 'The usage of vSAN memory. (epdConsumedSize)'),
            ('usage_bytes|epdMemAllocMax', 'vmware_vsan_memory_usage_bytes', ['epdMemAllocMax'], 'The usage of vSAN memory. (epdMemAllocMax)'),
            ('usage_bytes|epdMemAllocMin', 'vmware_vsan_memory_usage_bytes', ['epdMemAllocMin'], 'The usage of vSAN memory. (epdMemAllocMin)'),
            ('usage_bytes|epdReservedSize', 'vmware_vsan_memory_usage_bytes', ['epdReservedSize'], 'The usage of vSAN memory. (epdReservedSize)'),
            ('usage_bytes|kernelConsumedSize', 'vmware_vsan_memory_usage_bytes', ['kernelConsumedSize'], 'The usage of vSAN memory. (kernelConsumedSize)'),
            ('usage_bytes|kernelReservedSize', 'vmware_vsan_memory_usage_bytes', ['kernelReservedSize'], 'The usage of vSAN memory. (kernelReservedSize)'),
            ('usage_bytes|lsom2HeapConsumed', 'vmware_vsan_memory_usage_bytes', ['lsom2HeapConsumed'], 'The usage of vSAN memory. (lsom2HeapConsumed)'),
            ('usage_bytes|lsom2HeapReserved', 'vmware_vsan_memory_usage_bytes', ['lsom2HeapReserved'], 'The usage of vSAN memory. (lsom2HeapReserved)'),
            ('usage_bytes|lsom2SlabConsumed', 'vmware_vsan_memory_usage_bytes', ['lsom2SlabConsumed'], 'The usage of vSAN memory. (lsom2SlabConsumed)'),
            ('usage_bytes|lsom2SlabReserved', 'vmware_vsan_memory_usage_bytes', ['lsom2SlabReserved'], 'The usage of vSAN memory. (lsom2SlabReserved)'),
            ('usage_bytes|lsom2VaSpaceConsumed', 'vmware_vsan_memory_usage_bytes', ['lsom2VaSpaceConsumed'], 'The usage of vSAN memory. (lsom2VaSpaceConsumed)'),
            ('usage_bytes|lsom2VaSpaceReserved', 'vmware_vsan_memory_usage_bytes', ['lsom2VaSpaceReserved'], 'The usage of vSAN memory. (lsom2VaSpaceReserved)'),
            ('usage_bytes|osfsdConsumedSize', 'vmware_vsan_memory_usage_bytes', ['osfsdConsumedSize'], 'The usage of vSAN memory. (osfsdConsumedSize)'),
            ('usage_bytes|osfsdMemAllocMax', 'vmware_vsan_memory_usage_bytes', ['osfsdMemAllocMax'], 'The usage of vSAN memory. (osfsdMemAllocMax)'),
            ('usage_bytes|osfsdMemAllocMin', 'vmware_vsan_memory_usage_bytes', ['osfsdMemAllocMin'], 'The usage of vSAN memory. (osfsdMemAllocMin)'),
            ('usage_bytes|osfsdReservedSize', 'vmware_vsan_memory_usage_bytes', ['osfsdReservedSize'], 'The usage of vSAN memory. (osfsdReservedSize)'),
            ('usage_bytes|uwConsumedSize', 'vmware_vsan_memory_usage_bytes', ['uwConsumedSize'], 'The usage of vSAN memory. (uwConsumedSize)'),
            ('usage_bytes|uwMemAllocMax', 'vmware_vsan_memory_usage_bytes', ['uwMemAllocMax'], 'The usage of vSAN memory. (uwMemAllocMax)'),
            ('usage_bytes|uwMemAllocMin', 'vmware_vsan_memory_usage_bytes', ['uwMemAllocMin'], 'The usage of vSAN memory. (uwMemAllocMin)'),
            ('usage_bytes|uwReservedSize', 'vmware_vsan_memory_usage_bytes', ['uwReservedSize'], 'The usage of vSAN memory. (uwReservedSize)'),
            ('usage_bytes|vitdConsumedSize', 'vmware_vsan_memory_usage_bytes', ['vitdConsumedSize'], 'The usage of vSAN memory. (vitdConsumedSize)'),
            ('usage_bytes|vitdMemAllocMax', 'vmware_vsan_memory_usage_bytes', ['vitdMemAllocMax'], 'The usage of vSAN memory. (vitdMemAllocMax)'),
            ('usage_bytes|vitdMemAllocMin', 'vmware_vsan_memory_usage_bytes', ['vitdMemAllocMin'], 'The usage of vSAN memory. (vitdMemAllocMin)'),
            ('usage_bytes|vitdReservedSize', 'vmware_vsan_memory_usage_bytes', ['vitdReservedSize'], 'The usage of vSAN memory. (vitdReservedSize)'),
            ('usage_bytes|vsandevicemonitordConsumedSize', 'vmware_vsan_memory_usage_bytes', ['vsandevicemonitordConsumedSize'], 'The usage of vSAN memory. (vsandevicemonitordConsumedSize)'),
            ('usage_bytes|vsandevicemonitordMemAllocMax', 'vmware_vsan_memory_usage_bytes', ['vsandevicemonitordMemAllocMax'], 'The usage of vSAN memory. (vsandevicemonitordMemAllocMax)'),
            ('usage_bytes|vsandevicemonitordMemAllocMin', 'vmware_vsan_memory_usage_bytes', ['vsandevicemonitordMemAllocMin'], 'The usage of vSAN memory. (vsandevicemonitordMemAllocMin)'),
            ('usage_bytes|vsandevicemonitordReservedSize', 'vmware_vsan_memory_usage_bytes', ['vsandevicemonitordReservedSize'], 'The usage of vSAN memory. (vsandevicemonitordReservedSize)'),
            ('usage_bytes|vsanmgmtdConsumedSize', 'vmware_vsan_memory_usage_bytes', ['vsanmgmtdConsumedSize'], 'The usage of vSAN memory. (vsanmgmtdConsumedSize)'),
            ('usage_bytes|vsanmgmtdMemAllocMax', 'vmware_vsan_memory_usage_bytes', ['vsanmgmtdMemAllocMax'], 'The usage of vSAN memory. (vsanmgmtdMemAllocMax)'),
            ('usage_bytes|vsanmgmtdMemAllocMin', 'vmware_vsan_memory_usage_bytes', ['vsanmgmtdMemAllocMin'], 'The usage of vSAN memory. (vsanmgmtdMemAllocMin)'),
            ('usage_bytes|vsanmgmtdReservedSize', 'vmware_vsan_memory_usage_bytes', ['vsanmgmtdReservedSize'], 'The usage of vSAN memory. (vsanmgmtdReservedSize)'),
            ('usage_bytes|vsanmgmtdWatchdogConsumedSize', 'vmware_vsan_memory_usage_bytes', ['vsanmgmtdWatchdogConsumedSize'], 'The usage of vSAN memory. (vsanmgmtdWatchdogConsumedSize)'),
            ('usage_bytes|vsanmgmtdWatchdogMemAllocMax', 'vmware_vsan_memory_usage_bytes', ['vsanmgmtdWatchdogMemAllocMax'], 'The usage of vSAN memory. (vsanmgmtdWatchdogMemAllocMax)'),
            ('usage_bytes|vsanmgmtdWatchdogMemAllocMin', 'vmware_vsan_memory_usage_bytes', ['vsanmgmtdWatchdogMemAllocMin'], 'The usage of vSAN memory. (vsanmgmtdWatchdogMemAllocMin)'),
            ('usage_bytes|vsanmgmtdWatchdogReservedSize', 'vmware_vsan_memory_usage_bytes', ['vsanmgmtdWatchdogReservedSize'], 'The usage of vSAN memory. (vsanmgmtdWatchdogReservedSize)'),
            ('usage_bytes|vsanobserverConsumedSize', 'vmware_vsan_memory_usage_bytes', ['vsanobserverConsumedSize'], 'The usage of vSAN memory. (vsanobserverConsumedSize)'),
            ('usage_bytes|vsanobserverMemAllocMax', 'vmware_vsan_memory_usage_bytes', ['vsanobserverMemAllocMax'], 'The usage of vSAN memory. (vsanobserverMemAllocMax)'),
            ('usage_bytes|vsanobserverMemAllocMin', 'vmware_vsan_memory_usage_bytes', ['vsanobserverMemAllocMin'], 'The usage of vSAN memory. (vsanobserverMemAllocMin)'),
            ('usage_bytes|vsanobserverReservedSize', 'vmware_vsan_memory_usage_bytes', ['vsanobserverReservedSize'], 'The usage of vSAN memory. (vsanobserverReservedSize)'),
            ('usage_bytes|vsantracedConsumedSize', 'vmware_vsan_memory_usage_bytes', ['vsantracedConsumedSize'], 'The usage of vSAN memory. (vsantracedConsumedSize)'),
            ('usage_bytes|vsantracedMemAllocMax', 'vmware_vsan_memory_usage_bytes', ['vsantracedMemAllocMax'], 'The usage of vSAN memory. (vsantracedMemAllocMax)'),
            ('usage_bytes|vsantracedMemAllocMin', 'vmware_vsan_memory_usage_bytes', ['vsantracedMemAllocMin'], 'The usage of vSAN memory. (vsantracedMemAllocMin)'),
            ('usage_bytes|vsantracedReservedSize', 'vmware_vsan_memory_usage_bytes', ['vsantracedReservedSize'], 'The usage of vSAN memory. (vsantracedReservedSize)'),
            ('usage_bytes|zdomHeapConsumed', 'vmware_vsan_memory_usage_bytes', ['zdomHeapConsumed'], 'The usage of vSAN memory. (zdomHeapConsumed)'),
            ('usage_bytes|zdomHeapReserved', 'vmware_vsan_memory_usage_bytes', ['zdomHeapReserved'], 'The usage of vSAN memory. (zdomHeapReserved)'),
            ('usage_bytes|zdomSlabConsumed', 'vmware_vsan_memory_usage_bytes', ['zdomSlabConsumed'], 'The usage of vSAN memory. (zdomSlabConsumed)'),
            ('usage_bytes|zdomSlabReserved', 'vmware_vsan_memory_usage_bytes', ['zdomSlabReserved'], 'The usage of vSAN memory. (zdomSlabReserved)'),
            ('usage_bytes|zdomVaSpaceConsumed', 'vmware_vsan_memory_usage_bytes', ['zdomVaSpaceConsumed'], 'The usage of vSAN memory. (zdomVaSpaceConsumed)'),
            ('usage_bytes|zdomVaSpaceReserved', 'vmware_vsan_memory_usage_bytes', ['zdomVaSpaceReserved'], 'The usage of vSAN memory. (zdomVaSpaceReserved)'),
        ],
    },
    'vmware_vsan_rdt': {
        'identity': [],
        'metric_key_labels': ['sink_type'],
        'properties': ['name', 'unicast_agent_ipv4'],
        'objects_per_host': 1,
        'metrics': [
            ('max_network_latency|hot', 'vmware_vsan_rdt_max_network_latency', ['hot'], 'The maximum RDT roundtrip network latency in microsecond (hot)'),
            ('min_network_latency|cold', 'vmware_vsan_rdt_min_network_latency', ['cold'], 'The minimum RDT roundtrip network latency in microsecond (cold)'),
        ],
    },
    'vmware_vsan_vdisk': {
        'identity': ['objpath', 'objuuid'],
        'metric_key_labels': ['io_type'],
        'properties': ['sink_type'],
        'objects_per_host': 2,
        'metrics': [
            ('iopslimit', 'vmware_vsan_vdisk_iopslimit', [''], 'IOPS limit number of a virtual disk. ()'),
            ('normalizedio_total|read', 'vmware_vsan_vdisk_normalizedio_total', ['read'], 'Total normalized IOs of a virtual disk. (read)'),
            ('normalizedio_total|readdelay', 'vmware_vsan_vdisk_normalizedio_total', ['readdelay'], 'Total normalized IOs of a virtual disk. (readdelay)'),
            ('normalizedio_total|write', 'vmware_vsan_vdisk_normalizedio_total', ['write'], 'Total normalized IOs of a virtual disk. (write)'),
            ('normalizedio_total|writedelay', 'vmware_vsan_vdisk_normalizedio_total', ['writedelay'], 'Total normalized IOs of a virtual disk. (writedelay)'),
        ],
    },
    'vmware_vsan_vscsi': {
        'identity': ['objuuid', 'vm_instance_uuid', 'vscsi_name'],
        'metric_key_labels': ['io_type'],
        'properties': ['sink_type', 'vm_name'],
        'objects_per_host': 16,
        'metrics': [
            ('io_bytes_total|read', 'vmware_vsan_vscsi_io_bytes_total', ['read'], 'Total bytes seen by a VSCSI controller in a VM. (read)'),
            ('io_bytes_total|write', 'vmware_vsan_vscsi_io_bytes_total', ['write'], 'Total bytes seen by a VSCSI controller in a VM. (write)'),
            ('io_duration_seconds_total|read', 'vmware_vsan_vscsi_io_duration_seconds_total', ['read'], 'Sum total of duration of IO seen by a VSCSI controller in a VM. (read)'),
            ('io_duration_seconds_total|write', 'vmware_vsan_vscsi_io_duration_seconds_total', ['write'], 'Sum total of duration of IO seen by a VSCSI controller in a VM. (write)'),
            ('io_total|read', 'vmware_vsan_vscsi_io_total', ['read'], 'Total IOs seen by a VSCSI controller in a VM. (read)'),
            ('io_total|write', 'vmware_vsan_vscsi_io_total', ['write'], 'Total IOs seen by a VSCSI controller in a VM. (write)'),
        ],
    },
}

# All source metric names we consume, for the parser's keep-filter.
KEEP: Dict[str, str] = {
    'vmware_esx_heap_usage_ratio': 'vmware_esx_heap',
    'vmware_esx_pnic_pkt_bytes_total': 'vmware_esx_pnic',
    'vmware_esx_pnic_pkt_err_total': 'vmware_esx_pnic',
    'vmware_esx_pnic_pkt_total': 'vmware_esx_pnic',
    'vmware_esx_rdt_checksum_mismatch_count': 'vmware_esx_rdt',
    'vmware_esx_rdt_latency_us': 'vmware_esx_rdt',
    'vmware_esx_slab_alloc_count': 'vmware_esx_slab',
    'vmware_esx_slab_max_count': 'vmware_esx_slab',
    'vmware_esx_tcppkt_bytes_total': 'vmware_esx_tcppkt',
    'vmware_esx_tcppkt_rcvdupack_total': 'vmware_esx_tcppkt',
    'vmware_esx_tcppkt_rcvduppack_total': 'vmware_esx_tcppkt',
    'vmware_esx_tcppkt_rcvoopack_total': 'vmware_esx_tcppkt',
    'vmware_esx_tcppkt_sack_rcv_blocks_total': 'vmware_esx_tcppkt',
    'vmware_esx_tcppkt_sack_rexmits_total': 'vmware_esx_tcppkt',
    'vmware_esx_tcppkt_sack_send_blocks_total': 'vmware_esx_tcppkt',
    'vmware_esx_tcppkt_sndrexmitpack_total': 'vmware_esx_tcppkt',
    'vmware_esx_tcppkt_total': 'vmware_esx_tcppkt',
    'vmware_esx_world_readytime_seconds_total': 'vmware_esx_world',
    'vmware_esx_world_uptime_seconds_total': 'vmware_esx_world',
    'vmware_esx_world_usedtime_seconds_total': 'vmware_esx_world',
    'vmware_host_cpu_seconds_total': 'vmware_host_cpu',
    'vmware_vsan_cmmds_local_updates_count': 'vmware_vsan_cmmds',
    'vmware_vsan_cmmds_update_latency': 'vmware_vsan_cmmds',
    'vmware_vsan_cmmds_updates_count_at_leader': 'vmware_vsan_cmmds',
    'vmware_vsan_cmmds_workload_agent_batches_sent': 'vmware_vsan_cmmds',
    'vmware_vsan_cmmds_workload_check_point_batches_sent': 'vmware_vsan_cmmds',
    'vmware_vsan_cmmds_workload_heartbeat_soft_timeouts': 'vmware_vsan_cmmds',
    'vmware_vsan_cmmds_workload_heartbeats_missed': 'vmware_vsan_cmmds',
    'vmware_vsan_cmmds_workload_master_batches_recved': 'vmware_vsan_cmmds',
    'vmware_vsan_cmmds_workload_rx_accept': 'vmware_vsan_cmmds',
    'vmware_vsan_cmmds_workload_rx_agent_update_request': 'vmware_vsan_cmmds',
    'vmware_vsan_cmmds_workload_rx_heartbeat_request': 'vmware_vsan_cmmds',
    'vmware_vsan_cmmds_workload_rx_master_update': 'vmware_vsan_cmmds',
    'vmware_vsan_cmmds_workload_rx_misc': 'vmware_vsan_cmmds',
    'vmware_vsan_cmmds_workload_rx_retransmit_request': 'vmware_vsan_cmmds',
    'vmware_vsan_cmmds_workload_rx_snapshot': 'vmware_vsan_cmmds',
    'vmware_vsan_cmmds_workload_total_upd_in_batch_ckpt': 'vmware_vsan_cmmds',
    'vmware_vsan_cmmds_workload_total_upd_in_master_batches': 'vmware_vsan_cmmds',
    'vmware_vsan_cmmds_workload_total_upd_sent_in_agent_batch': 'vmware_vsan_cmmds',
    'vmware_vsan_cmmds_workload_tx_agent_update_request': 'vmware_vsan_cmmds',
    'vmware_vsan_cmmds_workload_tx_heartbeat_request': 'vmware_vsan_cmmds',
    'vmware_vsan_cmmds_workload_tx_master_checkpoint': 'vmware_vsan_cmmds',
    'vmware_vsan_cmmds_workload_tx_master_ckpt_tried': 'vmware_vsan_cmmds',
    'vmware_vsan_cmmds_workload_tx_master_update': 'vmware_vsan_cmmds',
    'vmware_vsan_cmmds_workload_tx_master_update_tried': 'vmware_vsan_cmmds',
    'vmware_vsan_cmmds_workload_tx_retransmit_request': 'vmware_vsan_cmmds',
    'vmware_vsan_cmmds_workload_tx_snapshot': 'vmware_vsan_cmmds',
    'vmware_vsan_cmmds_workload_tx_snapshot_bytes': 'vmware_vsan_cmmds',
    'vmware_vsan_cmmds_workload_tx_snapshot_tried': 'vmware_vsan_cmmds',
    'vmware_vsan_disk_checksum_errors_total': 'vmware_vsan_disk',
    'vmware_vsan_dom_clientcache_readhit_count': 'vmware_vsan_dom',
    'vmware_vsan_dom_clientcache_readio_count': 'vmware_vsan_dom',
    'vmware_vsan_dom_congestion_total': 'vmware_vsan_dom',
    'vmware_vsan_dom_io_bytes_total': 'vmware_vsan_dom',
    'vmware_vsan_dom_io_duration_seconds_total': 'vmware_vsan_dom',
    'vmware_vsan_dom_io_durationsquare_seconds_total': 'vmware_vsan_dom',
    'vmware_vsan_dom_io_total': 'vmware_vsan_dom',
    'vmware_vsan_dom_numoio_total': 'vmware_vsan_dom',
    'vmware_vsan_esa_clom_actual_bytes_moving': 'vmware_vsan_esa',
    'vmware_vsan_esa_clom_actual_bytes_sched_to_move': 'vmware_vsan_esa',
    'vmware_vsan_esa_clom_component_utilization': 'vmware_vsan_esa',
    'vmware_vsan_esa_clom_dedup_ratio': 'vmware_vsan_esa',
    'vmware_vsan_esa_clom_disk_logical_capacity_requested': 'vmware_vsan_esa',
    'vmware_vsan_esa_clom_disk_transient_capacity_used': 'vmware_vsan_esa',
    'vmware_vsan_esa_clom_fitness': 'vmware_vsan_esa',
    'vmware_vsan_esa_clom_fitness_disk_component_count_ratio': 'vmware_vsan_esa',
    'vmware_vsan_esa_clom_fitness_disk_data_component_count_ratio': 'vmware_vsan_esa',
    'vmware_vsan_esa_clom_fitness_diskgroup_data_component_count_ratio': 'vmware_vsan_esa',
    'vmware_vsan_esa_clom_fitness_max_actual_reserved_space_utilization': 'vmware_vsan_esa',
    'vmware_vsan_esa_clom_fitness_node_component_count_ratio': 'vmware_vsan_esa',
    'vmware_vsan_esa_clom_fitness_node_data_component_count_ratio': 'vmware_vsan_esa',
    'vmware_vsan_esa_clom_fitness_read_cache_reservation_utilization': 'vmware_vsan_esa',
    'vmware_vsan_esa_clom_fitness_resource_stddev_change': 'vmware_vsan_esa',
    'vmware_vsan_esa_clom_fitness_unreserved_address_space_utilization': 'vmware_vsan_esa',
    'vmware_vsan_esa_clom_fitness_version_weight': 'vmware_vsan_esa',
    'vmware_vsan_esa_clom_logical_fullness': 'vmware_vsan_esa',
    'vmware_vsan_esa_clom_num_components': 'vmware_vsan_esa',
    'vmware_vsan_esa_clom_pending_deletes': 'vmware_vsan_esa',
    'vmware_vsan_esa_clom_pending_writes': 'vmware_vsan_esa',
    'vmware_vsan_esa_clom_physical_disk_capacity_reserved': 'vmware_vsan_esa',
    'vmware_vsan_esa_clom_physical_free_space': 'vmware_vsan_esa',
    'vmware_vsan_esa_clom_physical_fullness': 'vmware_vsan_esa',
    'vmware_vsan_esa_clom_queued_bytes': 'vmware_vsan_esa',
    'vmware_vsan_esa_clom_queued_objects': 'vmware_vsan_esa',
    'vmware_vsan_esa_clom_rebalancing_fullness': 'vmware_vsan_esa',
    'vmware_vsan_esa_clom_rebalancing_status': 'vmware_vsan_esa',
    'vmware_vsan_esa_clom_total_queued_work_items': 'vmware_vsan_esa',
    'vmware_vsan_esa_clom_work_item_success_count': 'vmware_vsan_esa',
    'vmware_vsan_esa_disk_congestion_be_data': 'vmware_vsan_esa',
    'vmware_vsan_esa_disk_congestion_be_data_allocator': 'vmware_vsan_esa',
    'vmware_vsan_esa_disk_congestion_be_policy_allocator': 'vmware_vsan_esa',
    'vmware_vsan_esa_disk_congestion_global': 'vmware_vsan_esa',
    'vmware_vsan_esa_disk_congestion_spl_allocator': 'vmware_vsan_esa',
    'vmware_vsan_esa_disk_congestion_spl_attr': 'vmware_vsan_esa',
    'vmware_vsan_esa_disk_congestion_spl_logical': 'vmware_vsan_esa',
    'vmware_vsan_esa_disk_congestion_spl_prepare': 'vmware_vsan_esa',
    'vmware_vsan_esa_disk_congestion_wal': 'vmware_vsan_esa',
    'vmware_vsan_esa_disk_congestion_wal_allocator': 'vmware_vsan_esa',
    'vmware_vsan_esa_disk_dev_read_time_total': 'vmware_vsan_esa',
    'vmware_vsan_esa_disk_dev_write_time_total': 'vmware_vsan_esa',
    'vmware_vsan_esa_disk_io_bytes': 'vmware_vsan_esa',
    'vmware_vsan_esa_disk_io_count': 'vmware_vsan_esa',
    'vmware_vsan_esa_disk_num_allocated_blocks': 'vmware_vsan_esa',
    'vmware_vsan_esa_disk_num_total_blocks': 'vmware_vsan_esa',
    'vmware_vsan_esa_disk_pending_free_blocks': 'vmware_vsan_esa',
    'vmware_vsan_esa_disk_read_io_bytes': 'vmware_vsan_esa',
    'vmware_vsan_esa_disk_read_io_count': 'vmware_vsan_esa',
    'vmware_vsan_esa_disk_read_time_max': 'vmware_vsan_esa',
    'vmware_vsan_esa_disk_read_time_min': 'vmware_vsan_esa',
    'vmware_vsan_esa_disk_read_time_sum': 'vmware_vsan_esa',
    'vmware_vsan_esa_disk_write_io_bytes': 'vmware_vsan_esa',
    'vmware_vsan_esa_disk_write_io_count': 'vmware_vsan_esa',
    'vmware_vsan_esa_disk_write_time_max': 'vmware_vsan_esa',
    'vmware_vsan_esa_disk_write_time_min': 'vmware_vsan_esa',
    'vmware_vsan_esa_disk_write_time_sum': 'vmware_vsan_esa',
    'vmware_vsan_esa_num_max_components': 'vmware_vsan_esa',
    'vmware_vsan_esa_splinter_cache_hits_branch': 'vmware_vsan_esa',
    'vmware_vsan_esa_splinter_cache_hits_branch_range': 'vmware_vsan_esa',
    'vmware_vsan_esa_splinter_cache_hits_filter': 'vmware_vsan_esa',
    'vmware_vsan_esa_splinter_cache_hits_misc': 'vmware_vsan_esa',
    'vmware_vsan_esa_splinter_cache_misses_branch': 'vmware_vsan_esa',
    'vmware_vsan_esa_splinter_cache_misses_branch_range': 'vmware_vsan_esa',
    'vmware_vsan_esa_splinter_cache_misses_filter': 'vmware_vsan_esa',
    'vmware_vsan_esa_splinter_cache_misses_misc': 'vmware_vsan_esa',
    'vmware_vsan_esa_splinter_checkpoint_write_latency_max': 'vmware_vsan_esa',
    'vmware_vsan_esa_splinter_current_outstanding_tasks': 'vmware_vsan_esa',
    'vmware_vsan_esa_splinter_max_outstanding_tasks': 'vmware_vsan_esa',
    'vmware_vsan_esa_splinter_memtable_pending_tasks': 'vmware_vsan_esa',
    'vmware_vsan_esa_splinter_total_tasks': 'vmware_vsan_esa',
    'vmware_vsan_esa_splinter_total_tasks_latency_max_ns': 'vmware_vsan_esa',
    'vmware_vsan_esa_splinter_total_tasks_latency_ns': 'vmware_vsan_esa',
    'vmware_vsan_esa_splinter_total_tasks_runtime_max_ns': 'vmware_vsan_esa',
    'vmware_vsan_esa_zdom_all_op_cache_miss': 'vmware_vsan_esa',
    'vmware_vsan_esa_zdom_all_op_logical_tree_cache_miss': 'vmware_vsan_esa',
    'vmware_vsan_esa_zdom_all_op_middle_tree_cache_miss': 'vmware_vsan_esa',
    'vmware_vsan_esa_zdom_all_op_snap_tree_cache_miss': 'vmware_vsan_esa',
    'vmware_vsan_esa_zdom_bank_flush_count': 'vmware_vsan_esa',
    'vmware_vsan_esa_zdom_bank_flush_latency_us': 'vmware_vsan_esa',
    'vmware_vsan_esa_zdom_data_checksum_mismatch': 'vmware_vsan_esa',
    'vmware_vsan_esa_zdom_seg_clean_read_bytes': 'vmware_vsan_esa',
    'vmware_vsan_esa_zdom_seg_clean_unmap_bytes': 'vmware_vsan_esa',
    'vmware_vsan_esa_zdom_seg_clean_write_bytes': 'vmware_vsan_esa',
    'vmware_vsan_heap_usage_current_allocation': 'vmware_vsan_heap',
    'vmware_vsan_heap_usage_current_available': 'vmware_vsan_heap',
    'vmware_vsan_heap_usage_current_size': 'vmware_vsan_heap',
    'vmware_vsan_heap_usage_failed_count': 'vmware_vsan_heap',
    'vmware_vsan_heap_usage_max_size': 'vmware_vsan_heap',
    'vmware_vsan_memory_usage_bytes': 'vmware_vsan_memory',
    'vmware_vsan_rdt_max_network_latency': 'vmware_vsan_rdt',
    'vmware_vsan_rdt_min_network_latency': 'vmware_vsan_rdt',
    'vmware_vsan_vdisk_iopslimit': 'vmware_vsan_vdisk',
    'vmware_vsan_vdisk_normalizedio_total': 'vmware_vsan_vdisk',
    'vmware_vsan_vscsi_io_bytes_total': 'vmware_vsan_vscsi',
    'vmware_vsan_vscsi_io_duration_seconds_total': 'vmware_vsan_vscsi',
    'vmware_vsan_vscsi_io_total': 'vmware_vsan_vscsi',
}
