"""GENERATED -- do not edit by hand.

Regenerate:
    python3 tools/build_model_extra.py

Entity types the LIVE model omits because they returned no data on the
cluster it was generated against -- principally every OSA family, which is
silent on ESA. Without these the pack never queries them, so an OSA cluster
collects nothing for its disk groups or cache and capacity disks.

PROVISIONAL. Metrics are the ADVERTISED set, which understates what the
service returns; identity is INFERRED from the entity name and the
equivalent ESA families. Model a real OSA cluster properly with
tools/model_from_perfsvc.py and fold the result into perfsvc_model.py.
"""

from typing import Any, Dict

ENTITIES: Dict[str, Dict[str, Any]] = {
    'cache-disk': {
        'kind': 'VsanCacheDisk',
        'label': 'vSAN Cache Disk',
        'identity': ['disk_uuid'],
        'objects_observed': 0,
        'metrics': [
            'iopsDevRead',
            'iopsDevWrite',
            'latencyDevDAvg',
            'latencyDevGAvg',
            'latencyDevRead',
            'latencyDevWrite',
            'throughputDevRead',
            'throughputDevWrite',
        ],
    },
    'capacity-disk': {
        'kind': 'VsanCapacityDisk',
        'label': 'vSAN Capacity Disk',
        'identity': ['disk_uuid'],
        'objects_observed': 0,
        'metrics': [
            'deleteCongestion',
            'iopsDevRead',
            'iopsDevWrite',
            'iopsRead',
            'iopsWrite',
            'latencyDevDAvg',
            'latencyDevGAvg',
            'latencyDevRead',
            'latencyDevWrite',
            'latencyRead',
            'latencyWrite',
            'throughputDevRead',
            'throughputDevWrite',
        ],
    },
    'clom-disk': {
        'kind': 'VsanClomDisk',
        'label': 'vSAN CLOM Disk',
        'identity': ['disk_uuid'],
        'objects_observed': 0,
        'metrics': [
            'diskCompCntRatio',
            'diskDataCompCntRatio',
            'diskgrpDataCompCntRatio',
        ],
    },
    'clom-host': {
        'kind': 'VsanClomHost',
        'label': 'vSAN CLOM Host',
        'identity': ['host_uuid'],
        'objects_observed': 0,
        'metrics': [
            'nodeCompCntRatio',
            'nodeDataCompCntRatio',
        ],
    },
    'cluster-esa-dedup-domclient-io': {
        'kind': 'VsanClusterEsaDedupDomclientIo',
        'label': 'vSAN Cluster ESA Dedup Domclient IO',
        'identity': ['cluster_uuid'],
        'objects_observed': 0,
        'metrics': [
            'dedupChunkReadCount',
            'dedupChunkWriteCount',
            'dedupEngineReadCount',
            'dedupEngineWriteCount',
            'dedupHashReadCount',
            'dedupHashWriteCount',
            'iopsDedupChunkObjRead',
            'iopsDedupChunkObjWrite',
            'iopsDedupEngineRead',
            'iopsDedupEngineWrite',
            'iopsDedupHashObjRead',
            'iopsDedupHashObjWrite',
            'latencyAvgDedupChunkObjRead',
            'latencyAvgDedupChunkObjWrite',
            'latencyAvgDedupEngineRead',
            'latencyAvgDedupEngineWrite',
            'latencyAvgDedupHashObjRead',
            'latencyAvgDedupHashObjWrite',
            'tputDedupChunkObjRead',
            'tputDedupChunkObjWrite',
            'tputDedupEngineRead',
            'tputDedupEngineWrite',
            'tputDedupHashObjRead',
            'tputDedupHashObjWrite',
        ],
    },
    'cluster-esa-dedup-domcompmgr-io': {
        'kind': 'VsanClusterEsaDedupDomcompmgrIo',
        'label': 'vSAN Cluster ESA Dedup Domcompmgr IO',
        'identity': ['cluster_uuid'],
        'objects_observed': 0,
        'metrics': [
            'dedupChunkReadCount',
            'dedupChunkWriteCount',
            'dedupEngineReadCount',
            'dedupEngineWriteCount',
            'dedupHashReadCount',
            'dedupHashWriteCount',
            'iopsDedupChunkObjRead',
            'iopsDedupChunkObjWrite',
            'iopsDedupEngineRead',
            'iopsDedupEngineWrite',
            'iopsDedupHashObjRead',
            'iopsDedupHashObjWrite',
            'latencyAvgDedupChunkObjRead',
            'latencyAvgDedupChunkObjWrite',
            'latencyAvgDedupEngineRead',
            'latencyAvgDedupEngineWrite',
            'latencyAvgDedupHashObjRead',
            'latencyAvgDedupHashObjWrite',
            'tputDedupChunkObjRead',
            'tputDedupChunkObjWrite',
            'tputDedupEngineRead',
            'tputDedupEngineWrite',
            'tputDedupHashObjRead',
            'tputDedupHashObjWrite',
        ],
    },
    'cluster-esa-dedup-domowner-io': {
        'kind': 'VsanClusterEsaDedupDomownerIo',
        'label': 'vSAN Cluster ESA Dedup Domowner IO',
        'identity': ['cluster_uuid'],
        'objects_observed': 0,
        'metrics': [
            'dedupChunkReadCount',
            'dedupChunkWriteCount',
            'dedupEngineReadCount',
            'dedupEngineWriteCount',
            'dedupHashReadCount',
            'dedupHashWriteCount',
            'iopsDedupChunkObjRead',
            'iopsDedupChunkObjWrite',
            'iopsDedupEngineRead',
            'iopsDedupEngineWrite',
            'iopsDedupHashObjRead',
            'iopsDedupHashObjWrite',
            'latencyAvgDedupChunkObjRead',
            'latencyAvgDedupChunkObjWrite',
            'latencyAvgDedupEngineRead',
            'latencyAvgDedupEngineWrite',
            'latencyAvgDedupHashObjRead',
            'latencyAvgDedupHashObjWrite',
            'tputDedupChunkObjRead',
            'tputDedupChunkObjWrite',
            'tputDedupEngineRead',
            'tputDedupEngineWrite',
            'tputDedupHashObjRead',
            'tputDedupHashObjWrite',
        ],
    },
    'cluster-esa-dedup-store-chunksvc': {
        'kind': 'VsanClusterEsaDedupStoreChunksvc',
        'label': 'vSAN Cluster ESA Dedup Store Chunksvc',
        'identity': ['cluster_uuid'],
        'objects_observed': 0,
        'metrics': [
            'latencyChangeRefCount',
            'latencyDeleteChunkExtent',
            'latencyDeletedObjCleanup',
            'latencyGetChunkEntries',
            'latencyReserveMba',
            'numChangeRefCount',
            'numDeleteChunkExtent',
            'numDeletedObjCleanup',
            'numGetChunkEntries',
            'numObjsReported',
            'numReserveMba',
            'rateBlocksInChunkDeleted',
            'rateBlocksInChunkWritten',
            'rateChangeRefCount',
            'rateChunkRefEntAdded',
            'rateChunkRefEntRemoved',
            'rateChunksDeleted',
            'rateChunksInChangeRefCount',
            'rateChunksInDeleteChunkExtent',
            'rateChunksInGetChunkEntries',
            'rateChunksWritten',
            'rateDeleteChunkExtent',
            'rateDeletedObjCleanup',
            'rateGetChunkEntries',
            'rateReserveMba',
            'totalNumBlks',
            'totalNumRefCnt',
        ],
    },
    'cluster-esa-dedup-store-hashsvc': {
        'kind': 'VsanClusterEsaDedupStoreHashsvc',
        'label': 'vSAN Cluster ESA Dedup Store Hashsvc',
        'identity': ['cluster_uuid'],
        'objects_observed': 0,
        'metrics': [
            'currentGenNum',
            'currentStaleGenNum',
            'latencyDeleteChunksReq',
            'latencyNewDupReq',
            'latencyReadLockWait',
            'latencyUniqueHashReq',
            'latencyWriteLockWait',
            'numDeleteChunksReq',
            'numNewDupReq',
            'numObjsReported',
            'numReadLockWait',
            'numUniqHashReq',
            'numWriteLockWait',
            'rateChunkInDeleteChunksReq',
            'rateChunkInNewDupReq',
            'rateChunkInUniqHashReq',
            'rateDedupHashEntryAdded',
            'rateDedupHashEntryRemoved',
            'rateDedupHashEntryUpdated',
            'rateDeleteChunksReq',
            'rateDeletedChunks',
            'rateHashKeyRemovalEntriesPerGen',
            'rateHashKeyRemovalEntriesToScanInStep',
            'rateHashKeyRemovalStepsDone',
            'rateNewDupChunks',
            'rateNewDupReq',
            'rateOldDupChunks',
            'rateReadLockWait',
            'rateRetryChunks',
            'rateSentriesAdded',
            'rateSentriesRemoved',
            'rateUniqChunks',
            'rateUniqHashReq',
            'rateWriteLockWait',
        ],
    },
    'cluster-pmem': {
        'kind': 'VsanClusterPmem',
        'label': 'vSAN Cluster PMem',
        'identity': ['cluster_uuid'],
        'objects_observed': 0,
        'metrics': [
            'bandwidthRead',
            'bandwidthTotal',
            'bandwidthWrite',
            'iopsRead',
            'iopsTotal',
            'iopsWrite',
            'latencyRead',
            'latencyWrite',
        ],
    },
    'cluster-remotedomclient': {
        'kind': 'VsanClusterRemotedomclient',
        'label': 'vSAN Cluster Remotedomclient',
        'identity': ['cluster_uuid'],
        'objects_observed': 0,
        'metrics': [
            'congestion',
            'iopsRead',
            'iopsWrite',
            'latencyAvgRead',
            'latencyAvgWrite',
            'oio',
            'throughputRead',
            'throughputWrite',
        ],
    },
    'cluster-resync': {
        'kind': 'VsanClusterResync',
        'label': 'vSAN Cluster Resync',
        'identity': ['cluster_uuid'],
        'objects_observed': 0,
        'metrics': [
            'iopsResyncReadDecom',
            'iopsResyncReadFixComp',
            'iopsResyncReadPolicy',
            'iopsResyncReadRebalance',
            'iopsResyncWriteDecom',
            'iopsResyncWriteFixComp',
            'iopsResyncWritePolicy',
            'iopsResyncWriteRebalance',
            'latResyncReadDecom',
            'latResyncReadFixComp',
            'latResyncReadPolicy',
            'latResyncReadRebalance',
            'latResyncWriteDecom',
            'latResyncWriteFixComp',
            'latResyncWritePolicy',
            'latResyncWriteRebalance',
            'tputResyncReadDecom',
            'tputResyncReadFixComp',
            'tputResyncReadPolicy',
            'tputResyncReadRebalance',
            'tputResyncWriteDecom',
            'tputResyncWriteFixComp',
            'tputResyncWritePolicy',
            'tputResyncWriteRebalance',
        ],
    },
    'cmmds-workload': {
        'kind': 'VsanCmmdsWorkload',
        'label': 'vSAN CMMDS Workload',
        'identity': ['host_uuid'],
        'objects_observed': 0,
        'metrics': [
            'agentBatchesSent',
            'checkPointBatchesSent',
            'masterBatchesRecved',
            'rxAccept',
            'rxAgentUpdateRequest',
            'rxHeartbeatRequest',
            'rxMasterUpdate',
            'rxMisc',
            'rxRetransmitRequest',
            'rxSnapshot',
            'totalUpdInBatchCkpt',
            'totalUpdInMasterBatches',
            'totalUpdSentInAgentBatch',
            'txAgentUpdateRequest',
            'txHeartbeatRequest',
            'txMasterCheckpoint',
            'txMasterCkptTried',
            'txMasterUpdate',
            'txMasterUpdateTried',
            'txRetransmitRequest',
            'txSnapshot',
            'txSnapshotBytes',
            'txSnapshotTried',
        ],
    },
    'computeCluster-remotedomclient': {
        'kind': 'VsanComputeClusterRemotedomclient',
        'label': 'vSAN ComputeCluster Remotedomclient',
        'identity': ['cluster_uuid'],
        'objects_observed': 0,
        'metrics': [
            'congestion',
            'iopsRead',
            'iopsWrite',
            'latencyAvgRead',
            'latencyAvgWrite',
            'oio',
            'throughputRead',
            'throughputWrite',
        ],
    },
    'computeHost-remotedomclient': {
        'kind': 'VsanComputeHostRemotedomclient',
        'label': 'vSAN ComputeHost Remotedomclient',
        'identity': ['host_uuid'],
        'objects_observed': 0,
        'metrics': [
            'congestion',
            'iopsRead',
            'iopsUnmap',
            'iopsWrite',
            'latencyAvgRead',
            'latencyAvgUnmap',
            'latencyAvgWrite',
            'oio',
            'throughputRead',
            'throughputUnmap',
            'throughputWrite',
        ],
    },
    'ddh-disk': {
        'kind': 'VsanDdhDisk',
        'label': 'vSAN Disk Health Disk',
        'identity': ['disk_uuid'],
        'objects_observed': 0,
        'metrics': [
            'avgReadIOPS',
            'avgReadLatency',
            'avgReadTPut',
            'avgUnmapIOPS',
            'avgUnmapLatency',
            'avgUnmapTPut',
            'avgWriteIOPS',
            'avgWriteLatency',
            'avgWriteTPut',
            'logCongestion',
        ],
    },
    'disk-group': {
        'kind': 'VsanDiskGroup',
        'label': 'vSAN Disk Group',
        'identity': ['disk_uuid'],
        'objects_observed': 0,
        'metrics': [
            'componentCongestionReadSched',
            'componentCongestionWriteSched',
            'diskgroupCongestionReadSched',
            'diskgroupCongestionWriteSched',
            'iopsDelayPctSched',
            'iopsDirectSched',
            'iopsResyncRead',
            'iopsResyncReadDecom',
            'iopsResyncReadFixComp',
            'iopsResyncReadPolicy',
            'iopsResyncReadRebalance',
            'iopsResyncWrite',
            'iopsResyncWriteDecom',
            'iopsResyncWriteFixComp',
            'iopsResyncWritePolicy',
            'iopsResyncWriteRebalance',
            'latResyncRead',
            'latResyncReadDecom',
            'latResyncReadFixComp',
            'latResyncReadPolicy',
            'latResyncReadRebalance',
            'latResyncWrite',
            'latResyncWriteDecom',
            'latResyncWriteFixComp',
            'latResyncWritePolicy',
            'latResyncWriteRebalance',
            'latencySched',
            'outstandingBytesSched',
            'tputResyncRead',
            'tputResyncReadDecom',
            'tputResyncReadFixComp',
            'tputResyncReadPolicy',
            'tputResyncReadRebalance',
            'tputResyncWrite',
            'tputResyncWriteDecom',
            'tputResyncWriteFixComp',
            'tputResyncWritePolicy',
            'tputResyncWriteRebalance',
        ],
    },
    'heap-memory': {
        'kind': 'VsanHeapMemory',
        'label': 'vSAN Heap Memory',
        'identity': ['host_uuid', 'heap_name'],
        'objects_observed': 0,
        'metrics': [
            'heapUtil',
        ],
    },
    'host-esa-dedup-domclient-io': {
        'kind': 'VsanHostEsaDedupDomclientIo',
        'label': 'vSAN Host ESA Dedup Domclient IO',
        'identity': ['host_uuid'],
        'objects_observed': 0,
        'metrics': [
            'dedupChunkReadCount',
            'dedupChunkWriteCount',
            'dedupEngineReadCount',
            'dedupEngineWriteCount',
            'dedupHashReadCount',
            'dedupHashWriteCount',
            'iopsDedupChunkObjRead',
            'iopsDedupChunkObjWrite',
            'iopsDedupEngineRead',
            'iopsDedupEngineWrite',
            'iopsDedupHashObjRead',
            'iopsDedupHashObjWrite',
            'latencyAvgDedupChunkObjRead',
            'latencyAvgDedupChunkObjWrite',
            'latencyAvgDedupEngineRead',
            'latencyAvgDedupEngineWrite',
            'latencyAvgDedupHashObjRead',
            'latencyAvgDedupHashObjWrite',
            'tputDedupChunkObjRead',
            'tputDedupChunkObjWrite',
            'tputDedupEngineRead',
            'tputDedupEngineWrite',
            'tputDedupHashObjRead',
            'tputDedupHashObjWrite',
        ],
    },
    'host-esa-dedup-domcompmgr-io': {
        'kind': 'VsanHostEsaDedupDomcompmgrIo',
        'label': 'vSAN Host ESA Dedup Domcompmgr IO',
        'identity': ['host_uuid'],
        'objects_observed': 0,
        'metrics': [
            'dedupChunkReadCount',
            'dedupChunkWriteCount',
            'dedupEngineReadCount',
            'dedupEngineWriteCount',
            'dedupHashReadCount',
            'dedupHashWriteCount',
            'iopsDedupChunkObjRead',
            'iopsDedupChunkObjWrite',
            'iopsDedupEngineRead',
            'iopsDedupEngineWrite',
            'iopsDedupHashObjRead',
            'iopsDedupHashObjWrite',
            'latencyAvgDedupChunkObjRead',
            'latencyAvgDedupChunkObjWrite',
            'latencyAvgDedupEngineRead',
            'latencyAvgDedupEngineWrite',
            'latencyAvgDedupHashObjRead',
            'latencyAvgDedupHashObjWrite',
            'tputDedupChunkObjRead',
            'tputDedupChunkObjWrite',
            'tputDedupEngineRead',
            'tputDedupEngineWrite',
            'tputDedupHashObjRead',
            'tputDedupHashObjWrite',
        ],
    },
    'host-esa-dedup-domowner-io': {
        'kind': 'VsanHostEsaDedupDomownerIo',
        'label': 'vSAN Host ESA Dedup Domowner IO',
        'identity': ['host_uuid'],
        'objects_observed': 0,
        'metrics': [
            'dedupChunkReadCount',
            'dedupChunkWriteCount',
            'dedupEngineReadCount',
            'dedupEngineWriteCount',
            'dedupHashReadCount',
            'dedupHashWriteCount',
            'iopsDedupChunkObjRead',
            'iopsDedupChunkObjWrite',
            'iopsDedupEngineRead',
            'iopsDedupEngineWrite',
            'iopsDedupHashObjRead',
            'iopsDedupHashObjWrite',
            'latencyAvgDedupChunkObjRead',
            'latencyAvgDedupChunkObjWrite',
            'latencyAvgDedupEngineRead',
            'latencyAvgDedupEngineWrite',
            'latencyAvgDedupHashObjRead',
            'latencyAvgDedupHashObjWrite',
            'tputDedupChunkObjRead',
            'tputDedupChunkObjWrite',
            'tputDedupEngineRead',
            'tputDedupEngineWrite',
            'tputDedupHashObjRead',
            'tputDedupHashObjWrite',
        ],
    },
    'host-esa-dedup-store-chunksvc': {
        'kind': 'VsanHostEsaDedupStoreChunksvc',
        'label': 'vSAN Host ESA Dedup Store Chunksvc',
        'identity': ['host_uuid'],
        'objects_observed': 0,
        'metrics': [
            'latencyChangeRefCount',
            'latencyDeleteChunkExtent',
            'latencyDeletedObjCleanup',
            'latencyGetChunkEntries',
            'latencyReserveMba',
            'numChangeRefCount',
            'numDeleteChunkExtent',
            'numDeletedObjCleanup',
            'numGetChunkEntries',
            'numObjsReported',
            'numReserveMba',
            'rateBlocksInChunkDeleted',
            'rateBlocksInChunkWritten',
            'rateChangeRefCount',
            'rateChunkRefEntAdded',
            'rateChunkRefEntRemoved',
            'rateChunksDeleted',
            'rateChunksInChangeRefCount',
            'rateChunksInDeleteChunkExtent',
            'rateChunksInGetChunkEntries',
            'rateChunksWritten',
            'rateDeleteChunkExtent',
            'rateDeletedObjCleanup',
            'rateGetChunkEntries',
            'rateReserveMba',
            'totalNumBlks',
            'totalNumRefCnt',
        ],
    },
    'host-esa-dedup-store-hashsvc': {
        'kind': 'VsanHostEsaDedupStoreHashsvc',
        'label': 'vSAN Host ESA Dedup Store Hashsvc',
        'identity': ['host_uuid'],
        'objects_observed': 0,
        'metrics': [
            'currentGenNum',
            'currentStaleGenNum',
            'latencyDeleteChunksReq',
            'latencyNewDupReq',
            'latencyReadLockWait',
            'latencyUniqueHashReq',
            'latencyWriteLockWait',
            'numDeleteChunksReq',
            'numNewDupReq',
            'numObjsReported',
            'numReadLockWait',
            'numUniqHashReq',
            'numWriteLockWait',
            'rateChunkInDeleteChunksReq',
            'rateChunkInNewDupReq',
            'rateChunkInUniqHashReq',
            'rateDedupHashEntryAdded',
            'rateDedupHashEntryRemoved',
            'rateDedupHashEntryUpdated',
            'rateDeleteChunksReq',
            'rateDeletedChunks',
            'rateHashKeyRemovalEntriesPerGen',
            'rateHashKeyRemovalEntriesToScanInStep',
            'rateHashKeyRemovalStepsDone',
            'rateNewDupChunks',
            'rateNewDupReq',
            'rateOldDupChunks',
            'rateReadLockWait',
            'rateRetryChunks',
            'rateSentriesAdded',
            'rateSentriesRemoved',
            'rateUniqChunks',
            'rateUniqHashReq',
            'rateWriteLockWait',
        ],
    },
    'host-pmem': {
        'kind': 'VsanHostPmem',
        'label': 'vSAN Host PMem',
        'identity': ['host_uuid'],
        'objects_observed': 0,
        'metrics': [
            'bandwidthRead',
            'bandwidthTotal',
            'bandwidthWrite',
            'iopsRead',
            'iopsTotal',
            'iopsWrite',
            'latencyRead',
            'latencyWrite',
        ],
    },
    'host-remotedomclient': {
        'kind': 'VsanHostRemotedomclient',
        'label': 'vSAN Host Remotedomclient',
        'identity': ['host_uuid'],
        'objects_observed': 0,
        'metrics': [
            'congestion',
            'iopsRead',
            'iopsUnmap',
            'iopsWrite',
            'latencyAvgRead',
            'latencyAvgUnmap',
            'latencyAvgWrite',
            'oio',
            'throughputRead',
            'throughputUnmap',
            'throughputWrite',
        ],
    },
    'ioinsight': {
        'kind': 'VsanIoinsight',
        'label': 'vSAN Ioinsight',
        'identity': ['host_uuid'],
        'objects_observed': 0,
        'metrics': [
            'aligned4kRatio',
            'aligned4kReadRatio',
            'aligned4kWriteRatio',
            'iopsRead',
            'iopsTotal',
            'iopsWrite',
            'randomRatio',
            'randomReadRatio',
            'randomWriteRatio',
            'readRatio',
            'riosz0_4k',
            'riosz128k',
            'riosz128k_256k',
            'riosz16k',
            'riosz16k_32k',
            'riosz1_m',
            'riosz1m',
            'riosz256k',
            'riosz256k_512k',
            'riosz32k',
            'riosz32k_64k',
            'riosz4k',
            'riosz4k_8k',
            'riosz512k',
            'riosz512k_1m',
            'riosz64k',
            'riosz64k_128k',
            'riosz8k',
            'riosz8k_16k',
            'rlat0_1us',
            'rlat100_500us',
            'rlat100_ms',
            'rlat10_100us',
            'rlat10_25ms',
            'rlat1_10us',
            'rlat1_5ms',
            'rlat25_50ms',
            'rlat500us_1ms',
            'rlat50_100ms',
            'rlat5_10ms',
            'sequentialRatio',
            'sequentialReadRatio',
            'sequentialWriteRatio',
            'throughputRandom',
            'throughputRead',
            'throughputSequential',
            'throughputTotal',
            'throughputWrite',
            'unaligned4kRatio',
            'unaligned4kReadRatio',
            'unaligned4kWriteRatio',
            'wiosz0_4k',
            'wiosz128k',
            'wiosz128k_256k',
            'wiosz16k',
            'wiosz16k_32k',
            'wiosz1_m',
            'wiosz1m',
            'wiosz256k',
            'wiosz256k_512k',
            'wiosz32k',
            'wiosz32k_64k',
            'wiosz4k',
            'wiosz4k_8k',
            'wiosz512k',
            'wiosz512k_1m',
            'wiosz64k',
            'wiosz64k_128k',
            'wiosz8k',
            'wiosz8k_16k',
            'wlat0_1us',
            'wlat100_500us',
            'wlat100_ms',
            'wlat10_100us',
            'wlat10_25ms',
            'wlat1_10us',
            'wlat1_5ms',
            'wlat25_50ms',
            'wlat500us_1ms',
            'wlat50_100ms',
            'wlat5_10ms',
            'writeRatio',
        ],
    },
    'lsom-world-cpu': {
        'kind': 'VsanLsomWorldCpu',
        'label': 'vSAN LSOM World CPU',
        'identity': ['host_uuid', 'world_name', 'world_id'],
        'objects_observed': 0,
        'metrics': [
            'readyPct',
            'usedPct',
        ],
    },
    'remote-virtual-disk': {
        'kind': 'VsanRemoteVirtualDisk',
        'label': 'vSAN Remote Virtual Disk',
        'identity': ['disk_uuid'],
        'objects_observed': 0,
        'metrics': [
            'NIOPS',
            'NIOPSDelayed',
            'iopsLimit',
        ],
    },
    'remote-virtual-machine': {
        'kind': 'VsanRemoteVirtualMachine',
        'label': 'vSAN Remote Virtual Machine',
        'identity': ['vm_uuid'],
        'objects_observed': 0,
        'metrics': [
            'iopsRead',
            'iopsWrite',
            'latencyRead',
            'latencyWrite',
            'throughputRead',
            'throughputWrite',
        ],
    },
    'remote-vscsi': {
        'kind': 'VsanRemoteVscsi',
        'label': 'vSAN Remote Vscsi',
        'identity': ['vm_uuid', 'device'],
        'objects_observed': 0,
        'metrics': [
            'iopsRead',
            'iopsWrite',
            'latencyRead',
            'latencyWrite',
            'throughputRead',
            'throughputWrite',
        ],
    },
    'slab-memory': {
        'kind': 'VsanSlabMemory',
        'label': 'vSAN Slab Memory',
        'identity': ['host_uuid', 'slab_name'],
        'objects_observed': 0,
        'metrics': [
            'slabUtil',
        ],
    },
    'vsan-direct-cluster': {
        'kind': 'VsanDirectCluster',
        'label': 'vSAN Direct Cluster',
        'identity': ['host_uuid'],
        'objects_observed': 0,
        'metrics': [
            'iopsDevRead',
            'iopsDevWrite',
            'latencyDevRead',
            'latencyDevWrite',
            'oioDevRead',
            'oioDevWrite',
            'throughputDevRead',
            'throughputDevWrite',
        ],
    },
    'vsan-direct-host': {
        'kind': 'VsanDirectHost',
        'label': 'vSAN Direct Host',
        'identity': ['host_uuid'],
        'objects_observed': 0,
        'metrics': [
            'iopsDevRead',
            'iopsDevWrite',
            'latencyDevRead',
            'latencyDevWrite',
            'oioDevRead',
            'oioDevWrite',
            'throughputDevRead',
            'throughputDevWrite',
        ],
    },
    'vsan-distribution': {
        'kind': 'VsanDistribution',
        'label': 'vSAN Distribution',
        'identity': ['host_uuid'],
        'objects_observed': 0,
        'metrics': [
            'components',
            'domClients',
            'domColocated',
            'domOwners',
            'ioComponents',
        ],
    },
    'vsan-file-service': {
        'kind': 'VsanFileService',
        'label': 'vSAN File Service',
        'identity': ['host_uuid'],
        'objects_observed': 0,
        'metrics': [
            'readLatency',
            'readOpTotal',
            'readRequested',
            'readTransferred',
            'writeLatency',
            'writeOpTotal',
            'writeRequested',
            'writeTransferred',
        ],
    },
    'vsan-iscsi-host': {
        'kind': 'VsanIscsiHost',
        'label': 'vSAN iSCSI Host',
        'identity': ['host_uuid'],
        'objects_observed': 0,
        'metrics': [
            'bandwidthRead',
            'bandwidthTotal',
            'bandwidthWrite',
            'iopsRead',
            'iopsTotal',
            'iopsWrite',
            'latencyRead',
            'latencyTotal',
            'latencyWrite',
            'queueDepth',
        ],
    },
    'vsan-iscsi-lun': {
        'kind': 'VsanIscsiLun',
        'label': 'vSAN iSCSI LUN',
        'identity': ['host_uuid', 'target', 'lun'],
        'objects_observed': 0,
        'metrics': [
            'bandwidthRead',
            'bandwidthTotal',
            'bandwidthWrite',
            'iopsRead',
            'iopsTotal',
            'iopsWrite',
            'latencyRead',
            'latencyTotal',
            'latencyWrite',
            'queueDepth',
        ],
    },
    'vsan-iscsi-target': {
        'kind': 'VsanIscsiTarget',
        'label': 'vSAN iSCSI Target',
        'identity': ['host_uuid', 'target'],
        'objects_observed': 0,
        'metrics': [
            'bandwidthRead',
            'bandwidthTotal',
            'bandwidthWrite',
            'iopsRead',
            'iopsTotal',
            'iopsWrite',
            'latencyRead',
            'latencyTotal',
            'latencyWrite',
            'queueDepth',
        ],
    },
}
