"""GENERATED -- do not edit by hand.

Regenerate with:
    python3 tools/model_from_perfsvc.py

Derived from a LIVE vSAN Performance Service, not its schema:
VsanPerfGetSupportedEntityTypes understates what is returned
(vsan-tcpip-stats advertises 16 metrics and returns 32), and 39
of 70 entity types return nothing when the feature is unused.
"""

from typing import Dict

ENTITIES: Dict[str, dict] = {
    'cluster-domclient': {
        'kind': 'VsanClusterDomclient',
        'label': 'Cluster Domclient',
        'identity': ['cluster_uuid'],
        'objects_observed': 1,
        'metrics': [
            'iopsRead',
            'throughputRead',
            'latencyAvgRead',
            'iopsWrite',
            'throughputWrite',
            'latencyAvgWrite',
            'congestion',
            'oio',
            'readCongestion',
            'writeCongestion',
            'unmapCongestion',
            'numOio',
            'readCount',
            'writeCount',
        ],
    },
    'cluster-domcompmgr': {
        'kind': 'VsanClusterDomcompmgr',
        'label': 'Cluster Domcompmgr',
        'identity': ['cluster_uuid'],
        'objects_observed': 1,
        'metrics': [
            'iopsRead',
            'throughputRead',
            'latencyAvgRead',
            'iopsWrite',
            'throughputWrite',
            'latencyAvgWrite',
            'iopsRecWrite',
            'throughputRecWrite',
            'latencyAvgRecWrite',
            'congestion',
            'oio',
            'iopsResyncRead',
            'tputResyncRead',
            'latAvgResyncRead',
            'numOio',
        ],
    },
    'cluster-domowner': {
        'kind': 'VsanClusterDomowner',
        'label': 'Cluster Domowner',
        'identity': ['cluster_uuid'],
        'objects_observed': 1,
        'metrics': [
            'avgResyncParallelism',
            'numCompleteResyncOps',
            'numCompleteResyncRwrBatches',
            'numCompleteRwrOps',
            'numInflightPriorityResyncJobs',
            'numInflightSharedResyncJobs',
            'numPendingDecomResyncJobs',
            'numPendingResyncJobs',
            'numRunningResyncJobs',
            'numSuspendedPriorityResyncJobs',
            'numSuspendedResyncChangemaps',
            'numSuspendedResyncJobs',
            'numSuspendedSharedResyncJobs',
            'avgDeltaCreationDomActiveLatency',
            'avgDeltaCreationDomCreationLatency',
            'numCompleteDeltaToBaseResyncOps',
            'numCompleteFullResyncOps',
            'numCompleteSiblingToDeltaResyncOps',
            'numPendingDeltaToBaseResyncJobs',
            'numPendingFullResyncJobs',
            'numPendingSiblingToDeltaResyncJobs',
            'numRunningDeltaToBaseResyncJobs',
            'numRunningFullResyncJobs',
            'numRunningSiblingToDeltaResyncJobs',
            'numSuspendedDeltaToBaseResyncJobs',
            'numSuspendedFullResyncJobs',
            'numSuspendedSiblingToDeltaResyncJobs',
            'totalDeltasCreatedCount',
            'oio',
            'numOio',
            'congestion',
            'readCongestion',
            'writeCongestion',
            'unmapCongestion',
            'iopsRead',
            'tputRead',
            'latencyAvgRead',
            'iopsWrite',
            'tputWrite',
            'latencyAvgWrite',
            'iopsRecWrite',
            'tputRecWrite',
            'latencyAvgRecWrite',
            'iopsResyncRead',
            'tputResyncRead',
            'latencyAvgResyncRead',
        ],
    },
    'cluster-rdt-network-latency': {
        'kind': 'VsanClusterRdtLatency',
        'label': 'vSAN Cluster RDT Latency',
        'identity': ['cluster_uuid'],
        'objects_observed': 1,
        'metrics': [
            'avgLatency',
            'minLatency',
            'maxLatency',
            'rxSbSpaceMin',
            'rxSbSpaceMax',
            'rxSbSpaceAvg',
            'txSbSpaceMin',
            'txSbSpaceMax',
            'txSbSpaceAvg',
            'txCtxQMin',
            'txCtxQMax',
            'txCtxQAvg',
            'txQLatMin',
            'txQLatMax',
            'txQLatAvg',
            'numReadyDelay',
            'kaReset',
        ],
    },
    'cluster-zdom-top-stats': {
        'kind': 'VsanClusterZdomTopStats',
        'label': 'Cluster Zdom Top Stats',
        'identity': ['cluster_uuid'],
        'objects_observed': 1,
        'metrics': [
            'iopsRead',
            'throughputRead',
            'latencyAvgRead',
            'iopsWrite',
            'throughputWrite',
            'latencyAvgWrite',
            'iopsUnmap',
            'throughputUnmap',
            'latencyAvgUnmap',
            'oioRead',
            'oioWrite',
            'oio',
        ],
    },
    'cmmds-net': {
        'kind': 'VsanCmmdsNet',
        'label': 'Cmmds Net',
        'identity': ['host_uuid'],
        'objects_observed': 4,
        'metrics': [
            'rdtRx',
            'rdtRxThroughput',
            'rdtTx',
            'rdtTxThroughput',
            'groupRx',
            'groupRxThroughput',
            'groupTxUcast',
            'groupTxUcastThroughput',
            'groupTxMcast',
            'groupTxMcastThroughput',
        ],
    },
    'dom-world-cpu': {
        'kind': 'VsanDomWorld',
        'label': 'vSAN DOM World',
        'identity': ['host_uuid', 'world_name', 'world_id'],
        'objects_observed': 315,
        'metrics': [
            'usedPct',
            'readyPct',
            'runPct',
        ],
    },
    'host-cpu': {
        'kind': 'VsanHostCpu',
        'label': 'vSAN Host CPU',
        'identity': ['host_uuid', 'cpu'],
        'objects_observed': 244,
        'metrics': [
            'coreUtilPct',
            'pcpuUtilPct',
            'pcpuUsedPct',
        ],
    },
    'host-domclient': {
        'kind': 'VsanHostDomclient',
        'label': 'Host Domclient',
        'identity': ['host_uuid'],
        'objects_observed': 4,
        'metrics': [
            'iops',
            'throughput',
            'latencyAvg',
            'latencyStddev',
            'ioCount',
            'congestion',
            'oio',
            'iopsRead',
            'throughputRead',
            'latencyAvgRead',
            'readCount',
            'iopsWrite',
            'throughputWrite',
            'latencyAvgWrite',
            'writeCount',
            'clientCacheHits',
            'clientCacheHitRate',
            'readCongestion',
            'writeCongestion',
            'numOio',
            'latencyMaxRead',
            'latencyMaxWrite',
            'iopsUnmap',
            'throughputUnmap',
            'latencyAvgUnmap',
            'unmapCount',
            'unmapCongestion',
            'latencyMaxUnmap',
            'latencyStddevRead',
            'latencyStddevWrite',
            'latencyStddevUnmap',
            'iopsSegCleanerUnmap',
            'segCleanerUnmapLeafOwnerLatency',
            'segCleanerUnmapLeafOwnerMaxLatencyAvgUs',
            'throughputSegCleanerUnmap',
            'latencyAvgSegCleanerUnmap',
            'latencyStddevSegCleanerUnmap',
            'latencyMaxSegCleanerUnmap',
            'segCleanerUnmapCongestion',
            'rateClientOpsNoMem',
            'rateClientOpsRetry',
            'rateClientOpsNoSpace',
            'rateClientOpsNoConnect',
            'rateClientOpsIoError',
            'rateClientOpsChecksumMismatch',
            'rateClientOpsLimitExceed',
            'rateClientOpsBadParam',
            'rateClientOpsNotSupported',
            'rateOtherClientOpsFailure',
            'oioRead',
            'oioWrite',
            'oioResyncRead',
            'oioRecoveryWrite',
            'burstsPerSecond',
            'avgBurstTotalTime',
            'avgBurstArrivalTime',
            'avgBurstCompletionTime',
            'avgBurstPeakOIO',
            'avgBurstPeakOutstandingKb',
            'avgPctTimeToPeak',
            'IOPSWithinBursts',
            'bandwidthWithinBursts',
            'numBurstStatsSkipped',
            'burstsPerSecondMultiObj',
            'avgBurstTotalTimeMultiObj',
            'avgBurstArrivalTimeMultiObj',
            'avgBurstCompletionTimeMultiObj',
            'avgBurstPeakOIOMultiObj',
            'avgBurstPeakOutstandingKbMultiObj',
            'avgPctTimeToPeakMultiObj',
            'IOPSWithinBurstsMultiObj',
            'bandwidthWithinBurstsMultiObj',
            'IOPSWithinBurstsExclFirstObj',
            'bandwidthWithinBurstsExclFirstObj',
            'lessSkewedMultiBurstsPerSecond',
            'serverSwitchCount',
            'serverSwitchLatencyMaxUs',
            'serverSwitchAvglatency',
        ],
    },
    'host-domcompmgr': {
        'kind': 'VsanHostDomcompmgr',
        'label': 'Host Domcompmgr',
        'identity': ['host_uuid'],
        'objects_observed': 4,
        'metrics': [
            'iops',
            'throughput',
            'latencyAvg',
            'latencyStddev',
            'ioCount',
            'congestion',
            'oio',
            'iopsRead',
            'throughputRead',
            'latencyAvgRead',
            'readCount',
            'iopsWrite',
            'throughputWrite',
            'latencyAvgWrite',
            'writeCount',
            'iopsRecWrite',
            'throughputRecWrite',
            'latencyAvgRecWrite',
            'recWriteCount',
            'iopsResyncRead',
            'tputResyncRead',
            'latAvgResyncRead',
            'resyncReadCount',
            'readCongestion',
            'writeCongestion',
            'recWriteCongestion',
            'resyncReadCongestion',
            'numOio',
            'latencyMaxRead',
            'latencyMaxWrite',
            'regulatorIopsRead',
            'regulatorIopsWrite',
            'sharedCongestion',
            'componentCongestion',
            'metadataQueueDepthRead',
            'metadataQueueDepthWrite',
            'namespaceQueueDepthRead',
            'namespaceQueueDepthWrite',
            'resyncQueueDepthRead',
            'resyncQueueDepthWrite',
            'vmdiskQueueDepthRead',
            'vmdiskQueueDepthWrite',
            'metadataDispatchedCostRead',
            'metadataDispatchedCostWrite',
            'namespaceDispatchedCostRead',
            'namespaceDispatchedCostWrite',
            'resyncDispatchedCostRead',
            'resyncDispatchedCostWrite',
            'vmdiskDispatchedCostRead',
            'vmdiskDispatchedCostWrite',
            'iopsUnmap',
            'throughputUnmap',
            'latencyAvgUnmap',
            'unmapCount',
            'iopsRecUnmap',
            'throughputRecUnmap',
            'latencyAvgRecUnmap',
            'recUnmapCount',
            'unmapCongestion',
            'recUnmapCongestion',
            'latencyMaxUnmap',
            'latencyStddevRead',
            'latencyStddevWrite',
            'latencyStddevUnmap',
            'rateCompmgrOpsNoMem',
            'rateCompmgrOpsRetry',
            'rateCompmgrOpsNoSpace',
            'rateCompmgrOpsNoConnect',
            'rateCompmgrOpsIoError',
            'rateCompmgrOpsChecksumMismatch',
            'rateCompmgrOpsLimitExceed',
            'rateCompmgrOpsBadParam',
            'rateCompmgrOpsNotSupported',
            'rateOtherCompmgrOpsFailure',
            'tputServiceVMRead',
            'latencyAvgServiceVMRead',
            'tputServiceVMWrite',
            'latencyAvgServiceVMWrite',
            'oioRead',
            'oioWrite',
            'oioResyncRead',
            'oioRecoveryWrite',
        ],
    },
    'host-domowner': {
        'kind': 'VsanHostDomowner',
        'label': 'Host Domowner',
        'identity': ['host_uuid'],
        'objects_observed': 4,
        'metrics': [
            'iops',
            'throughput',
            'latencyAvg',
            'latencyStddev',
            'ioCount',
            'congestion',
            'oio',
            'readCongestion',
            'writeCongestion',
            'recoveryWriteCongestion',
            'iopsRead',
            'tputRead',
            'latencyAvgRead',
            'readCount',
            'iopsResyncRead',
            'tputResyncRead',
            'latencyAvgResyncRead',
            'resyncReadCount',
            'iopsWrite',
            'tputWrite',
            'latencyAvgWrite',
            'writeCount',
            'iopsRecWrite',
            'tputRecWrite',
            'latencyAvgRecWrite',
            'recWriteCount',
            'numOio',
            'latencyMaxRead',
            'latencyMaxWrite',
            'iopsUnmap',
            'tputUnmap',
            'latencyAvgUnmap',
            'unmapCount',
            'iopsRecUnmap',
            'tputRecUnmap',
            'latencyAvgRecUnmap',
            'recUnmapCount',
            'unmapCongestion',
            'recoveryUnmapCongestion',
            'latencyMaxUnmap',
            'readLeafOwnerLatency',
            'writeLeafOwnerLatency',
            'unmapLeafOwnerLatency',
            'recoveryWriteLeafOwnerLatency',
            'recoveryUnmapLeafOwnerLatency',
            'numCompleteResyncOps',
            'numCompleteRwrOps',
            'numCompleteResyncRwrBatches',
            'avgResyncParallelism',
            'latencyStddevRead',
            'latencyStddevWrite',
            'latencyStddevUnmap',
            'numPendingResyncJobs',
            'numPendingDecomResyncJobs',
            'numSuspendedResyncJobs',
            'numSuspendedResyncChangemaps',
            'numSuspendedSharedResyncJobs',
            'numSuspendedPriorityResyncJobs',
            'numRunningResyncJobs',
            'numInflightSharedResyncJobs',
            'numInflightPriorityResyncJobs',
            'highOIOCount',
            'highOIOCountPercent',
            'highOIOThroughput',
            'highOIOBytes',
            'highOIODurationMs',
            'highOIODurationPercent',
            'highOIONumTimes',
            'highOIOAvgOIO',
            'highOIOAvgDurationMs',
            'highOIOAvgIOCount',
            'highOIOCountRead',
            'highOIOCountPercentRead',
            'highOIOThroughputRead',
            'highOIOBytesRead',
            'highOIODurationMsRead',
            'highOIODurationPercentRead',
            'highOIONumTimesRead',
            'highOIOAvgOIORead',
            'highOIOAvgDurationMsRead',
            'highOIOAvgIOCountRead',
            'highOIOCountWrite',
            'highOIOCountPercentWrite',
            'highOIOThroughputWrite',
            'highOIOBytesWrite',
            'highOIODurationMsWrite',
            'highOIODurationPercentWrite',
            'highOIONumTimesWrite',
            'highOIOAvgOIOWrite',
            'highOIOAvgDurationMsWrite',
            'highOIOAvgIOCountWrite',
            'readECLeafOwnerMaxLatencyAvgUs',
            'writeECLeafOwnerMaxLatencyAvgUs',
            'unmapECLeafOwnerMaxLatencyAvgUs',
            'numPendingFullResyncJobs',
            'numPendingDeltaToBaseResyncJobs',
            'numPendingSiblingToDeltaResyncJobs',
            'numRunningFullResyncJobs',
            'numRunningDeltaToBaseResyncJobs',
            'numRunningSiblingToDeltaResyncJobs',
            'numSuspendedFullResyncJobs',
            'numSuspendedDeltaToBaseResyncJobs',
            'numSuspendedSiblingToDeltaResyncJobs',
            'deltaSourceChanges',
            'resyncsStartedAsDeltaToBase',
            'resyncsEndedAsDeltaToBase',
            'deltaLeafGTEs',
            'leafGTEs',
            'totalDeltaCreationDomActiveLatency',
            'totalDeltaCreationDomCreationLatency',
            'totalDeltasCreatedCount',
            'numCompleteDeltaToBaseResyncOps',
            'numCompleteSiblingToDeltaResyncOps',
            'numCompleteFullResyncOps',
            'ownerECCacheNumCachedObjects',
            'ownerECCacheHitMissRatio',
            'ownerECCacheNumFailedAllocs',
            'ownerECCacheNumSuccessAllocs',
            'avgDeltaCreationDomActiveLatency',
            'avgDeltaCreationDomCreationLatency',
            'readECLeafOwnerMaxLatencyUs',
            'writeECLeafOwnerMaxLatencyUs',
            'unmapECLeafOwnerMaxLatencyUs',
            'readLeafOwnerMaxLatencyAvgUs',
            'writeLeafOwnerMaxLatencyAvgUs',
            'unmapLeafOwnerMaxLatencyAvgUs',
            'ecWriteCount',
            'ecStridedWriteCount',
            'ecStridedWriteHits',
            'ecCachedWriteCount',
            'ecCachedWriteHits',
            'ecFswCount',
            'twoPCPrepareRetryCount',
            'twoPCCommitCount',
            'twoPCCommitSize',
            'owner2PCCommitLatencyAvgUs',
            'twoPCReservedLSNUsedCount',
            'twoPCReservedLSNUnusedCount',
            'twoPCReservedLSNExhaustedCount',
            'iopsSegCleanerUnmap',
            'segCleanerUnmapLeafOwnerLatency',
            'segCleanerUnmapLeafOwnerMaxLatencyAvgUs',
            'throughputSegCleanerUnmap',
            'latencyAvgSegCleanerUnmap',
            'latencyStddevSegCleanerUnmap',
            'latencyMaxSegCleanerUnmap',
            'segCleanerUnmapCongestion',
            'resyncReadLeafOwnerLatency',
            'numNetSchedOwnerIops',
            'numNetSchedCompIops',
            'numNetSchedOwnerRecoveryWriteIops',
            'numNetSchedCompRecoveryWriteIops',
            'numNetSchedOwnerResyncReadIops',
            'numNetSchedCompResyncReadIops',
            'numNetSchedOwnerIopsLimit',
            'numNetSchedCompIopsLimit',
            'numNetSchedOwnerRecoveryWriteIopsLimit',
            'numNetSchedCompRecoveryWriteIopsLimit',
            'numNetSchedOwnerResyncReadIopsLimit',
            'numNetSchedCompResyncReadIopsLimit',
            'numNetSchedOwnerTpThrottled',
            'numNetSchedCompTpThrottled',
            'numNetSchedRecoveryWriteTpThrottled',
            'numNetSchedResyncReadTpThrottled',
            'numNetSchedOwnerRecoveryWriteTpThrottled',
            'numNetSchedCompRecoveryWriteTpThrottled',
            'numNetSchedOwnerResyncReadTpThrottled',
            'numNetSchedCompResyncReadTpThrottled',
            'numNetSchedHighBand',
            'numNetSchedMidBand',
            'numNetSchedLowBand',
            'numNetSchedHighBandLowLimit',
            'numNetSchedLowBandHighLimit',
            'numNetSchedMidBandHighLimit',
            'numNetSchedHighBandHighShare',
            'numNetSchedMidBandLowShare',
            'numNetSchedLowToHighBand',
            'numNetSchedLowToMidBand',
            'numNetSchedMidToLowBand',
            'numNetSchedMidToHighBand',
            'numNetSchedHighToLowBand',
            'numNetSchedHighToMidBand',
            'numNetSchedControllerActivations',
            'numNetSchedControllerIopsLimit',
            'numNetSchedResyncTotalSharePercent',
            'numNetSchedSeenTotalTpBps',
            'numNetSchedSeenResyncTpBps',
            'numNetSchedSeenNonResyncTpBps',
            'numNetSchedHighBandSec',
            'numNetSchedMidBandSec',
            'numNetSchedLowBandSec',
            'numNetSchedRollingAvgLatUs',
            'numBlockedResyncJobs',
            'numBlockedSharedResyncJobs',
            'numBlockedPriorityResyncJobs',
            'numBlockedFullResyncJobs',
            'numBlockedDeltaToBaseResyncJobs',
            'numBlockedSiblingToDeltaResyncJobs',
            'oioRead',
            'oioWrite',
            'oioResyncRead',
            'oioRecoveryWrite',
            'readLeafOwnerIops',
            'writeLeafOwnerIops',
            'readLeafOwnerThroughput',
            'writeLeafOwnerThroughput',
            'readLeafOwnerRetriesPerOp',
            'writeLeafOwnerRetriesPerOp',
            'readOwnerRetriesPerOp',
            'writeOwnerRetriesPerOp',
            'readLeafOwnerLatencyRemote',
            'writeLeafOwnerLatencyRemote',
            'resyncReadLeafOwnerLatencyRemote',
            'recoveryWriteLeafOwnerLatencyRemote',
            'readLeafOwnerLatencyLocal',
            'writeLeafOwnerLatencyLocal',
            'resyncReadLeafOwnerLatencyLocal',
            'recoveryWriteLeafOwnerLatencyLocal',
            'serverSwitchCount',
            'serverSwitchLatencyMaxUs',
            'serverSwitchAvglatency',
            'serverSwitchlatencyStddev',
            'rateOwnerOpsNoMem',
            'rateOwnerOpsRetry',
            'rateOwnerOpsNoSpace',
            'rateOwnerOpsNoConnect',
            'rateOwnerOpsIoError',
            'rateOwnerOpsChecksumMismatch',
            'rateOwnerOpsLimitExceed',
            'rateOwnerOpsBadParam',
            'rateOwnerOpsNotSupported',
            'rateOtherOwnerOpsFailure',
            'tputServiceVMRead',
            'latencyAvgServiceVMRead',
            'tputServiceVMWrite',
            'latencyAvgServiceVMWrite',
            'netSchedUnderUtilCount',
            'netSchedUnderUtilGuestBps',
            'netSchedUnderUtilTtlBps',
            'netSchedBandwidthDiscoveryBps',
            'netSchedBWDiscoverySessions',
            'netSchedBWReallocationSessions',
            'netSchedBWDiscoveryActions',
            'netSchedBWReallocationActions',
            'netSchedResyncGainsFromGuestCount',
            'netSchedBWDiscoveryUtilizationPct',
            'netSchedLatencyIncreaseFromResyncPerDiscoverySessionPct',
            'netSchedGuestIopsIncreasePerReallocationSession',
            'netSchedGuestIopsDecreasePerDiscoverySession',
            'netSchedResyncIopsIncreasePerDiscoverySession',
            'netSchedResyncIopsDecreasePerReallocationSession',
            'netSchedBWDiscoveredPerDiscoverySession',
            'netSchedBWReallocatedPerReallocationSession',
            'netSchedBWDiscoveryStopsDueToHighLatencyPct',
            'netSchedBWDiscoveryStopsDueToGainsFromGuestPct',
            'netSchedBWReallocationStopsDueToLowUtilizationPct',
            'netSchedBWReallocationStopsDueToHighSharePct',
            'netSchedBWDiscoveryAvgIntervalsUs',
            'netSchedBWReallocationAvgIntervalsUs',
            'netSchedAvgOwnerRecoveryWriteDelayMs',
            'netSchedAvgCompRecoveryWriteDelayMs',
            'netSchedAvgOwnerResyncReadDelayMs',
            'netSchedAvgCompResyncReadDelayMs',
            'twoPCPrepareLimitRetryResyncIOPS',
            'twoPCPrepareLimitRetryGuestIOPS',
            'twoPCPrepareLimitRetryOtherIOPS',
            'twoPCPrepareLimitRetryResyncAvgTimeMs',
            'twoPCPrepareLimitRetryGuestAvgTimeMs',
            'twoPCPrepareLimitRetryOtherAvgTimeMs',
            'twoPCBatchCommitSyncIOPS',
            'twoPCBatchCommitResyncIOPS',
            'twoPCBatchCommitGuestIOPS',
            'twoPCBatchCommitOtherIOPS',
            'twoPCBatchCommitBlockedBySyncIOPS',
            'twoPCBatchCommitBlockedByResyncIOPS',
            'twoPCBatchCommitBlockedByGuestIOPS',
            'twoPCBatchCommitBlockedByOtherIOPS',
            'netSchedBWDiscoveryStopsDueToLowUtilizationPct',
            'netSchedBWReallocationUtilizationRatio',
            'netSchedBWReallocationUtilizationRatioBelow',
            'netSchedBWReallocationUtilizationRatioAbove',
            'numNetSchedGuestLTLatUs',
            'numNetSchedLowBandThreshUs',
            'numSuspendedDedupResyncJobs',
            'numInflightDedupResyncJobs',
            'numPendingDedupResyncJobs',
            'latencyStddevResyncRead',
            'latencyStddevRecoveryWrite',
        ],
    },
    'host-vsansparse': {
        'kind': 'VsanHostVsansparse',
        'label': 'Host Vsansparse',
        'identity': ['host_uuid'],
        'objects_observed': 4,
        'metrics': [
            'iopsRead',
            'iopsWrite',
            'iopsGwe',
            'iopsRmw',
            'iopsWriteConflicts',
            'throughputRead',
            'throughputWrite',
            'latencyRead',
            'latencyWrite',
            'latencyGwe',
            'latencyCacheLookup',
            'cacheInserts',
            'cacheRemoves',
            'cacheEntries',
            'cacheAllocFails',
            'cacheEvictAttempts',
            'lruLockContentions',
            'cacheLockContentions',
            'cacheUpdateLatency',
            'cacheHitRate',
            'readsToLayer',
        ],
    },
    'host-zdom-top-stats': {
        'kind': 'VsanHostZdomTopStats',
        'label': 'Host Zdom Top Stats',
        'identity': ['host_uuid'],
        'objects_observed': 4,
        'metrics': [
            'iopsRead',
            'throughputRead',
            'latencyAvgRead',
            'readCount',
            'iopsWrite',
            'throughputWrite',
            'latencyAvgWrite',
            'writeCount',
            'iopsUnmap',
            'throughputUnmap',
            'latencyAvgUnmap',
            'unmapCount',
            'ioCount',
            'oioRead',
            'oioWrite',
            'oio',
            'readLatencyMaxUs',
            'writeLatencyMaxUs',
            'unmapLatencyMaxUs',
        ],
    },
    'rdt-net': {
        'kind': 'VsanRdtNet',
        'label': 'vSAN RDT Network',
        'identity': ['host_uuid'],
        'objects_observed': 4,
        'metrics': [
            'checksumMismatchCount',
        ],
    },
    'rdt-network-latency': {
        'kind': 'VsanRdtLatency',
        'label': 'vSAN RDT Latency',
        'identity': ['host_uuid'],
        'objects_observed': 4,
        'metrics': [
            'avgLatency',
            'minLatency',
            'maxLatency',
            'rxSbSpaceMin',
            'rxSbSpaceMax',
            'rxSbSpaceAvg',
            'txSbSpaceMin',
            'txSbSpaceMax',
            'txSbSpaceAvg',
            'txCtxQMin',
            'txCtxQMax',
            'txCtxQAvg',
            'txQLatMin',
            'txQLatMax',
            'txQLatAvg',
            'numReadyDelay',
            'kaReset',
        ],
    },
    'system-mem': {
        'kind': 'VsanSystemMemory',
        'label': 'vSAN System Memory',
        'identity': ['host_uuid'],
        'objects_observed': 4,
        'metrics': [
            'totalMbMemUsed',
            'pctMemUsed',
            'overcommitRatio',
        ],
    },
    'virtual-disk': {
        'kind': 'VsanVirtualDisk',
        'label': 'vSAN Virtual Disk',
        'identity': ['vdisk_uuid'],
        'objects_observed': 60,
        'metrics': [
            'iopsLimit',
            'NIOPSRead',
            'NIOPSWrite',
            'NIOPS',
            'NIOPSReadDelayed',
            'NIOPSWriteDelayed',
            'NIOPSDelayed',
        ],
    },
    'virtual-machine': {
        'kind': 'VsanVirtualMachine',
        'label': 'vSAN Virtual Machine',
        'identity': ['vm_uuid'],
        'objects_observed': 30,
        'metrics': [
            'iopsRead',
            'throughputRead',
            'latencyRead',
            'readCount',
            'iopsWrite',
            'throughputWrite',
            'latencyWrite',
            'writeCount',
        ],
    },
    'vnic-rdt-network-latency': {
        'kind': 'VsanVnicRdtLatency',
        'label': 'vSAN VMkernel RDT Latency',
        'identity': ['host_uuid', 'vmknic'],
        'objects_observed': 4,
        'metrics': [
            'avgLatency',
            'minLatency',
            'maxLatency',
            'rxSbSpaceMin',
            'rxSbSpaceMax',
            'rxSbSpaceAvg',
            'txSbSpaceMin',
            'txSbSpaceMax',
            'txSbSpaceAvg',
            'txCtxQMin',
            'txCtxQMax',
            'txCtxQAvg',
            'txQLatMin',
            'txQLatMax',
            'txQLatAvg',
            'numReadyDelay',
            'kaReset',
        ],
    },
    'vsan-cluster-capacity': {
        'kind': 'VsanClusterCapacity',
        'label': 'Vsan Cluster Capacity',
        'identity': ['cluster_uuid'],
        'objects_observed': 1,
        'metrics': [
            'total',
            'used',
            'free',
            'savedByDedup',
            'dedupRatio',
            'totalDpOverhead',
        ],
    },
    'vsan-cpu': {
        'kind': 'VsanCpu',
        'label': 'vSAN CPU',
        'identity': ['host_uuid'],
        'objects_observed': 4,
        'metrics': [
            'usedPct',
            'readyPct',
            'runPct',
            'avgUsedPct',
            'avgRunPct',
            'maxUsedPct',
            'maxRunPct',
        ],
    },
    'vsan-dp-historical-stats': {
        'kind': 'VsanDpHistoricalStats',
        'label': 'Vsan Dp Historical Stats',
        'identity': ['host_uuid'],
        'objects_observed': 1,
        'metrics': [
            'totalSnapshotCapacity',
        ],
    },
    'vsan-esa-disk-layer': {
        'kind': 'VsanEsaDiskLayer',
        'label': 'Vsan Esa Disk Layer',
        'identity': ['disk_uuid'],
        'objects_observed': 7,
        'metrics': [
            'tputReadPerf',
            'tputReadDiskPerf',
            'avgLatReadPerf',
            'iopsReadPerf',
            'maxReadTimePerf',
            'minReadTimePerf',
            'tputWritePerf',
            'avgLatWritePerf',
            'iopsWritePerf',
            'maxWriteTimePerf',
            'minWriteTimePerf',
            'tputReadCapacity',
            'tputReadDiskCapacity',
            'avgLatReadCapacity',
            'iopsReadCapacity',
            'maxReadTimeCapacity',
            'minReadTimeCapacity',
            'tputWriteCapacity',
            'avgLatWriteCapacity',
            'iopsWriteCapacity',
            'maxWriteTimeCapacity',
            'minWriteTimeCapacity',
            'iopsUnmapPerf',
            'tputUnmapPerf',
            'avgLatUnmapPerf',
            'maxUnmapTimePerf',
            'minUnmapTimePerf',
            'iopsUnmapCapacity',
            'tputUnmapCapacity',
            'avgLatUnmapCapacity',
            'maxUnmapTimeCapacity',
            'minUnmapTimeCapacity',
            'readCountPerf',
            'writeCountPerf',
            'readCountCapacity',
            'writeCountCapacity',
            'unmapCountPerf',
            'unmapCountCapacity',
        ],
    },
    'vsan-esa-disk-scsifw': {
        'kind': 'VsanEsaDiskScsifw',
        'label': 'Vsan Esa Disk Scsifw',
        'identity': ['disk_uuid'],
        'objects_observed': 7,
        'metrics': [
            'iopsDevRead',
            'throughputDevRead',
            'latencyDevRead',
            'ioCountDevRead',
            'iopsDevWrite',
            'throughputDevWrite',
            'latencyDevWrite',
            'ioCountDevWrite',
            'latencyDevDAvg',
            'latencyDevGAvg',
            'latencyDevKAvg',
            'outstandingCmdCount',
            'iopsDevUnmap',
            'throughputDevUnmap',
            'latencyDevUnmap',
            'ioCountDevUnmap',
        ],
    },
    'vsan-host-net': {
        'kind': 'VsanHostNet',
        'label': 'vSAN Host Network',
        'identity': ['host_uuid'],
        'objects_observed': 4,
        'metrics': [
            'rxThroughput',
            'rxPackets',
            'rxPacketsLossRate',
            'txThroughput',
            'txPackets',
            'txPacketsLossRate',
            'tcpTxPackets',
            'tcpRxPackets',
            'tcpTxRexmitRate',
            'tcpRxErrRate',
            'portRxpkts',
            'portTxpkts',
            'portRxDrops',
            'portTxDrops',
            'ioChainRxdrops',
            'ioChainTxdrops',
        ],
    },
    'vsan-memory': {
        'kind': 'VsanMemory',
        'label': 'vSAN Memory',
        'identity': ['host_uuid'],
        'objects_observed': 4,
        'metrics': [
            'kernelReservedSize',
            'uwReservedSize',
            'uwConsumedSize',
            'vsanmgmtdConsumedSize',
            'vsanmgmtdWatchdogConsumedSize',
            'clomdConsumedSize',
            'osfsdConsumedSize',
            'cmmdsdConsumedSize',
            'vitdConsumedSize',
            'vsandevicemonitordConsumedSize',
            'vsanobserverConsumedSize',
            'vsantracedConsumedSize',
            'epdConsumedSize',
            'cmmdsTimeMachineConsumedSize',
            'vsanmgmtdReservedSize',
            'vsanmgmtdWatchdogReservedSize',
            'clomdReservedSize',
            'osfsdReservedSize',
            'cmmdsdReservedSize',
            'vitdReservedSize',
            'vsandevicemonitordReservedSize',
            'vsanobserverReservedSize',
            'vsantracedReservedSize',
            'epdReservedSize',
            'cmmdsTimeMachineReservedSize',
            'uwMemAllocMin',
            'vsanmgmtdMemAllocMin',
            'vsanmgmtdWatchdogMemAllocMin',
            'clomdMemAllocMin',
            'osfsdMemAllocMin',
            'cmmdsdMemAllocMin',
            'vitdMemAllocMin',
            'vsandevicemonitordMemAllocMin',
            'vsanobserverMemAllocMin',
            'vsantracedMemAllocMin',
            'epdMemAllocMin',
            'cmmdsTimeMachineMemAllocMin',
            'uwMemAllocMax',
            'vsanmgmtdMemAllocMax',
            'vsanmgmtdWatchdogMemAllocMax',
            'clomdMemAllocMax',
            'osfsdMemAllocMax',
            'cmmdsdMemAllocMax',
            'vitdMemAllocMax',
            'vsandevicemonitordMemAllocMax',
            'vsanobserverMemAllocMax',
            'vsantracedMemAllocMax',
            'epdMemAllocMax',
            'cmmdsTimeMachineMemAllocMax',
            'kernelConsumedSize',
        ],
    },
    'vsan-pnic-net': {
        'kind': 'VsanPnic',
        'label': 'vSAN Physical NIC',
        'identity': ['host_uuid', 'vmnic'],
        'objects_observed': 7,
        'metrics': [
            'rxThroughput',
            'rxPackets',
            'rxPacketsLossRate',
            'txThroughput',
            'txPackets',
            'txPacketsLossRate',
            'portRxDrops',
            'portTxDrops',
            'pauseCount',
            'ioChainDrops',
            'ioChainRxdrops',
            'ioChainTxdrops',
            'portRxpkts',
            'portTxpkts',
            'rxErr',
            'rxDrp',
            'rxLgtErr',
            'rxOvErr',
            'rxCrcErr',
            'rxFrmErr',
            'rxFifoErr',
            'rxMissErr',
            'txErr',
            'txDrp',
            'txAbortErr',
            'txCarErr',
            'txFifoErr',
            'txHeartErr',
            'txWinErr',
            'pfcCount',
            'rxPacketsLossRateActual',
            'txPacketsLossRateActual',
            'portRxDropsActual',
            'portTxDropsActual',
            'pauseCountActual',
            'ioChainDropsActual',
            'ioChainRxdropsActual',
            'ioChainTxdropsActual',
            'rxErrActual',
            'rxDrpActual',
            'rxLgtErrActual',
            'rxOvErrActual',
            'rxCrcErrActual',
            'rxFrmErrActual',
            'rxFifoErrActual',
            'rxMissErrActual',
            'txErrActual',
            'txDrpActual',
            'txAbortErrActual',
            'txCarErrActual',
            'txFifoErrActual',
            'txHeartErrActual',
            'txWinErrActual',
            'pfcCountActual',
            'rxCrcErrRaw',
            'txCarErrRaw',
            'rxErrRaw',
            'txErrRaw',
            'pauseCountRaw',
            'pfcCountRaw',
            'rxMissErrRaw',
            'rxOvErrRaw',
            'rxFifoErrRaw',
            'rxPktRaw',
            'txPktRaw',
        ],
    },
    'vsan-tcpip-stats': {
        'kind': 'VsanTcpIp',
        'label': 'vSAN TCP/IP',
        'identity': ['host_uuid', 'stack'],
        'objects_observed': 4,
        'metrics': [
            'tcpTxPackets',
            'tcpRxPackets',
            'tcpTxRexmitRate',
            'tcpRxErrRate',
            'ipErrs',
            'ipTotal',
            'ip6Total',
            'ip6Errs',
            'tcpRxThroughput',
            'tcpTxThroughput',
            'tcpSndZeroWin',
            'tcpRcvduppackRate',
            'tcpRcvoopackRate',
            'tcpRcvdupackRate',
            'tcpSackRexmitsRate',
            'tcpSackSendBlocksRate',
            'tcpSackRcvBlocksRate',
            'tcpHalfopenDropRate',
            'tcpTimeoutDropRate',
            'tcpErrs',
            'tcpEcnCe',
            'arpDropRate',
            'tcpSndZeroWinActual',
            'tcpRcvduppackRateActual',
            'tcpRcvoopackRateActual',
            'tcpRcvdupackRateActual',
            'tcpSackRexmitsRateActual',
            'tcpSackSendBlocksRateActual',
            'tcpSackRcvBlocksRateActual',
            'tcpHalfopenDropRateActual',
            'tcpTimeoutDropRateActual',
            'tcpErrsActual',
        ],
    },
    'vsan-vnic-net': {
        'kind': 'VsanVnic',
        'label': 'vSAN VMkernel NIC',
        'identity': ['host_uuid', 'stack', 'vmknic'],
        'objects_observed': 4,
        'metrics': [
            'rxThroughput',
            'rxPackets',
            'rxPacketsLossRate',
            'txThroughput',
            'txPackets',
            'txPacketsLossRate',
            'tcpTxPackets',
            'tcpRxPackets',
            'tcpTxRexmitRate',
            'tcpRxErrRate',
            'ipErrs',
            'portRxDrops',
            'portTxDrops',
            'ioChainDrops',
            'tcpConnects',
            'tcpSndacks',
            'tcpRcvackpack',
            'tcpRcvduppack',
            'tcpRcvoopack',
            'tcpRcvdupack',
            'tcpSackRexmits',
            'tcpSackSendBlocks',
            'tcpSackRcvBlocks',
            'tcpKeeptimeo',
            'tcpPersisttimeo',
            'tcpRexmttimeo',
            'tcpTimeoutdrop',
            'tcpConndrops',
            'tcpDrops',
            'tcpKeepdrops',
            'tcpRcvmemdrop',
            'tcpBadsyn',
            'tcpBadrst',
            'tcpRcvbadsum',
            'tcpRcvbadoff',
            'tcpRcvshort',
            'ipTotal',
            'ip6Total',
            'ip6Errs',
            'ioChainRxdrops',
            'ioChainTxdrops',
            'portRxpkts',
            'portTxpkts',
            'tcpRxThroughput',
            'tcpTxThroughput',
            'tcpSndZeroWin',
            'tcpRcvduppackRate',
            'tcpRcvoopackRate',
            'tcpRcvdupackRate',
            'tcpSackRexmitsRate',
            'tcpSackSendBlocksRate',
            'tcpSackRcvBlocksRate',
            'tcpHalfopenDropRate',
            'tcpTimeoutDropRate',
            'tcpErrs',
            'tcpEcnCe',
            'arpDropRate',
            'rxPacketsLossRateActual',
            'txPacketsLossRateActual',
            'portRxDropsActual',
            'portTxDropsActual',
            'ioChainDropsActual',
            'ioChainRxdropsActual',
            'ioChainTxdropsActual',
        ],
    },
    'vscsi': {
        'kind': 'VsanVscsi',
        'label': 'vSAN vSCSI',
        'identity': ['vm_uuid', 'device'],
        'objects_observed': 106,
        'metrics': [
            'iopsRead',
            'throughputRead',
            'latencyRead',
            'readCount',
            'iopsWrite',
            'throughputWrite',
            'latencyWrite',
            'writeCount',
        ],
    },
    'zdom-vtx': {
        'kind': 'VsanZdomVtx',
        'label': 'Zdom Vtx',
        'identity': ['host_uuid'],
        'objects_observed': 4,
        'metrics': [
            'rateTxnReadWrite',
            'rateTotalCacheMiss',
            'rateTotalCacheRef',
            'rateBankFlushTotalCacheRef',
            'rateSegCleaningCtxDataTotalCacheRef',
            'latAvgCacheGet',
            'latAvgTotalOpIO',
            'allOpCacheMaxGetLatUSec',
            'rateTxnPrefetchTotalCacheRef',
            'rateTxnPrefetchLogicalTreeCacheRef',
            'rateTxnPrefetchMiddleTreeCacheRef',
            'rateTxnPrefetchSutCacheRef',
            'rateTxnPrefetchTotalCacheMiss',
            'rateTxnPrefetchLogicalTreeCacheMiss',
            'rateTxnPrefetchMiddleTreeCacheMiss',
            'rateTxnPrefetchSutCacheMiss',
            'rateTxnBankTotalCacheRef',
            'rateTxnBankLogicalTreeCacheRef',
            'rateTxnBankMiddleTreeCacheRef',
            'rateTxnBankSutCacheRef',
            'rateTxnBankTotalCacheMiss',
            'rateTxnBankLogicalTreeCacheMiss',
            'rateTxnBankMiddleTreeCacheMiss',
            'rateTxnBankSutCacheMiss',
            'latAvgTxnBank',
            'latAvgTxnBankTotalIO',
            'maxDiscUsedPct',
            'checkpointWorkerWakeupMs',
            'rateTxnUnmapTotalCacheMiss',
            'rateTxnUnmapLogicalTreeCacheMiss',
            'rateTxnUnmapMiddleTreeCacheMiss',
            'rateTxnUnmapSutCacheMiss',
            'latAvgTxnUnmap',
            'latAvgTxnUnmapTotalIO',
            'rateTxnSegCleaningCtxDataTotalCacheRef',
            'rateTxnSegCleaningCtxDataLogicalTreeCacheRef',
            'rateTxnSegCleaningCtxDataMiddleTreeCacheRef',
            'rateTxnSegCleaningCtxDataSutCacheRef',
            'rateTxnSegCleaningCtxDataTotalCacheMiss',
            'rateTxnSegCleaningCtxDataLogicalTreeCacheMiss',
            'rateTxnSegCleaningCtxDataMiddleTreeCacheMiss',
            'rateTxnSegCleaningCtxDataSutCacheMiss',
            'rateTxnLookupCacheRef',
            'rateTxnLookupLogicalTreeCacheRef',
            'rateTxnLookupMiddleTreeCacheRef',
            'rateTxnLookupCacheMiss',
            'rateTxnLookupLogicalTreeCacheMiss',
            'rateTxnLookupMiddleTreeCacheMiss',
            'rateTotalLogicalTreeCacheMiss',
            'rateTotalMiddleTreeCacheMiss',
            'rateTotalSnapTreeCacheMiss',
            'rateTotalBitmapCacheMiss',
            'rateTotalSutCacheMiss',
            'cacheMissPerPrefetchTxn',
            'cacheMissPerSegCleaningCtxDataTxn',
            'cacheMissPerLookupTxn',
            'txnDLogMaxLatUs',
            'txnBankMaxLatUs',
            'txnSegCtxDataMaxLatUs',
            'txnSegCtxLLPMaxLatUs',
            'txnVatWriteSegMaxLatUs',
            'txnUnmapMaxLatUs',
            'txnCacheFlushMaxLatUs',
            'txnDelExtMiddleTreeMaxLatUs',
            'txnPrefetchMaxLatUs',
            'txnLookupMaxLatUs',
            'prefetchCacheMaxGetLatUs',
            'iopsCacheMissRate',
            'tputCacheMissRate',
            'missesPerIO',
            'rateTotDirtyCachePage',
        ],
    },
}
