#!/usr/bin/env python3
"""Generate the metric reference section of README.md.

    python3 tools/build_metric_reference.py

Sources, in order of authority:

1. `docs/assets/perfsvc_schema.json` -- harvested from a live Performance
   Service (`VsanPerfGetSupportedEntityTypes`). Its per-metric `name` and
   `description` are Broadcom's own wording and are used verbatim where
   present. Regenerate with tools/model_from_perfsvc.py's sibling harvest.
2. `app/metric_labels.py` -- our derived labels and units, for everything the
   schema does not document.

The schema covers only 133 of the 730 metrics we collect. That is the same
understatement seen elsewhere: the service advertises fewer metrics than it
returns (vsan-tcpip-stats advertises 16 and returns 32).

Deliberately NOT taken from the schema: `unit`. It hangs off the *graph*, not
the metric, and a graph mixes metric kinds. Verified 2026-09-23 against live
values -- the graph says time_ms for latency while latencyAvgRead reads 589
(0.59 ms as microseconds; 589 ms would be absurd on an idle NVMe cluster), and
says rate_bytes for rxSbSpaceMin which reads 8,286,980, an 8 MB socket buffer
rather than 8 MB/s. Adopting it would have introduced a 1000x error.
"""
import json
import re
import sys

sys.path.insert(0, "app")
import metric_labels  # noqa: E402
import perfsvc_model  # noqa: E402

START = "<!-- METRIC-REFERENCE-START -->"
END = "<!-- METRIC-REFERENCE-END -->"


def load_schema(path="docs/assets/perfsvc_schema.json"):
    raw = json.load(open(path))
    flat = {}
    for metrics in raw.values():
        for mid, d in metrics.items():
            flat.setdefault(mid, d)
    return flat


def esc(text):
    return (text or "").replace("|", "\\|").strip()


def build() -> str:
    schema = load_schema()
    ents = perfsvc_model.ENTITIES
    documented = sum(1 for e in ents.values() for m in e["metrics"] if m in schema)
    total = sum(len(e["metrics"]) for e in ents.values())
    distinct = len({m for e in ents.values() for m in e["metrics"]})

    out = [START, "", "## Metric reference", "",
           f"Every metric this pack collects: **{total} attributes** "
           f"({distinct} distinct ids) across **{len(ents)} resource kinds**. "
           "Generated by `tools/build_metric_reference.py` -- do not edit by "
           "hand.", "",
           "**Definition** is Broadcom's own wording from the Performance "
           f"Service schema where it exists ({documented} of {total} "
           "attributes). The service documents far fewer metrics than it "
           "returns, so the remainder show a derived label only, marked "
           "*(derived)*. A derived entry describes what the metric is called, "
           "not what it measures -- treat it as a starting point, not an "
           "authority.", "",
           "Units are ours, not the schema's: the schema's unit hangs off the "
           "*graph* rather than the metric and disagrees with observed values "
           "by 1000x on latency. See the tool's docstring.", ""]

    for ent in sorted(ents):
        spec = ents[ent]
        metrics = sorted(spec["metrics"])
        out.append(f"### {spec['label']} — `{spec['kind']}`")
        out.append("")
        out.append(f"perfsvc entity `{ent}` · identified by "
                   f"{', '.join('`%s`' % i for i in spec['identity'])} · "
                   f"{spec['objects_observed']} objects observed · "
                   f"{len(metrics)} metrics")
        out.append("")
        out.append("| Metric | Name | Unit | Definition |")
        out.append("|---|---|---|---|")
        for mid in metrics:
            doc = schema.get(mid) or {}
            name = esc(doc.get("name")) or esc(metric_labels.LABELS.get(mid, mid))
            desc = esc(doc.get("description"))
            if not desc:
                desc = "*(derived)*"
            unit = metric_labels.UNITS.get(mid, "")
            unit = f"`{unit.split('.')[-1].lower()}`" if unit else ""
            out.append(f"| `{mid}` | {name} | {unit} | {desc} |")
        out.append("")
    out.append(END)
    return "\n".join(out)


def main() -> None:
    section = build()
    readme = open("README.md").read()
    if START in readme and END in readme:
        readme = re.sub(re.escape(START) + r".*?" + re.escape(END),
                        lambda _: section, readme, flags=re.S)
    else:
        readme = readme.rstrip() + "\n\n" + section + "\n"
    open("README.md", "w").write(readme)
    print(f"  wrote metric reference: {section.count(chr(10))} lines")


if __name__ == "__main__":
    main()
