#!/usr/bin/env python3
"""Generate content/CONTENT-INVENTORY.md from a built pak.

    python3 tools/gen_content_inventory.py ~/vsan-host-metrics/build/VsanHostMetrics_1.4.6.pak

Uninstalling the pack does NOT remove its dashboards and views, and there is no
API to delete them -- all of that is verified in the generated document. So the
only way to remove them is by hand, and the only way to do that safely is an
exact list of what belongs to us. Generating it from the pak keeps the list
honest; a hand-written one would drift the first time a view was renamed.
"""
import json
import sys
import xml.etree.ElementTree as ET
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOC = ROOT / "content" / "CONTENT-INVENTORY.md"

PROBED = [
    ("uninstalling the pack", "**removes the dashboards**; leaves the views"),
    ("uninstall hook in the pak format", "none exists; only install-time scripts"),
    ("`GET /suite-api/api/dashboards`", "404"),
    ("`GET /suite-api/internal/dashboards`", "404, with the unsupported-API header"),
    ("`GET /suite-api/api/views`, `/api/viewdefinitions`", "404"),
    ("`GET /suite-api/api/reportdefinitions`", "200, but contains none of ours"),
]


def main() -> int:
    if len(sys.argv) < 2:
        sys.exit("usage: gen_content_inventory.py <pak>")
    z = zipfile.ZipFile(sys.argv[1])
    ver = json.loads(z.read("manifest.txt"))["version"]

    dash = [(n, json.loads(z.read(n))) for n in sorted(z.namelist())
            if "/dashboards/" in n and n.endswith(".json")]
    views = [n for n in sorted(z.namelist())
             if "/reports/" in n and n.endswith(".xml")]
    if not dash or not views:
        sys.exit(f"refusing to write an empty inventory: {len(dash)} dashboards, "
                 f"{len(views)} views -- is that really a pak?")

    out = []
    w = out.append
    w("# What this pack installs, and how to remove it\n")
    w("Generated by `tools/gen_content_inventory.py` from the built pak. Do not")
    w("edit by hand.\n")
    w(f"Pack `iSDK_VsanHostMetrics` version **{ver}**.\n")
    w("## What uninstalling does and does not remove\n")
    w("Uninstalling the pack **does remove the dashboards**. It leaves the")
    w("**views**, and there is no API to delete those, so they have to go by hand.\n")
    w("An earlier version of this document claimed uninstall left the dashboards")
    w("too. That was wrong: the 404s below were measured, the uninstall behaviour")
    w("was inferred from them and never tested. Corrected from an actual")
    w("uninstall.\n")
    w("| interface | result |")
    w("|---|---|")
    for a, b in PROBED:
        w(f"| {a} | {b} |")
    w("")
    w("The views carry no marking that identifies them as this pack's, which is")
    w("why they are tedious to find among the built-in ones. Searching the Views")
    w("list for **`vSAN`** finds 29 of the 30. The exception is listed below.\n")
    w("Since 1.4.5 every id is a uuid5 derived from the title, so **reinstalling")
    w("replaces rather than duplicates**. You only need this list to remove the")
    w("pack entirely, or to clear the one-off duplicates left by upgrading from")
    w("1.4.4 or earlier, whose ids were random.\n")

    w(f"## Dashboards ({len(dash)})\n")
    w("Removed automatically by uninstalling the pack. Listed for the case where")
    w("you are clearing the one-off duplicates left by upgrading from 1.4.4 or")
    w("earlier, whose ids were random rather than derived.\n")
    w("| name | id |")
    w("|---|---|")
    for n, d in dash:
        db = d["dashboards"][0]
        w(f"| {db.get('name') or n.split('/')[-1][:-5]} | `{db['id']}` |")

    w(f"\n## Views ({len(views)})\n")
    w("**NOT removed by uninstalling.** Visualize -> Views, search `vSAN`, select,")
    w("Delete. These are the titles as the UI shows them.\n")
    w("| title | subject |")
    w("|---|---|")
    rows = []
    for n in views:
        root = ET.fromstring(z.read(n))
        # <Title> is what the Views list displays; the filename is not.
        t = root.find(".//Title")
        name = (t.text if t is not None and t.text else n.split("/")[-1][:-4])
        subj = root.find(".//SubjectType")
        rows.append((name, f"{subj.get('adapterKind','?')}/{subj.get('resourceKind','?')}"
                     if subj is not None else "-"))
    for name, subj in sorted(rows):
        flag = "" if "vsan" in name.lower() else "  **<- a `vSAN` search misses this one**"
        w(f"| {name}{flag} | `{subj}` |")

    w("\n## Objects\n")
    w("Removing the adapter instance stops collection. The OBJECTS persist until")
    w("they age out, and a reinstall before that re-adopts them because identity")
    w("is derived from vSAN uuids, not from the install. To test a genuinely")
    w("clean install, delete them explicitly:\n")
    w("    Administration -> Inventory -> filter adapter type VsanHostMetrics")
    w("    -> select all -> Delete\n")
    w("Confirm the filter returns zero before reinstalling. Skipping this step is")
    w("why an upgrade can appear to work when nothing has changed.")

    DOC.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {DOC.relative_to(ROOT)}: {len(dash)} dashboards, {len(views)} views")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
